"""Default markdown templates for journal documents.

Templates use {{variable}} placeholders that get substituted on creation.
"""
from __future__ import annotations

from datetime import date, timedelta


DAILY_NOTE_TEMPLATE = """\
# {{date}} ({{weekday}})

[[{{yesterday}}]] | [[{{tomorrow}}]]

---

## Morning Report
*Generated by The Claw*

## Log
*Running transcript of the day — tasks, decisions, thoughts, research.*

## Evening Check-in
*Added at 16:30 JST*
"""

WEEKLY_REVIEW_TEMPLATE = """\
# Weekly Review — {{date}}

## 🏆 Wins this week
- 

## ❌ What didn't work?
- 

## 🎯 Goal progress
- **Sautai:** 
- **Academy Watch:** 
- **NBHD United:** 

## 💰 Budget check
- On track? Adjustments?

## 📅 Next week's focus
1. 
2. 
3. 

## 💪 Energy / health check
- 

## 💡 Ideas to explore
- 

## 📝 Notes for The Claw
- 
"""

MONTHLY_REVIEW_TEMPLATE = """\
# Monthly Review — {{date}}

## Last month summary
### Major accomplishments
- 

### Lessons learned
- 

## 🎯 Goal progress
- **Sautai:** 
- **Academy Watch:** 
- **NBHD United:** 

## Keep / Stop / Start
- **Keep doing:** 
- **Stop doing:** 
- **Start doing:** 

## 📋 Project status
- **Active:** 
- **Paused:** 
- **Archived:** 

## 🎯 This month's theme/focus
- 

## 💰 Financial review
- 

## 📝 Notes for The Claw
- 
"""

GOALS_TEMPLATE = """\
# Goals

## Active Goals

*Add goals here. Use the format below for each goal.*

### 🎯 [Goal Name]
**Target:** [Specific, measurable outcome]
**Why:** [1-2 sentences on motivation]
**Status:** [Current status]
**Next milestone:** [What success looks like in the next 2-4 weeks]

---

*Add new goals by editing this document.*
"""

TASKS_TEMPLATE = """\
# Tasks

## 🔥 Active
- [ ] 

## ⏳ Waiting
- [ ] 

## ✅ Done
- [x] 

---

*Tasks get added throughout the day. Evening check-in reviews what's done and what carries forward.*
"""

IDEAS_TEMPLATE = """\
# Ideas

Capture everything. Sort later.

## 💡 Active Ideas
- 

## 🧊 Ice Box
- 

---

*Drop ideas here anytime.*
"""

MEMORY_TEMPLATE = """\
# Memory

*Agent-curated long-term memory about the user. Preferences, goals, decisions, and lessons learned.*
"""

PROJECT_TEMPLATE = """\
# {{title}}

## Overview
*Project description*

## Current Status
*Where things stand*

## Next Steps
- [ ] 

## Notes
- 
"""

EVENING_CHECKIN_TEMPLATE = """\
## What got done today?
- 

## What didn't get done? Why?
- 

## Plan for tomorrow (top 3)
1. 
2. 
3. 

## Overnight work for The Claw
- 

## Blockers or decisions needed?
- 

## Energy/mood (1-10)
- 
"""


_WEEKDAY_NAMES = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]


def render_template(template: str, context: dict[str, str]) -> str:
    """Substitute {{key}} placeholders in a template string."""
    result = template
    for key, value in context.items():
        result = result.replace("{{" + key + "}}", value)
    return result


def daily_note_context(d: date) -> dict[str, str]:
    """Build template context for a daily note."""
    yesterday = d - timedelta(days=1)
    tomorrow = d + timedelta(days=1)
    return {
        "date": str(d),
        "weekday": _WEEKDAY_NAMES[d.weekday()],
        "yesterday": str(yesterday),
        "tomorrow": str(tomorrow),
    }


def get_default_template(kind: str) -> str:
    """Return the default markdown template for a document kind."""
    templates = {
        "daily": DAILY_NOTE_TEMPLATE,
        "weekly": WEEKLY_REVIEW_TEMPLATE,
        "monthly": MONTHLY_REVIEW_TEMPLATE,
        "goal": GOALS_TEMPLATE,
        "project": PROJECT_TEMPLATE,
        "tasks": TASKS_TEMPLATE,
        "ideas": IDEAS_TEMPLATE,
        "memory": MEMORY_TEMPLATE,
    }
    return templates.get(kind, "")
