# Generated by Django 5.1.15 on 2026-02-16 13:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0009_migrate_tier_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformIssueLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('missing_capability', 'Missing Capability'), ('tool_error', 'Tool Error'), ('config_issue', 'Configuration Issue'), ('rate_limit', 'Rate Limit Hit'), ('auth_error', 'Authentication Error'), ('other', 'Other')], default='other', max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('tool_name', models.CharField(blank=True, default='', help_text='Name of the tool that failed or was missing', max_length=100)),
                ('summary', models.CharField(max_length=500)),
                ('detail', models.TextField(blank=True, default='', help_text='Additional context (no user PII)')),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_issues', to='tenants.tenant')),
            ],
            options={
                'db_table': 'platform_issue_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='platform_is_tenant__9e48ef_idx'), models.Index(fields=['category', 'resolved'], name='platform_is_categor_495b8c_idx')],
            },
        ),
    ]
