# Generated by Django 6.0.7 on 2026-08-19 02:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform_logs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolContractEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "namespace",
                    models.CharField(
                        default="runtime",
                        help_text="Call-site namespace; selects the detail-key allowlist.",
                        max_length=32,
                    ),
                ),
                (
                    "tool_name",
                    models.CharField(
                        help_text="Tool or runtime endpoint name (URL name for generic capture).", max_length=120
                    ),
                ),
                ("tenant_id", models.UUIDField(blank=True, null=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("normalized", "Normalized"),
                            ("error", "Error"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Short slug explaining a non-accepted outcome (e.g. http_400).",
                        max_length=64,
                    ),
                ),
                (
                    "detail",
                    models.JSONField(
                        blank=True, default=dict, help_text="Allowlisted scalar flags only — never free text."
                    ),
                ),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "tool_contract_events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["tool_name", "outcome", "-created_at"], name="tool_contra_tool_na_ec5eb9_idx"),
                    models.Index(fields=["-created_at"], name="tool_contra_created_02e3b6_idx"),
                    models.Index(fields=["tenant_id", "-created_at"], name="tool_contra_tenant__1dfec1_idx"),
                ],
            },
        ),
    ]
