# Generated by Django 5.1.15 on 2026-04-30 15:50

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0049_tenant_byo_models_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="BYOCredential",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "provider",
                    models.CharField(choices=[("anthropic", "Anthropic"), ("openai", "OpenAI")], max_length=20),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("api_key", "API Key"), ("cli_subscription", "CLI Subscription")], max_length=20
                    ),
                ),
                ("key_vault_secret_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending verification"),
                            ("verified", "Verified"),
                            ("expired", "Expired"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                (
                    "seed_version",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Bumped on every paste/re-paste. Phase 2 Codex entrypoint will compare this against an on-disk marker to decide whether to overwrite the file-share-resident auth.json. Phase 1 (Anthropic env-var) ignores this field.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="byo_credentials", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("tenant", "provider"), name="byo_one_credential_per_provider")
                ],
            },
        ),
    ]
