# Generated by Django 5.1.15 on 2026-04-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fuel", "0002_fuelprofile"),
        ("tenants", "0041_merge_0040_pat_and_fuel"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="workout",
            index=models.Index(fields=["tenant", "status", "date"], name="fuel_workou_tenant__d622d0_idx"),
        ),
    ]
