# Generated by Django 5.1.15 on 2026-04-22 12:26

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fuel", "0003_status_date_index"),
        ("tenants", "0041_merge_0040_pat_and_fuel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="status",
            field=models.CharField(
                choices=[("done", "Done"), ("planned", "Planned"), ("rest", "Rest")], default="done", max_length=10
            ),
        ),
        migrations.CreateModel(
            name="FuelGoal",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("exercise_name", models.CharField(max_length=128)),
                ("metric", models.CharField(default="est_1rm", max_length=16)),
                ("target_value", models.DecimalField(decimal_places=2, max_digits=8)),
                ("target_date", models.DateField(blank=True, null=True)),
                ("achieved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="fuel_goals", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "fuel_goals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutTemplate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Template name, e.g. 'Push Day A'", max_length=128)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("strength", "Strength"),
                            ("cardio", "Cardio"),
                            ("hiit", "HIIT"),
                            ("calisthenics", "Calisthenics"),
                            ("mobility", "Mobility"),
                            ("sport", "Sport"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("activity", models.CharField(max_length=128)),
                ("duration_minutes", models.IntegerField(blank=True, null=True)),
                ("detail_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_templates",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "fuel_workout_templates",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="PersonalRecord",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("exercise_name", models.CharField(max_length=128)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("strength", "Strength"),
                            ("cardio", "Cardio"),
                            ("hiit", "HIIT"),
                            ("calisthenics", "Calisthenics"),
                            ("mobility", "Mobility"),
                            ("sport", "Sport"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, help_text="The new record value", max_digits=8)),
                ("previous_value", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                (
                    "metric",
                    models.CharField(default="est_1rm", help_text="est_1rm, distance, hold_s, reps", max_length=16),
                ),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_records",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="prs", to="fuel.workout"
                    ),
                ),
            ],
            options={
                "db_table": "fuel_personal_records",
                "ordering": ["-date", "-created_at"],
                "indexes": [models.Index(fields=["tenant", "exercise_name"], name="fuel_person_tenant__119568_idx")],
            },
        ),
        migrations.CreateModel(
            name="RestingHeartRateLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("date", models.DateField()),
                (
                    "bpm",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(20),
                            django.core.validators.MaxValueValidator(250),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="rhr_logs", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "fuel_resting_heart_rate",
                "ordering": ["-date"],
                "unique_together": {("tenant", "date")},
            },
        ),
    ]
