# Generated by Django 5.1.15 on 2026-04-22 16:53

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fuel", "0004_v2_features"),
        ("tenants", "0042_cron_wake_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="SleepLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("date", models.DateField()),
                (
                    "duration_hours",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Sleep duration in hours, e.g. 7.5",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(24),
                        ],
                    ),
                ),
                (
                    "quality",
                    models.IntegerField(
                        blank=True,
                        help_text="Sleep quality rating 1-5 (optional)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True, default="", help_text="Optional notes, e.g. 'woke up twice'")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sleep_logs", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "fuel_sleep",
                "ordering": ["-date"],
                "unique_together": {("tenant", "date")},
            },
        ),
    ]
