# Generated by Django 5.1.15 on 2026-04-24

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fuel", "0005_sleep_log"),
        ("tenants", "0042_cron_wake_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutPlan",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Plan name, e.g. '4-Week Strength Builder'", max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("start_date", models.DateField(help_text="First day of the plan")),
                (
                    "weeks",
                    models.IntegerField(
                        help_text="Plan duration in weeks",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(52),
                        ],
                    ),
                ),
                (
                    "days_per_week",
                    models.IntegerField(
                        help_text="Training days per week in this plan",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                    ),
                ),
                (
                    "schedule_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Weekly template: keys are weekday indices (0=Mon..6=Sun), values are workout definitions",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", help_text="Programming notes, progression strategy"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_plans",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "fuel_workout_plans",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["tenant", "status"], name="fuel_workout_tenant_status_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="workout",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                help_text="The workout plan this belongs to, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workouts",
                to="fuel.workoutplan",
            ),
        ),
        migrations.AddField(
            model_name="fuelprofile",
            name="preferred_days",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Preferred training days as weekday indices: 0=Monday ... 6=Sunday, e.g. [0, 2, 4]",
            ),
        ),
        migrations.AddField(
            model_name="fuelprofile",
            name="preferred_time",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Preferred workout time: morning, afternoon, evening, or empty",
                max_length=16,
            ),
        ),
    ]
