# Generated by Django 5.1.15 on 2026-05-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fuel", "0010_stamp_set_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="fuelprofile",
            name="distance_unit",
            field=models.CharField(
                choices=[("km", "Kilometers"), ("mi", "Miles")],
                default="km",
                help_text="User's preferred distance unit for cardio. Storage is always km; the UI converts on display. Elevation follows: km → meters, mi → feet.",
                max_length=4,
            ),
        ),
    ]
