# Generated by Django 5.1.15 on 2026-05-28 16:12

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fuel", "0011_fuelprofile_distance_unit"),
        ("tenants", "0076_welcome_email_and_first_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="edit_lock_owner",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Owner of the active edit lock; 'user' or 'assistant' (currently always 'user'). Empty when no lock is held.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="workout",
            name="edit_lock_until",
            field=models.DateTimeField(
                blank=True,
                help_text="When set and in the future, the user is actively editing this workout. Runtime PATCHes during the lock window return 409. The browser acquires on edit-mode entry and heartbeats every 30s.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workout",
            name="last_edited_by_user_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Most recent user-side PATCH timestamp. Populated when status=done and the edit happened more than 24h after creation, so the UI can show an 'Edited <relative>' footnote on completed sessions.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workout",
            name="version",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Monotonic write counter. Bumped on every save (user or runtime). Used by clients for optimistic-concurrency If-Match checks.",
            ),
        ),
        migrations.CreateModel(
            name="PlanSlot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "week_index",
                    models.PositiveSmallIntegerField(
                        help_text="0-indexed week within the plan (0..plan.weeks-1).",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(51),
                        ],
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        help_text="Weekday index, 0=Monday..6=Sunday (matches Python's date.weekday()).",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When set, the slot has been removed from the active schedule but lingers because a workout row still references it.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        help_text="Slots are owned by a plan; cascade-delete when the plan dies.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="fuel.workoutplan",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Denormalized for RLS scoping; matches Workout/WorkoutPlan pattern.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_slots",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "fuel_plan_slots",
                "ordering": ["plan_id", "week_index", "weekday"],
            },
        ),
        migrations.AddField(
            model_name="workout",
            name="slot",
            field=models.ForeignKey(
                blank=True,
                help_text="Stable plan-slot identity. Survives plan regen so the row's uuid stays valid for an open browser drawer. Null for standalone (non-plan) workouts or backfill-mismatched rows.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workouts",
                to="fuel.planslot",
            ),
        ),
        migrations.AddIndex(
            model_name="planslot",
            index=models.Index(fields=["tenant", "archived_at"], name="fuel_plan_s_tenant__fb17e4_idx"),
        ),
        migrations.AddIndex(
            model_name="planslot",
            index=models.Index(fields=["plan", "archived_at"], name="fuel_plan_s_plan_id_a50894_idx"),
        ),
        migrations.AddConstraint(
            model_name="planslot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("archived_at__isnull", True)),
                fields=("plan", "week_index", "weekday"),
                name="unique_active_plan_slot",
            ),
        ),
    ]
