# Generated by Django 5.1.15 on 2026-06-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fuel", "0013_backfill_plan_slots"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutplan",
            name="objective",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Structured one-line objective for the plan, e.g. 'Run a sub-25 5K' or 'Build pull strength'. The plan's through-line, kept out of free-form notes.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="workoutplan",
            name="week_overrides",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-week progression/deload: keys are 0-indexed week offsets, values are partial schedule_json overrides merged over the base template for that week (a day mapped to null = rest). Empty means every week uses the base template unchanged.",
            ),
        ),
    ]
