# Generated by Django 5.1.15 on 2026-06-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fuel", "0014_workoutplan_objective_workoutplan_week_overrides"),
        ("tenants", "0086_migrate_minimax_preferred_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="fuelprofile",
            name="healthkit_tombstones",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="external_ids of deleted HealthKit-sourced workouts (FIFO-capped). Consulted by the sync endpoint so an anchor reset (reinstall) cannot resurrect a workout the user deleted.",
            ),
        ),
        migrations.AddField(
            model_name="workout",
            name="external_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Stable id of the upstream record for imported workouts (HealthKit sample UUID). Unique per tenant when non-empty — the idempotency anchor for at-least-once sync delivery.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="source",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("assistant", "Assistant"),
                    ("template", "Template"),
                    ("healthkit", "HealthKit"),
                ],
                default="user",
                help_text="Who created this session.",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="workout",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), _negated=True),
                fields=("tenant", "external_id"),
                name="unique_workout_external_id",
            ),
        ),
    ]
