# Generated by Django 5.1.15 on 2026-06-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fuel", "0015_fuelprofile_healthkit_tombstones_workout_external_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="duration_seconds",
            field=models.IntegerField(
                blank=True,
                help_text="Precise active duration in seconds (from HealthKit / fine-grained entry). When present it drives cardio pace; duration_minutes stays the rounded display value. Null for legacy rows synced before seconds capture.",
                null=True,
            ),
        ),
    ]
