# Generated by Django 6.0.7 on 2026-07-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fuel", "0017_workout_congratulated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="fuelprofile",
            name="additional_context_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="fuelprofile",
            name="limitations_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="sleeplog",
            name="notes_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="workout",
            name="activity_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="workout",
            name="detail_json_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="workout",
            name="notes_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="workout",
            name="notes_thread_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="workout",
            name="skip_reason_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="workoutplan",
            name="name_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="workoutplan",
            name="notes_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="workoutplan",
            name="objective_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="workouttemplate",
            name="detail_json_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="workouttemplate",
            name="name_enc",
            field=models.BinaryField(null=True),
        ),
    ]
