# Generated by Django 6.0.7 on 2026-08-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fuel", "0018_fuelprofile_additional_context_enc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fuelprofile",
            name="pii_receipts",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="sleeplog",
            name="pii_receipts",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="workout",
            name="pii_receipts",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="workoutplan",
            name="pii_receipts",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="workouttemplate",
            name="pii_receipts",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
