# Generated by Django 6.0.7 on 2026-09-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fuel", "0019_fuelprofile_pii_receipts_sleeplog_pii_receipts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
