# Generated by Django 5.1.15 on 2026-05-22 07:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0006_lineoutboundmessage'),
        ('tenants', '0068_pii_denylist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProactiveOutbound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('line', 'Line')], max_length=16)),
                ('channel_user_id', models.CharField(help_text='Per-channel user identifier (line_user_id for LINE, Telegram chat_id stringified for Telegram).', max_length=128)),
                ('message_text', models.TextField(help_text='Full proactive message body as sent (post-PII-rehydration).')),
                ('job_name', models.CharField(blank=True, default='', help_text='Cron job name if the send originated from a cron session (read from X-NBHD-Job-Name header). Empty for main-session or ad-hoc proactive sends.', max_length=64)),
                ('parsed_items', models.JSONField(blank=True, default=list, help_text='Markdown bullets / numbered items extracted from ``message_text`` as list[str]. Empty list when the body has no list structure. Used by the envelope to render structured anchors so a multi-paragraph reply can be mapped by index.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_at', models.DateTimeField(blank=True, help_text='Set when this row was first surfaced into an inbound envelope. Kept for audit even after consumption — the envelope still surfaces consumed rows within a short follow-up window so back-to-back replies still see context.', null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proactive_outbounds', to='tenants.tenant')),
            ],
            options={
                'db_table': 'proactive_outbounds',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'channel', 'channel_user_id', '-created_at'], name='proactive_outb_thread_idx'), models.Index(fields=['created_at'], name='proactive_outb_created_idx')],
            },
        ),
    ]
