# Generated by Django 5.1.15 on 2026-05-22 07:12

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("router", "0006_lineoutboundmessage"),
        ("tenants", "0068_pii_denylist"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProactiveOutbound",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("channel", models.CharField(choices=[("telegram", "Telegram"), ("line", "Line")], max_length=16)),
                (
                    "channel_user_id",
                    models.CharField(
                        help_text="Per-channel user identifier (line_user_id for LINE, Telegram chat_id stringified for Telegram).",
                        max_length=128,
                    ),
                ),
                (
                    "message_text",
                    models.TextField(help_text="Full proactive message body as sent (post-PII-rehydration)."),
                ),
                (
                    "job_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Cron job name if the send originated from a cron session (read from X-NBHD-Job-Name header). Empty for main-session or ad-hoc proactive sends.",
                        max_length=64,
                    ),
                ),
                (
                    "parsed_items",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Markdown bullets / numbered items extracted from ``message_text`` as list[str]. Empty list when the body has no list structure. Used by the envelope to render structured anchors so a multi-paragraph reply can be mapped by index.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consumed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when this row was first surfaced into an inbound envelope. Kept for audit even after consumption — the envelope still surfaces consumed rows within a short follow-up window so back-to-back replies still see context.",
                        null=True,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proactive_outbounds",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "proactive_outbounds",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "channel", "channel_user_id", "-created_at"], name="proactive_outb_thread_idx"
                    ),
                    models.Index(fields=["created_at"], name="proactive_outb_created_idx"),
                ],
            },
        ),
        # Enable RLS to match the public-schema lockdown invariant
        # (tenants/0059 + tenants/0066). Test
        # ``test_rls_enabled_on_owned_public_tables`` will fail otherwise.
        # No policies are defined here: the Django backend connects as the
        # table owner and bypasses RLS by default, while the anon role
        # PostgREST exposes has no SELECT/INSERT/UPDATE grant on this
        # table — locking it down structurally rather than via policy.
        # Mirrors apps/router/migrations/0006_lineoutboundmessage.py.
        migrations.RunSQL(
            sql="ALTER TABLE proactive_outbounds ENABLE ROW LEVEL SECURITY;",
            # Intentionally NOT disabling RLS on reverse — would re-expose
            # the table via PostgREST/anon. The table itself is dropped by
            # the reverse of CreateModel anyway, so this RunSQL has nothing
            # meaningful to undo.
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
