# Generated by Django 5.1.15 on 2026-05-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("router", "0007_proactive_outbound"),
    ]

    operations = [
        migrations.CreateModel(
            name="LineQuotaState",
            fields=[
                ("id", models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                (
                    "line_quota_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Monthly Push-message cap from /v2/bot/message/quota. Null before the first successful poll.",
                        null=True,
                    ),
                ),
                (
                    "line_quota_used",
                    models.PositiveIntegerField(
                        default=0, help_text="Push messages used this month from /v2/bot/message/quota/consumption."
                    ),
                ),
                (
                    "line_quota_checked_at",
                    models.DateTimeField(blank=True, help_text="Timestamp of the last successful poll.", null=True),
                ),
                (
                    "line_quota_pre_warn_sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the 90% pre-warn email was last sent. Cleared when usage drops back below the threshold (next month) so the next event fires fresh.",
                        null=True,
                    ),
                ),
                (
                    "line_quota_exhausted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the system entered the exhausted state. Set by the 429 tripwire or by the daily poll seeing used >= limit. Cleared by the poll when usage drops back below the cap. Presence drives the frontend LINE-disabled gate.",
                        null=True,
                    ),
                ),
                (
                    "line_quota_exhausted_notified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the exhaustion fan-out (user emails + channel flips) last completed. Compared against ``line_quota_exhausted_at`` for idempotency: if the handler is dispatched twice for the same exhaustion event (tripwire + poll race), the second dispatch bails. Cleared on recovery so the next event fires fresh.",
                        null=True,
                    ),
                ),
                (
                    "line_quota_recovered_notified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the 'LINE is back — want to switch?' fan-out emails last completed. Cleared the next time we enter exhausted.",
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "line_quota_state",
            },
        ),
        # Enable RLS to match the public-schema lockdown invariant
        # (tenants/0059 + tenants/0066). The Django backend connects as
        # the table owner and bypasses RLS; the anon role PostgREST
        # exposes has no SELECT/INSERT/UPDATE grant on this table —
        # locking it down structurally rather than via policy. Mirrors
        # apps/router/migrations/0007_proactive_outbound.py.
        migrations.RunSQL(
            sql="ALTER TABLE line_quota_state ENABLE ROW LEVEL SECURITY;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
