# Generated by Django 5.1.15 on 2026-06-07 03:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("router", "0008_line_quota_state"),
        ("tenants", "0082_tenant_fuel_version"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingmessage",
            name="channel",
            field=models.CharField(choices=[("telegram", "Telegram"), ("line", "Line"), ("ios", "Ios")], max_length=16),
        ),
        migrations.CreateModel(
            name="ChatThread",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(blank=True, default="", max_length=120)),
                (
                    "is_main",
                    models.BooleanField(
                        default=False, help_text="The shared default thread resumed by every channel. One per tenant."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_active_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="chat_threads", to="tenants.tenant"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_threads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_threads",
                "ordering": ["-last_active_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AppChatMessage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "client_msg_id",
                    models.CharField(help_text="Client-supplied stable id. Idempotency key + poll key.", max_length=64),
                ),
                ("user_text", models.TextField()),
                ("reply_text", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("ready", "Ready"), ("error", "Error")],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "error",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Machine-readable error reason when status=error (e.g. 'budget_exhausted').",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("replied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_chat_messages",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="router.chatthread"
                    ),
                ),
            ],
            options={
                "db_table": "app_chat_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="chatthread",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_main", True)), fields=("tenant",), name="uniq_main_thread_per_tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="appchatmessage",
            index=models.Index(fields=["thread", "created_at"], name="appchat_thread_idx"),
        ),
        migrations.AddConstraint(
            model_name="appchatmessage",
            constraint=models.UniqueConstraint(fields=("tenant", "client_msg_id"), name="uniq_app_chat_client_msg"),
        ),
    ]
