# Generated by Django 5.1.15 on 2026-06-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("router", "0011_appchatmessage_waking_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="appchatmessage",
            name="source",
            field=models.CharField(
                choices=[("tenant", "Tenant"), ("on_device", "On Device")],
                default="tenant",
                help_text="Where the assistant reply was produced: the tenant runtime, or the client's on-device model (recorded post-hoc).",
                max_length=16,
            ),
        ),
    ]
