# Generated by Django 5.1.15 on 2026-06-16 04:32

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("router", "0013_appchatmessage_phase_appchatmessage_phase_detail"),
        ("tenants", "0087_tenant_last_wake_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceToken",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("token", models.CharField(max_length=200)),
                (
                    "environment",
                    models.CharField(
                        choices=[("sandbox", "Sandbox"), ("production", "Production")],
                        default="production",
                        help_text="Which APNs host the token is valid for (sandbox builds vs App Store / TestFlight).",
                        max_length=16,
                    ),
                ),
                ("bundle_id", models.CharField(blank=True, default="", max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="device_tokens", to="tenants.tenant"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "device_tokens",
                "ordering": ["-last_seen_at"],
                "indexes": [models.Index(fields=["tenant"], name="device_token_tenant_idx")],
                "constraints": [models.UniqueConstraint(fields=("token",), name="uniq_device_token")],
            },
        ),
        # Enable RLS to match the public-schema lockdown invariant
        # (tenants/0059 + tenants/0066). Test
        # ``test_rls_enabled_on_owned_public_tables`` fails otherwise.
        # No policies here: the Django backend connects as the table owner and
        # bypasses RLS, while the anon role PostgREST exposes has no grant on this
        # table — structural lockdown. Mirrors apps/router/migrations/0010_conversationturn.py.
        migrations.RunSQL(
            sql="ALTER TABLE device_tokens ENABLE ROW LEVEL SECURITY;",
            # NOT disabling on reverse — would re-expose the table; CreateModel's
            # reverse drops the table anyway, so there's nothing meaningful to undo.
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
