# Generated by Django 5.1.15 on 2026-06-16 04:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0013_appchatmessage_phase_appchatmessage_phase_detail'),
        ('tenants', '0087_tenant_last_wake_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=200)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='production', help_text='Which APNs host the token is valid for (sandbox builds vs App Store / TestFlight).', max_length=16)),
                ('bundle_id', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'device_tokens',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['tenant'], name='device_token_tenant_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'token'), name='uniq_user_device_token')],
            },
        ),
    ]
