# Generated by Django 5.1.15 on 2026-06-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("router", "0015_appchatmessage_notified_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proactiveoutbound",
            name="notified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set when an APNs push was first claimed for this proactive / cron send so the iOS app pings the user (the counterpart to ``AppChatMessage.notified_at``). The atomic isnull→now claim makes the push idempotent. Distinct from ``consumed_at`` (inbound-envelope thread continuity), which is deliberately re-surfaced.",
                null=True,
            ),
        ),
    ]
