# Generated by Django 5.1.15 on 2026-06-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("router", "0016_proactiveoutbound_notified_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proactiveoutbound",
            name="channel",
            field=models.CharField(choices=[("telegram", "Telegram"), ("line", "Line"), ("app", "App")], max_length=16),
        ),
    ]
