# Generated by Django 5.1.15 on 2026-07-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("router", "0017_proactiveoutbound_app_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="appchatmessage",
            name="attachment_path",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Workspace-relative path of an inbound image stored on the tenant share (e.g. 'workspace/media/inbound/photo_ab12cd34.jpg'); empty for text-only turns. The agent reads it via the '[Photo attached: <container-path>]' marker baked into the queued message_text — the bytes never ride the queue payload.",
                max_length=255,
            ),
        ),
    ]
