# Generated by Django 5.1.15 on 2026-07-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("router", "0018_appchatmessage_attachment_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="appchatmessage",
            name="partial_seq",
            field=models.IntegerField(
                default=0,
                help_text="Monotonic sequence of the latest partial_text write; a stale/duplicate post (seq <= this) is ignored so out-of-order events can't rewind the stream.",
            ),
        ),
        migrations.AddField(
            model_name="appchatmessage",
            name="partial_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Cumulative assistant text-so-far for the in-flight turn (streamed per model-call step). Cleared when the final reply is written.",
            ),
        ),
    ]
