# Generated by Django 5.1.15 on 2026-07-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("router", "0019_appchatmessage_partial_seq_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appchatmessage",
            name="reply_redactions",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="appchatmessage",
            name="user_redactions",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
