# Generated by Django 5.1.15 on 2026-07-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("router", "0020_appchatmessage_reply_redactions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversationturn",
            name="reply_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The assistant's reply, marker-stripped and kept in PII-placeholder space ([PERSON_1]) at rest; rehydrated at the owner-facing ?since= feed. May be empty on a failed turn.",
            ),
        ),
        migrations.AlterField(
            model_name="lineoutboundmessage",
            name="text_excerpt",
            field=models.TextField(
                blank=True,
                default="",
                help_text="First ~500 chars of the message we sent, in PII-placeholder space ([PERSON_1]) — pseudonymize-at-rest. Its only reader (_extract_line_reply_context) inlines it into the INBOUND agent turn, which is model-facing, so placeholder space is correct and needs no rehydration.",
            ),
        ),
        migrations.AlterField(
            model_name="proactiveoutbound",
            name="message_text",
            field=models.TextField(
                help_text="Full proactive message body in PII-placeholder space ([PERSON_1]), as the agent authored it. Stored placeholder-space at rest (pseudonymize-at-rest); rehydrated only at owner-facing egress (the iOS APNs push and the ?since= feed builder)."
            ),
        ),
    ]
