# Generated by Django 5.1.15 on 2026-07-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("router", "0021_alter_conversationturn_reply_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bufferedmessage",
            name="payload",
            field=models.JSONField(
                help_text="Minimal schema-versioned envelope with the routing/media metadata the drain needs (apps.router.buffer_envelope). Legacy rows hold a raw webhook (no 'schema' marker) — the drain handles both."
            ),
        ),
        migrations.AlterField(
            model_name="bufferedmessage",
            name="user_text",
            field=models.TextField(
                blank=True, default="", help_text="Extracted user message text, redacted at write time."
            ),
        ),
    ]
