# Generated by Django 5.1.15 on 2026-07-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("router", "0022_buffered_message_minimal_envelope_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="appchatmessage",
            name="quick_replies",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
