# Generated by Django 5.1.15 on 2026-07-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("router", "0023_appchatmessage_quick_replies"),
    ]

    operations = [
        migrations.AddField(
            model_name="appchatmessage",
            name="user_text_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="chatthread",
            name="title_enc",
            field=models.BinaryField(null=True),
        ),
    ]
