# Generated by Django 5.1.15 on 2026-07-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("router", "0024_add_chat_enc_columns"),
    ]

    operations = [
        migrations.AddField(
            model_name="appchatmessage",
            name="journal_link",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="proactiveoutbound",
            name="journal_link",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="A tappable 'View in Journal' deep-link parsed from a trailing ``[[journal-link: kind|slug|title]]`` marker on a proactive / cron send (see ``apps.router.journal_link.extract_journal_link``). Stored as ``{kind, slug, title}`` in PII-placeholder space (``title`` rehydrated only at the owner-facing ``?since=`` feed). Populated only for app-channel sends; null on Telegram/LINE (marker stripped, no transport) and when the send carried no marker. This is the path MJ's morning report uses.",
                null=True,
            ),
        ),
    ]
