# Generated by Django 5.1.15 on 2026-07-16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("router", "0025_appchatmessage_journal_link_proactiveoutbound_journal_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicetoken",
            name="installation_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="devicetoken",
            name="revoked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
