# Generated by Django 5.1.15 on 2026-07-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("router", "0025_appchatmessage_journal_link_proactiveoutbound_journal_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proactiveoutbound",
            name="channel",
            field=models.CharField(
                choices=[("telegram", "Telegram"), ("line", "Line"), ("app", "App"), ("eval", "Eval")], max_length=16
            ),
        ),
    ]
