# Generated by Django 6.0.7 on 2026-07-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("router", "0027_alter_proactiveoutbound_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="proactiveoutbound",
            name="quick_replies",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
