# Generated by Django 6.0.7 on 2026-07-31 02:27

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("router", "0028_proactiveoutbound_quick_replies"),
        ("tenants", "0140_relock_after_apple_auth"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryAttempt",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("occurrence_key", models.CharField(db_index=True, max_length=64)),
                ("job_name", models.CharField(blank=True, default="", max_length=128)),
                ("channel", models.CharField(max_length=16)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("claimed", "Transport not yet attempted"),
                            ("sent", "Transport confirmed acceptance"),
                            ("failed", "Definitive failure; safe to retry"),
                            ("ambiguous", "Transport outcome unknown; do not retry"),
                        ],
                        default="claimed",
                        max_length=12,
                    ),
                ),
                ("claimed_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("response_excerpt", models.CharField(blank=True, default="", max_length=500)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_attempts",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "occurrence_key"), name="delivery_attempt_unique_tenant_occurrence"
                    )
                ],
            },
        ),
    ]
