# Generated by Django 6.0.7 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("router", "0030_deliveryattempt_pii_receipts"),
    ]

    operations = [
        migrations.AddField(
            model_name="appchatmessage",
            name="retried_at",
            field=models.DateTimeField(
                blank=True,
                help_text=(
                    "Set when a silently dropped tenant-runtime turn spends its one bounded replay. "
                    "The same row returns to pending if that replay runs."
                ),
                null=True,
            ),
        ),
    ]
