# Generated by Django 6.0.8 on 2026-08-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("router", "0031_appchatmessage_retried_at"),
        ("tenants", "0145_tenant_layer1_placeholder_writes"),
    ]

    operations = [
        migrations.CreateModel(
            name="RuntimeWriteActivity",
            fields=[
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="runtime_write_activity",
                        serialize=False,
                        to="tenants.tenant",
                    ),
                ),
                ("last_runtime_write_at", models.DateTimeField()),
            ],
            options={"db_table": "runtime_write_activity"},
        ),
        migrations.AddField(
            model_name="appchatmessage",
            name="retry_health_deferred_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set when the dropped-turn replay spends its one 120-second health deferral.",
                null=True,
            ),
        ),
    ]
