# Generated by Django 6.0.7 on 2026-08-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("router", "0032_runtimewriteactivity_and_retry_health_deferral"),
    ]

    operations = [
        migrations.AddField(
            model_name="proactiveoutbound",
            name="thread_id",
            field=models.UUIDField(
                blank=True,
                help_text="Tenant-owned app thread that should receive this proactive row. Null preserves legacy delivery to the tenant's main thread.",
                null=True,
            ),
        ),
    ]
