# Generated by Django 6.0.7 on 2026-08-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("router", "0033_proactive_outbound_thread"),
    ]

    operations = [
        migrations.AddField(
            model_name="appchatmessage",
            name="redaction_confirmed",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="appchatmessage",
            name="redaction_reason",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
