# Generated by Django 6.0.7 on 2026-09-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("router", "0034_appchatmessage_redaction_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="appchatmessage",
            name="panels",
            field=models.JSONField(
                blank=True, help_text="Live panel references attached to the assistant message.", null=True
            ),
        ),
        migrations.AddField(
            model_name="proactiveoutbound",
            name="panels",
            field=models.JSONField(
                blank=True, help_text="Live panel references attached to the assistant message.", null=True
            ),
        ),
    ]
