# Generated by Django 6.0.7 on 2026-07-26 02:08

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=17, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("revoked", "Revoked")], default="active", max_length=16
                    ),
                ),
                ("purchaser_email", models.EmailField(db_index=True, max_length=254)),
                ("stripe_session_id", models.CharField(max_length=255, unique=True)),
                ("stripe_customer_id", models.CharField(blank=True, default="", max_length=255)),
                ("stripe_payment_intent_id", models.CharField(blank=True, default="", max_length=255)),
                ("key_email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LicenseActivation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("device_id", models.CharField(max_length=64)),
                ("activated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="activations", to="yardtalk.license"
                    ),
                ),
            ],
            options={
                "ordering": ["activated_at"],
                "constraints": [
                    models.UniqueConstraint(fields=("license", "device_id"), name="yardtalk_unique_license_device")
                ],
            },
        ),
    ]
