# Generated by Django 6.0.7 on 2026-07-26 02:09

from django.db import migrations


def migrate_legacy_licenses(apps, schema_editor):
    LegacyLicense = apps.get_model("billing", "YardTalkLicense")
    License = apps.get_model("yardtalk", "License")
    LicenseActivation = apps.get_model("yardtalk", "LicenseActivation")

    for legacy in LegacyLicense.objects.all().iterator():
        license_obj, _ = License.objects.update_or_create(
            id=legacy.id,
            defaults={
                "key": legacy.key,
                "status": "revoked" if legacy.revoked_at else "active",
                "purchaser_email": legacy.email,
                "stripe_session_id": legacy.stripe_session_id,
                "stripe_customer_id": "",
                "stripe_payment_intent_id": legacy.stripe_payment_intent_id,
                "key_email_sent_at": legacy.key_email_sent_at,
                "created_at": legacy.created_at,
            },
        )
        License.objects.filter(id=license_obj.id).update(created_at=legacy.created_at)
        activations = [
            LicenseActivation(
                license=license_obj,
                device_id=device_id,
                activated_at=legacy.created_at,
            )
            for device_id in dict.fromkeys(legacy.device_ids or [])
            if isinstance(device_id, str) and 0 < len(device_id) <= 64
        ]
        LicenseActivation.objects.bulk_create(
            activations,
            ignore_conflicts=True,
        )
        LicenseActivation.objects.filter(license=license_obj).update(
            activated_at=legacy.created_at,
        )


def restore_legacy_licenses(apps, schema_editor):
    LegacyLicense = apps.get_model("billing", "YardTalkLicense")
    License = apps.get_model("yardtalk", "License")

    for license_obj in License.objects.all().iterator():
        legacy, _ = LegacyLicense.objects.update_or_create(
            id=license_obj.id,
            defaults={
                "key": license_obj.key,
                "email": license_obj.purchaser_email,
                "stripe_session_id": license_obj.stripe_session_id,
                "stripe_payment_intent_id": license_obj.stripe_payment_intent_id,
                "device_ids": list(
                    license_obj.activations.order_by("activated_at").values_list(
                        "device_id",
                        flat=True,
                    )
                ),
                "revoked_at": (license_obj.created_at if license_obj.status == "revoked" else None),
                "key_email_sent_at": license_obj.key_email_sent_at,
                "created_at": license_obj.created_at,
                "updated_at": license_obj.created_at,
            },
        )
        LegacyLicense.objects.filter(id=legacy.id).update(
            created_at=license_obj.created_at,
            updated_at=license_obj.created_at,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0010_yardtalklicense"),
        ("yardtalk", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_licenses, restore_legacy_licenses),
    ]
