# Generated by Django 6.0.7 on 2026-07-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yardtalk", "0002_migrate_legacy_licenses"),
    ]

    operations = [
        migrations.AddField(
            model_name="license",
            name="revocation_reason",
            field=models.CharField(
                blank=True,
                choices=[("refund", "Refund"), ("dispute", "Dispute"), ("manual", "Manual")],
                default="",
                max_length=16,
            ),
        ),
    ]
