# Generated by Django 5.1.15 on 2026-02-08 02:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('stripe_price_id', models.CharField(blank=True, default='', max_length=255)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('sponsor', 'Sponsor')], default='free', max_length=20)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('token_budget', models.IntegerField(default=100000, help_text='Daily token budget')),
                ('features', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'plans',
            },
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('tokens', models.IntegerField(default=0)),
                ('model_used', models.CharField(blank=True, default='', max_length=255)),
                ('cost_estimate', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usage_events',
            },
        ),
    ]
