# Generated by Django 5.1.15 on 2026-02-08 06:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_reconcile_refactor"),
        ("billing", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyBudget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "month",
                    models.DateField(
                        help_text="First day of the month", unique=True
                    ),
                ),
                (
                    "budget_dollars",
                    models.DecimalField(decimal_places=2, default=100, max_digits=10),
                ),
                (
                    "spent_dollars",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "is_capped",
                    models.BooleanField(
                        default=False,
                        help_text="If True, all non-essential API calls are blocked",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "monthly_budgets",
            },
        ),
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(max_length=50)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("model_used", models.CharField(blank=True, default="", max_length=255)),
                (
                    "cost_estimate",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "usage_records",
            },
        ),
        migrations.AddIndex(
            model_name="usagerecord",
            index=models.Index(
                fields=["tenant", "created_at"], name="usage_recor_tenant__5ae9d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usagerecord",
            index=models.Index(
                fields=["event_type", "created_at"],
                name="usage_recor_event_t_9e72b7_idx",
            ),
        ),
        migrations.DeleteModel(
            name="Plan",
        ),
        migrations.DeleteModel(
            name="UsageEvent",
        ),
    ]
