# Generated by Django 5.1.15 on 2026-03-13 06:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_donation_ledger'),
        ('tenants', '0025_alter_tenant_onboarding_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfraCostSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField(help_text='First day of the month')),
                ('container_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('storage_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('database_share', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('source', models.CharField(default='estimate', help_text="'azure' for real billing data, 'estimate' for fallback", max_length=20)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infra_costs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'infra_cost_snapshots',
                'indexes': [models.Index(fields=['month'], name='infra_cost__month_e504c1_idx')],
                'unique_together': {('tenant', 'month')},
            },
        ),
    ]
