# Generated by Django 5.1.15 on 2026-05-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0005_infra_cost_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="usagerecord",
            name="is_system_event",
            field=models.BooleanField(default=False),
        ),
    ]
