# Generated by Django 5.1.15 on 2026-06-08 06:04

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0007_modelhealth_freemodeloffer"),
        ("tenants", "0084_tenant_purchased_credit"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditLedger",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("grant", "Grant"),
                            ("debit", "Debit"),
                            ("reversal", "Reversal"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=4, max_digits=10)),
                ("stripe_event_id", models.CharField(blank=True, default="", max_length=255)),
                ("stripe_session_id", models.CharField(blank=True, default="", max_length=255)),
                ("stripe_payment_intent_id", models.CharField(blank=True, default="", max_length=255)),
                ("pack_id", models.CharField(blank=True, default="", max_length=64)),
                ("amount_paid_cents", models.IntegerField(blank=True, null=True)),
                ("description", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="credit_ledger", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "credit_ledger",
                "indexes": [
                    models.Index(fields=["tenant", "created_at"], name="credit_ledg_tenant__5bded4_idx"),
                    models.Index(fields=["stripe_payment_intent_id"], name="credit_ledg_stripe__eab591_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "grant"), models.Q(("stripe_event_id", ""), _negated=True)),
                        fields=("stripe_event_id",),
                        name="uniq_credit_grant_per_event",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "reversal"), models.Q(("stripe_event_id", ""), _negated=True)),
                        fields=("stripe_event_id",),
                        name="uniq_credit_reversal_per_event",
                    ),
                ],
            },
        ),
    ]
