# Generated by Django 6.0.7 on 2026-07-20 15:03

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0009_infra_snapshot_platform_share"),
    ]

    operations = [
        migrations.CreateModel(
            name="YardTalkLicense",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=19, unique=True)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("stripe_session_id", models.CharField(max_length=255, unique=True)),
                ("stripe_payment_intent_id", models.CharField(blank=True, default="", max_length=255)),
                ("device_ids", models.JSONField(blank=True, default=list)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("key_email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "yardtalk_licenses",
                "ordering": ["-created_at"],
            },
        ),
    ]
