# Generated by Django 6.0.7 on 2026-07-26 02:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0010_yardtalklicense"),
        ("yardtalk", "0002_migrate_legacy_licenses"),
    ]

    operations = [
        migrations.DeleteModel(
            name="YardTalkLicense",
        ),
    ]
