# Generated by Django 5.1.15 on 2026-02-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_reconcile_refactor"),
        ("integrations", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="integration",
            old_name="created_at",
            new_name="connected_at",
        ),
        migrations.AddField(
            model_name="integration",
            name="key_vault_secret_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Key Vault secret name where tokens are stored",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="integration",
            name="provider",
            field=models.CharField(
                choices=[
                    ("gmail", "Gmail"),
                    ("google-calendar", "Google Calendar"),
                    ("sautai", "Sautai"),
                ],
                max_length=50,
            ),
        ),
        migrations.RemoveField(
            model_name="integration",
            name="access_token_ref",
        ),
        migrations.RemoveField(
            model_name="integration",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="integration",
            name="provider_user_id",
        ),
        migrations.RemoveField(
            model_name="integration",
            name="refresh_token_ref",
        ),
        migrations.RemoveField(
            model_name="integration",
            name="user",
        ),
        migrations.DeleteModel(
            name="UserSecret",
        ),
    ]
