# Generated by Django 5.1.15 on 2026-07-12 07:20

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0006_unify_google_provider"),
        ("tenants", "0121_tenant_sautai_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="SautaiMealPlanJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("ready", "Ready"), ("failed", "Failed")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "week_start",
                    models.DateField(
                        blank=True,
                        help_text=(
                            "Requested week (Monday), resolved server-side in the tenant's timezone by "
                            "RuntimeSautaiGeneratePlanView — always populated for new jobs; nullable only "
                            "for historical rows."
                        ),
                        null=True,
                    ),
                ),
                ("number_of_days", models.PositiveSmallIntegerField(default=7)),
                ("user_prompt", models.TextField(blank=True, default="")),
                ("result", models.JSONField(blank=True, default=dict, help_text="sautai's plan payload, once READY")),
                ("web_link", models.CharField(blank=True, default="", max_length=500)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sautai_meal_plan_jobs",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "sautai_meal_plan_jobs",
                "indexes": [models.Index(fields=["tenant", "status"], name="sautai_meal_tenant__92d16f_idx")],
            },
        ),
    ]
