# Generated by Django 5.1.15 on 2026-07-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0007_sautaimealplanjob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sautaimealplanjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("generating", "Generating"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
