# Generated by Django 5.1.15 on 2026-07-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0008_alter_sautaimealplanjob_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="integration",
            name="linked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="integration",
            name="sautai_user_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sautaimealplanjob",
            name="funnel",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="sautaimealplanjob",
            name="regenerate",
            field=models.BooleanField(default=False),
        ),
    ]
