# Generated by Django 6.0.7 on 2026-07-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0009_sautai_phase05_link_and_funnel"),
    ]

    operations = [
        migrations.AddField(
            model_name="sautaimealplanjob",
            name="addressed_by",
            field=models.CharField(
                blank=True,
                choices=[("linked_id", "Linked sautai user id"), ("email", "Tenant email")],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sautaimealplanjob",
            name="sautai_user_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
