"""Postgres canonical store for OpenClaw cron jobs.

Started life as a passive read cache (Phase 1) populated from successful
``cron.list`` calls and hibernation snapshots. Phase 2 promotes this table
to the canonical source of truth for tenant cron schedules — OpenClaw's
SQLite registry becomes a derived view, regenerated by
``apps/orchestrator/cron_reconcile.py`` on every CronJob write, on container
start, and via an hourly fleet reconcile.

Cutover is per-tenant via ``Tenant.postgres_cron_canonical``. While that
flag is False (legacy default), the gateway is still the source of truth
and this table is just a read cache as before.
"""

from __future__ import annotations

from django.db import models


class CronJobSource(models.TextChoices):
    """Origin of a CronJob row — drives reconciler classification + UI filters."""

    SYSTEM = "system", "System (Morning Briefing, Heartbeat, etc.)"
    USER = "user", "User-created via dashboard"
    FUEL_SESSION = "fuel_session", "Per-Workout Fuel session cron (_fuel:{8-hex})"
    AGENT = "agent", "Agent-created in-session (_sync:* etc.)"


class CronJob(models.Model):
    tenant = models.ForeignKey(
        "tenants.Tenant",
        on_delete=models.CASCADE,
        related_name="cron_jobs",
    )
    name = models.CharField(max_length=255)
    gateway_job_id = models.CharField(max_length=64, blank=True, default="")
    data = models.JSONField(
        default=dict,
        help_text="The full job dict (schedule, payload, delivery, sessionTarget) — same shape as the OpenClaw gateway response.",
    )
    source = models.CharField(
        max_length=16,
        choices=CronJobSource.choices,
        default=CronJobSource.USER,
        help_text="Origin classifier — drives reconciler treatment + UI visibility.",
    )
    managed = models.BooleanField(
        default=True,
        help_text=(
            "If False, the reconciler leaves the gateway-side cron alone. "
            "Used for agent-created _sync:* crons that live in SQLite-only."
        ),
    )
    enabled = models.BooleanField(
        default=True,
        help_text="Lifted out of `data` for query clarity; toggles update this column.",
    )
    last_synced_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When this row was last refreshed from a gateway cron.list response.",
    )
    last_pushed_to_container_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When the reconciler last successfully pushed this row to the container's SQLite.",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["tenant", "name"],
                name="cron_unique_tenant_name",
            ),
        ]
        indexes = [
            models.Index(fields=["tenant", "last_synced_at"]),
            models.Index(fields=["tenant", "source", "managed"]),
        ]

    def __str__(self) -> str:
        return f"{self.tenant_id}:{self.name}"
