# Generated by Django 6.0.7 on 2026-08-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="financeaccount",
            name="pii_receipts",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="financesnapshot",
            name="pii_receipts",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="financetransaction",
            name="pii_receipts",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="payoffplan",
            name="pii_receipts",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
