# Generated by Django 6.0.7 on 2026-08-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_financeaccount_pii_receipts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financetransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("payment", "Payment"),
                    ("charge", "Charge"),
                    ("transfer", "Transfer"),
                    ("refund", "Refund"),
                    ("interest", "Interest Charge"),
                    ("deposit", "Deposit"),
                    ("withdrawal", "Withdrawal"),
                ],
                max_length=16,
            ),
        ),
    ]
