# Generated by Django 5.1.15 on 2026-02-12 01:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0005_remove_celery_beat_schedules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('daily_brief', 'Daily Brief'), ('weekly_review', 'Weekly Review')], max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused')], default='active', max_length=16)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('schedule_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], max_length=16)),
                ('schedule_time', models.TimeField()),
                ('schedule_days', models.JSONField(blank=True, default=list)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='tenants.tenant')),
            ],
            options={
                'db_table': 'automations',
            },
        ),
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('trigger_source', models.CharField(choices=[('manual', 'Manual'), ('schedule', 'Schedule')], default='schedule', max_length=16)),
                ('scheduled_for', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='automations.automation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_runs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'automation_runs',
            },
        ),
        migrations.AddIndex(
            model_name='automation',
            index=models.Index(fields=['tenant', 'status', 'next_run_at'], name='automations_tenant__49ebfd_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrun',
            index=models.Index(fields=['tenant', 'created_at'], name='automation__tenant__7c19ed_idx'),
        ),
    ]
