# Generated by Django 6.0.7 on 2026-08-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationrun",
            name="pii_receipts",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
