import { LegalPage } from "@/components/legal-page";

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" lastUpdated="February 13, 2026">
      <h2>1. Service Description</h2>
      <p>
        NBHD United (&ldquo;we,&rdquo; &ldquo;us,&rdquo; &ldquo;our&rdquo;) provides a private AI-powered assistant
        delivered via Telegram. Our service includes a dedicated AI agent that
        responds to your messages in a private Telegram chat. The service is
        offered on a subscription basis. Current pricing is available on our website and during checkout.
      </p>

      <h2>2. Account Eligibility & Registration</h2>
      <p>
        You must be at least 18 years old to create an account. By registering,
        you agree to provide accurate and complete information, including a valid
        email address. You are responsible for maintaining the security of your
        account credentials.
      </p>

      <h2>3. Subscription & Billing</h2>
      <p>
        Access to the NBHD United assistant requires an active paid
        subscription. Subscriptions are billed monthly on a recurring basis
        through Stripe, our third-party payment processor. By subscribing, you
        authorize us to charge your payment method on a recurring basis until you
        cancel.
      </p>
      <ul>
        <li>Billing begins immediately upon subscribing.</li>
        <li>
          Subscriptions automatically renew each month unless cancelled before
          the renewal date.
        </li>
        <li>
          You may cancel at any time through the Stripe customer portal
          accessible from your Billing page.
        </li>
        <li>
          Cancellation takes effect at the end of the current billing period. You
          retain access until that date.
        </li>
      </ul>

      <h2>4. Acceptable Use</h2>
      <p>You agree not to use the service to:</p>
      <ul>
        <li>Violate any applicable laws or regulations.</li>
        <li>
          Generate, store, or transmit content that is illegal, harmful,
          threatening, abusive, or otherwise objectionable.
        </li>
        <li>
          Attempt to reverse-engineer, decompile, or extract the underlying
          models or systems.
        </li>
        <li>
          Use the service in a manner that could damage, disable, or impair our
          infrastructure.
        </li>
        <li>
          Share your account credentials or allow others to access the service
          through your account.
        </li>
      </ul>

      <h2>5. Intellectual Property</h2>
      <p>
        All rights, title, and interest in the NBHD United platform, branding,
        and underlying technology remain with us. Responses generated by the AI
        assistant are provided for your personal use. We do not claim ownership
        of the content you submit through the service.
      </p>

      <h2>6. Third-Party Services</h2>
      <p>
        NBHD United integrates with the following third-party services, each
        governed by their own terms:
      </p>
      <ul>
        <li>
          <strong>Telegram</strong> — used as the messaging interface for your
          AI assistant.
        </li>
        <li>
          <strong>Stripe</strong> — used for payment processing and subscription
          management.
        </li>
        <li>
          <strong>Anthropic</strong> — provides the AI language model that powers
          your assistant.
        </li>
      </ul>
      <p>
        We are not responsible for the availability, terms, or practices of these
        third-party services.
      </p>

      <h2>7. Limitation of Liability</h2>
      <p>
        To the maximum extent permitted by law, NBHD United and its operators
        shall not be liable for any indirect, incidental, special,
        consequential, or punitive damages, including loss of profits, data, or
        goodwill, arising from your use of the service.
      </p>
      <p>
        Our total liability for any claim arising from the service shall not
        exceed the amount you paid us in the 12 months preceding the claim.
      </p>

      <h2>8. Disclaimers</h2>
      <p>
        The service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties of
        any kind, either express or implied. We do not guarantee that AI
        responses will be accurate, complete, or suitable for any particular
        purpose. You should not rely on AI-generated content as professional,
        legal, medical, or financial advice.
      </p>

      <h2>9. Termination & Suspension</h2>
      <p>
        We may suspend or terminate your account at our discretion if you
        violate these terms, engage in abusive behavior, or if continued service
        is not feasible. You may terminate your account at any time by cancelling
        your subscription and contacting us at the email address below.
      </p>

      <h2>10. Changes to Terms</h2>
      <p>
        We may update these terms from time to time. If we make material
        changes, we will notify you via email or through the service. Continued
        use of the service after changes take effect constitutes acceptance of
        the revised terms.
      </p>

      <h2>11. Contact</h2>
      <p>
        If you have questions about these terms, please contact us at{" "}
        <a href="mailto:mj@bywayofmj.com">mj@bywayofmj.com</a>.
      </p>
    </LegalPage>
  );
}
