# Generated by Django 5.1.15 on 2026-04-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cron", "0001_initial"),
        ("tenants", "0047_tenant_postgres_cron_canonical"),
    ]

    operations = [
        migrations.AddField(
            model_name="cronjob",
            name="enabled",
            field=models.BooleanField(
                default=True, help_text="Lifted out of `data` for query clarity; toggles update this column."
            ),
        ),
        migrations.AddField(
            model_name="cronjob",
            name="last_pushed_to_container_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the reconciler last successfully pushed this row to the container's SQLite.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cronjob",
            name="managed",
            field=models.BooleanField(
                default=True,
                help_text="If False, the reconciler leaves the gateway-side cron alone. Used for agent-created _sync:* crons that live in SQLite-only.",
            ),
        ),
        migrations.AddField(
            model_name="cronjob",
            name="source",
            field=models.CharField(
                choices=[
                    ("system", "System (Morning Briefing, Heartbeat, etc.)"),
                    ("user", "User-created via dashboard"),
                    ("fuel_session", "Per-Workout Fuel session cron (_fuel:{8-hex})"),
                    ("agent", "Agent-created in-session (_sync:* etc.)"),
                ],
                default="user",
                help_text="Origin classifier — drives reconciler treatment + UI visibility.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="cronjob",
            name="data",
            field=models.JSONField(
                default=dict,
                help_text="The full job dict (schedule, payload, delivery, sessionTarget) — same shape as the OpenClaw gateway response.",
            ),
        ),
        migrations.AlterField(
            model_name="cronjob",
            name="last_synced_at",
            field=models.DateTimeField(
                blank=True, help_text="When this row was last refreshed from a gateway cron.list response.", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="cronjob",
            index=models.Index(fields=["tenant", "source", "managed"], name="cron_cronjo_tenant__803359_idx"),
        ),
    ]
