# Generated by Django 5.1.15 on 2026-05-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cron", "0002_cronjob_enabled_cronjob_last_pushed_to_container_at_and_more"),
        ("tenants", "0072_typed_cron_patterns"),
    ]

    operations = [
        migrations.AddField(
            model_name="cronjob",
            name="creation_path",
            field=models.CharField(
                choices=[
                    ("legacy", "Legacy (pre-typed)"),
                    ("typed", "Typed pattern"),
                    ("freeform", "Freeform (UI-only, user-confirmed)"),
                    ("internal", "Internal sync (agent-managed)"),
                ],
                default="legacy",
                help_text="Discriminator: who created this row and through which path. Determines whether `data` is derived or source-of-truth.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="cronjob",
            name="pattern",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pure_reminder", "Pure reminder"),
                    ("quote_user_intent", "Quote user intent"),
                    ("domain_summary", "Domain summary"),
                    ("daily_briefing", "Daily briefing (system)"),
                ],
                help_text="Typed pattern for this cron. NULL when creation_path is legacy/freeform/internal. NOT NULL when creation_path='typed'.",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cronjob",
            name="typed_payload",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Schema-validated payload for the typed pattern (see apps/cron/patterns/<pattern>.py). Empty dict for legacy/freeform.",
            ),
        ),
        migrations.AddField(
            model_name="cronjob",
            name="user_confirmed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Required when creation_path='freeform' — timestamp of the explicit user confirmation that this cron's content will not be validated. NULL for all other creation_paths.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cronjob",
            name="data",
            field=models.JSONField(
                default=dict,
                help_text="Full job dict (schedule, payload, delivery, sessionTarget) — same shape as the OpenClaw gateway response. For creation_path='typed' this is DERIVED from pattern + typed_payload by the pre_save signal and should not be edited directly. For legacy/freeform rows this is the source of truth.",
            ),
        ),
        migrations.AlterField(
            model_name="cronjob",
            name="managed",
            field=models.BooleanField(
                default=True,
                help_text="If False, the reconciler leaves the gateway-side cron alone. Used for agent-created _sync:* crons that live in SQLite-only, and for typed one-off (kind:'at') crons that OC auto-deletes.",
            ),
        ),
        migrations.AddIndex(
            model_name="cronjob",
            index=models.Index(fields=["tenant", "pattern"], name="cron_cronjo_tenant__8600d8_idx"),
        ),
        migrations.AddConstraint(
            model_name="cronjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("creation_path", "freeform"), _negated=True),
                    ("user_confirmed_at__isnull", False),
                    _connector="OR",
                ),
                name="cron_freeform_requires_user_confirmation",
            ),
        ),
        migrations.AddConstraint(
            model_name="cronjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("creation_path", "typed"), _negated=True), ("pattern__isnull", False), _connector="OR"
                ),
                name="cron_typed_requires_pattern",
            ),
        ),
    ]
