# Generated by Django 5.1.15 on 2026-07-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cron", "0004_alter_cronjob_pattern"),
        ("tenants", "0125_alter_tenant_experimental_typed_crons"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cronjob",
            name="cron_unique_tenant_name",
        ),
        migrations.AddConstraint(
            model_name="cronjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("enabled", True)), fields=("tenant", "name"), name="cron_unique_tenant_name"
            ),
        ),
    ]
