# Generated by Django 6.0.7 on 2026-08-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cron", "0005_remove_cronjob_cron_unique_tenant_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cronjob",
            name="pattern",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pure_reminder", "Pure reminder"),
                    ("quote_user_intent", "Quote user intent"),
                    ("domain_summary", "Domain summary"),
                    ("daily_briefing", "Daily briefing (system)"),
                    ("workout_congrats", "Workout congrats (system)"),
                    ("task_hygiene", "Task hygiene (system)"),
                ],
                help_text="Typed pattern for this cron. NULL when creation_path is legacy/freeform/internal. NOT NULL when creation_path='typed'.",
                max_length=32,
                null=True,
            ),
        ),
    ]
