# Generated by Django 5.1.15 on 2026-03-06 07:44

import django.db.models.deletion
from django.db import migrations, models

import apps.actions.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0021_tenant_gate_acknowledged_risk_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionAuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("gmail_trash", "Gmail: Trash Message"),
                            ("gmail_delete", "Gmail: Delete Message"),
                            ("gmail_send", "Gmail: Send Email"),
                            ("calendar_delete", "Calendar: Delete Event"),
                            ("drive_delete", "Drive: Delete File"),
                            ("task_delete", "Tasks: Delete Task"),
                        ],
                        max_length=32,
                    ),
                ),
                ("action_payload", models.JSONField()),
                ("display_summary", models.CharField(max_length=500)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("expired", "Expired"),
                        ],
                        help_text="Final outcome: approved, denied, or expired.",
                        max_length=16,
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_audit_logs",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GatePreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("gmail_trash", "Gmail: Trash Message"),
                            ("gmail_delete", "Gmail: Delete Message"),
                            ("gmail_send", "Gmail: Send Email"),
                            ("calendar_delete", "Calendar: Delete Event"),
                            ("drive_delete", "Drive: Delete File"),
                            ("task_delete", "Tasks: Delete Task"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "require_confirmation",
                    models.BooleanField(
                        default=True, help_text="If False, this action type is auto-approved for this tenant."
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gate_preferences",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "unique_together": {("tenant", "action_type")},
            },
        ),
        migrations.CreateModel(
            name="PendingAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("gmail_trash", "Gmail: Trash Message"),
                            ("gmail_delete", "Gmail: Delete Message"),
                            ("gmail_send", "Gmail: Send Email"),
                            ("calendar_delete", "Calendar: Delete Event"),
                            ("drive_delete", "Drive: Delete File"),
                            ("task_delete", "Tasks: Delete Task"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "action_payload",
                    models.JSONField(help_text="Structured data: {message_id, subject, ...} or {event_id, title, ...}"),
                ),
                (
                    "display_summary",
                    models.CharField(
                        help_text="Human-readable description shown in confirmation prompt.", max_length=500
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "platform_message_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Telegram message_id or LINE message_id for post-response edit.",
                        max_length=128,
                    ),
                ),
                (
                    "platform_channel",
                    models.CharField(blank=True, default="", help_text="telegram, line, etc.", max_length=32),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(default=apps.actions.models.default_expires_at)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="pending_actions", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["tenant", "status"], name="actions_pen_tenant__e1e10d_idx"),
                    models.Index(fields=["expires_at"], name="actions_pen_expires_91e08f_idx"),
                ],
            },
        ),
    ]
