# Generated by Django 6.0.7 on 2026-08-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0002_actionauditlog_pii_receipts_and_more"),
        ("tenants", "0153_relock_after_datebook_b1"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionauditlog",
            name="datebook_command_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="actionauditlog",
            name="detail_code",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="pendingaction",
            name="datebook_command_id",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="pendingaction",
            name="datebook_request_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="pendingaction",
            name="resolution_code",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="actionauditlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("gmail_trash", "Gmail: Trash Message"),
                    ("gmail_delete", "Gmail: Delete Message"),
                    ("gmail_send", "Gmail: Send Email"),
                    ("calendar_delete", "Calendar: Delete Event"),
                    ("drive_delete", "Drive: Delete File"),
                    ("task_delete", "Tasks: Delete Task"),
                    ("calendar_create", "Calendar: Create Event"),
                    ("reminder_create", "Reminders: Create Apple Reminder"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="actionauditlog",
            name="result",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("denied", "Denied"),
                    ("expired", "Expired"),
                    ("queued", "Queued"),
                    ("executed", "Executed"),
                    ("failed", "Failed"),
                    ("command_expired", "Command expired"),
                    ("cancelled", "Cancelled"),
                    ("ambiguous", "Ambiguous"),
                ],
                help_text="Immutable gate decision or downstream execution transition.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="gatepreference",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("gmail_trash", "Gmail: Trash Message"),
                    ("gmail_delete", "Gmail: Delete Message"),
                    ("gmail_send", "Gmail: Send Email"),
                    ("calendar_delete", "Calendar: Delete Event"),
                    ("drive_delete", "Drive: Delete File"),
                    ("task_delete", "Tasks: Delete Task"),
                    ("calendar_create", "Calendar: Create Event"),
                    ("reminder_create", "Reminders: Create Apple Reminder"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="pendingaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("gmail_trash", "Gmail: Trash Message"),
                    ("gmail_delete", "Gmail: Delete Message"),
                    ("gmail_send", "Gmail: Send Email"),
                    ("calendar_delete", "Calendar: Delete Event"),
                    ("drive_delete", "Drive: Delete File"),
                    ("task_delete", "Tasks: Delete Task"),
                    ("calendar_create", "Calendar: Create Event"),
                    ("reminder_create", "Reminders: Create Apple Reminder"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="pendingaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("datebook_request_id", ""), _negated=True),
                fields=("tenant", "datebook_request_id"),
                name="actions_datebook_request_unique",
            ),
        ),
    ]
