# Generated by Django 6.0.7 on 2026-08-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0003_actionauditlog_datebook_command_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionauditlog",
            name="approved_destination_fingerprint",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="actionauditlog",
            name="default_destination_new_fingerprint",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="actionauditlog",
            name="default_destination_old_fingerprint",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="actionauditlog",
            name="requested_destination_fingerprint",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="pendingaction",
            name="delivery_state",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Truthful confirmation delivery fact; only sent implies a real platform message id.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="pendingaction",
            name="originating_channel",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Immutable request provenance: app, telegram, line, or blank legacy origin.",
                max_length=16,
            ),
        ),
    ]
