# Generated by Django 6.0.7 on 2026-08-25 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0004_datebook_approval_ux"),
        ("cron", "0006_alter_cronjob_pattern"),
        ("tenants", "0158_relock_after_calendar_context"),
    ]

    operations = [
        migrations.CreateModel(
            name="CronDispatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(max_length=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="pendingaction",
            name="cron_request_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="pendingaction",
            name="origin_cron_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="pendingaction",
            name="origin_kind",
            field=models.CharField(choices=[("cron", "Cron"), ("unknown", "Unknown")], default="unknown", max_length=8),
        ),
        migrations.AddField(
            model_name="pendingaction",
            name="origin_run_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="pendingaction",
            name="suggestion_fingerprint",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="actionauditlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("gmail_trash", "Gmail: Trash Message"),
                    ("gmail_delete", "Gmail: Delete Message"),
                    ("gmail_send", "Gmail: Send Email"),
                    ("calendar_delete", "Calendar: Delete Event"),
                    ("drive_delete", "Drive: Delete File"),
                    ("task_delete", "Tasks: Delete Task"),
                    ("calendar_create", "Calendar: Create Event"),
                    ("reminder_create", "Reminders: Create Apple Reminder"),
                    ("cron_create", "Scheduled Tasks: Create Task"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="gatepreference",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("gmail_trash", "Gmail: Trash Message"),
                    ("gmail_delete", "Gmail: Delete Message"),
                    ("gmail_send", "Gmail: Send Email"),
                    ("calendar_delete", "Calendar: Delete Event"),
                    ("drive_delete", "Drive: Delete File"),
                    ("task_delete", "Tasks: Delete Task"),
                    ("calendar_create", "Calendar: Create Event"),
                    ("reminder_create", "Reminders: Create Apple Reminder"),
                    ("cron_create", "Scheduled Tasks: Create Task"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="pendingaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("gmail_trash", "Gmail: Trash Message"),
                    ("gmail_delete", "Gmail: Delete Message"),
                    ("gmail_send", "Gmail: Send Email"),
                    ("calendar_delete", "Calendar: Delete Event"),
                    ("drive_delete", "Drive: Delete File"),
                    ("task_delete", "Tasks: Delete Task"),
                    ("calendar_create", "Calendar: Create Event"),
                    ("reminder_create", "Reminders: Create Apple Reminder"),
                    ("cron_create", "Scheduled Tasks: Create Task"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="pendingaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cron_request_id", ""), _negated=True),
                fields=("tenant", "cron_request_id"),
                name="actions_cron_request_unique",
            ),
        ),
        migrations.AddField(
            model_name="crondispatch",
            name="action",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="cron_dispatch", to="actions.pendingaction"
            ),
        ),
        migrations.AddField(
            model_name="crondispatch",
            name="cron",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="approval_dispatch", to="cron.cronjob"
            ),
        ),
        migrations.RunSQL(
            sql="ALTER TABLE actions_crondispatch ENABLE ROW LEVEL SECURITY;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
