# Generated by Django 6.0.7 on 2026-08-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0005_cron_create_gate"),
    ]

    operations = [
        migrations.AddField(
            model_name="crondispatch",
            name="attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="crondispatch",
            name="last_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="crondispatch",
            name="state",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("dispatching", "Dispatching"),
                    ("executed", "Executed"),
                    ("failed", "Failed"),
                ],
                default="queued",
                max_length=16,
            ),
        ),
    ]
