# Generated by Django 5.1.15 on 2026-06-03 07:59

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0078_tenant_core_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoreProfile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "onboarding_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "preferred_voice",
                    models.CharField(
                        default="Achernar", help_text="Pinned TTS voice name (e.g. 'Achernar', 'Aoede').", max_length=64
                    ),
                ),
                (
                    "preferred_duration_minutes",
                    models.IntegerField(
                        default=10,
                        help_text="Target meditation length in minutes.",
                        validators=[
                            django.core.validators.MinValueValidator(3),
                            django.core.validators.MaxValueValidator(30),
                        ],
                    ),
                ),
                (
                    "ambient_bed_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Mix a soft ambient bed under the narration (deferred; voice-only for canary).",
                    ),
                ),
                (
                    "daily_cron_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Opt-in: auto-compose one meditation each morning (spends a render/day). Default is on-demand only.",
                    ),
                ),
                (
                    "preferred_time",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Preferred sit time for the optional daily cron: morning, afternoon, evening, or empty.",
                        max_length=16,
                    ),
                ),
                (
                    "additional_context",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Free-form context the user wants reflected in their meditations.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="core_profile", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "core_profiles",
            },
        ),
        migrations.CreateModel(
            name="MeditationSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("date", models.DateField(help_text="Day this meditation was composed for.")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("rendering", "Rendering"),
                            ("ready", "Ready"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=160)),
                (
                    "theme",
                    models.TextField(blank=True, default="", help_text="The personalized through-line for this sit."),
                ),
                ("voice", models.CharField(blank=True, default="", max_length=64)),
                (
                    "model",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="TTS model used, e.g. gemini-2.5-flash-preview-tts.",
                        max_length=64,
                    ),
                ),
                (
                    "manifest",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="The render manifest (phases → segments). Re-renderable; auditable.",
                    ),
                ),
                (
                    "guidance_text",
                    models.TextField(blank=True, default="", help_text="Flattened narration text, for display/audit."),
                ),
                (
                    "audio_url",
                    models.CharField(
                        blank=True, default="", help_text="Public URL of the rendered mp3.", max_length=512
                    ),
                ),
                (
                    "ogg_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Public URL of the ogg/opus (LINE/Telegram voice).",
                        max_length=512,
                    ),
                ),
                (
                    "duration_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Rendered audio length in milliseconds (LINE audio messages require it).",
                        null=True,
                    ),
                ),
                ("ambient_bed", models.CharField(blank=True, default="", max_length=64)),
                ("error", models.TextField(blank=True, default="", help_text="Last render error, when status=failed.")),
                (
                    "user_feedback",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional user signal, e.g. 'liked', 'skipped'.",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meditation_sessions",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "core_meditation_sessions",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(fields=["tenant", "date"], name="core_medita_tenant__46e0fc_idx"),
                    models.Index(fields=["tenant", "status"], name="core_medita_tenant__3803bd_idx"),
                ],
            },
        ),
    ]
