# Generated by Django 5.1.15 on 2026-07-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meditationsession",
            name="feedback_at",
            field=models.DateTimeField(
                blank=True, help_text="When the user last left feedback on this sit.", null=True
            ),
        ),
        migrations.AddField(
            model_name="meditationsession",
            name="feedback_note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional free-text the user leaves about this sit (what landed, what didn't).",
            ),
        ),
        migrations.AlterField(
            model_name="meditationsession",
            name="user_feedback",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional user signal, e.g. 'liked', 'disliked', 'skipped'.",
                max_length=16,
            ),
        ),
    ]
