# Generated by Django 6.0.7 on 2026-07-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_meditationsession_feedback_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coreprofile",
            name="additional_context_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="meditationsession",
            name="feedback_note_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="meditationsession",
            name="guidance_text_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="meditationsession",
            name="manifest_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="meditationsession",
            name="theme_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="meditationsession",
            name="title_enc",
            field=models.BinaryField(null=True),
        ),
    ]
