# Generated by Django 6.0.7 on 2026-07-28

from django.db import migrations, models


def classify_existing_failures(apps, schema_editor):
    """Give pre-deploy FAILED rows the same retry semantics as new failures."""
    MeditationSession = apps.get_model("core", "MeditationSession")
    failed = MeditationSession.objects.filter(status="failed", failure_class="")
    failed.filter(error__startswith="render_error:").update(failure_class="transient")
    failed.filter(error__startswith="persist_error:").update(failure_class="transient")
    failed.filter(failure_class="").update(failure_class="terminal")


def unclassify_existing_failures(apps, schema_editor):
    MeditationSession = apps.get_model("core", "MeditationSession")
    MeditationSession.objects.filter(status="failed").update(failure_class="")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_coreprofile_additional_context_enc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meditationsession",
            name="artifact_manifest_sha256",
            field=models.CharField(
                blank=True,
                help_text="Canonical manifest SHA-256 for the uploaded audio checkpoint.",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="meditationsession",
            name="attempt_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="meditationsession",
            name="failure_class",
            field=models.CharField(
                blank=True,
                choices=[("", "None"), ("transient", "Transient"), ("terminal", "Terminal")],
                default="",
                max_length=12,
            ),
        ),
        migrations.RunPython(
            classify_existing_failures,
            reverse_code=unclassify_existing_failures,
        ),
    ]
