# Generated by Django 6.0.7 on 2026-08-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_meditationsession_retry_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="coreprofile",
            name="pii_receipts",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="meditationsession",
            name="pii_receipts",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
