# Generated by Django 6.0.7 on 2026-09-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_coreprofile_pii_receipts_and_more"),
        ("tenants", "0161_tenant_site_editor"),
    ]

    operations = [
        migrations.AddField(
            model_name="meditationsession",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, help_text="When the person finished listening; stamped server-side once.", null=True
            ),
        ),
        migrations.AddField(
            model_name="meditationsession",
            name="lesson",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="meditationsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("rendering", "Rendering"),
                    ("ready", "Ready"),
                    ("delivered", "Delivered"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=12,
            ),
        ),
        migrations.AddIndex(
            model_name="meditationsession",
            index=models.Index(fields=["tenant", "completed_at"], name="core_medita_tenant__958dac_idx"),
        ),
    ]
