# Generated by Django 6.0.7 on 2026-09-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_completion_truth_lesson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meditationsession",
            name="lesson",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Validated meditation teaching and practice; empty for legacy sessions.",
            ),
        ),
    ]
