# Generated by Django 6.0.7 on 2026-07-30 02:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EvidenceEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("gateway_heartbeat", "Gateway heartbeat"),
                            ("ci_run", "CI run"),
                            ("asc_version_state", "App Store Connect version state"),
                            ("mj_ack", "MJ acknowledgement"),
                        ],
                        max_length=32,
                    ),
                ),
                ("subject", models.CharField(max_length=128)),
                ("occurred_at", models.DateTimeField()),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured evidence metadata only; maximum 4KB and no user PII.",
                    ),
                ),
                ("fingerprint", models.CharField(max_length=128, unique=True)),
                (
                    "trust",
                    models.CharField(
                        choices=[
                            ("authenticated_api", "Authenticated API"),
                            ("host_log", "Host log"),
                            ("untrusted_text", "Untrusted text"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "provenance",
                    models.CharField(
                        choices=[("mj", "MJ"), ("collector", "Collector"), ("agent_proposed", "Agent proposed")],
                        max_length=24,
                    ),
                ),
            ],
            options={
                "db_table": "steward_evidence_events",
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(fields=["source", "subject", "-occurred_at"], name="steward_evi_source_a941c0_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Expectation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[("heartbeat", "Heartbeat"), ("deadline", "Deadline"), ("recurrence", "Recurrence")],
                        max_length=16,
                    ),
                ),
                ("interval_s", models.PositiveIntegerField(blank=True, null=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("cron_expr", models.CharField(blank=True, max_length=128, null=True)),
                ("grace_s", models.PositiveIntegerField()),
                (
                    "evidence_source",
                    models.CharField(
                        choices=[
                            ("gateway_heartbeat", "Gateway heartbeat"),
                            ("ci_run", "CI run"),
                            ("asc_version_state", "App Store Connect version state"),
                            ("mj_ack", "MJ acknowledgement"),
                        ],
                        max_length=32,
                    ),
                ),
                ("subject", models.CharField(max_length=128)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("armed", "Armed"),
                            ("satisfied", "Satisfied"),
                            ("missed", "Missed"),
                            ("retired", "Retired"),
                        ],
                        default="armed",
                        max_length=16,
                    ),
                ),
                ("last_satisfied_at", models.DateTimeField(blank=True, null=True)),
                ("miss_count", models.PositiveIntegerField(default=0)),
                ("last_alerted_at", models.DateTimeField(blank=True, null=True)),
                ("on_miss", models.CharField(choices=[("urgent", "Urgent"), ("digest", "Digest")], max_length=16)),
                ("owner", models.CharField(default="mj", max_length=32)),
            ],
            options={
                "db_table": "steward_expectations",
                "indexes": [
                    models.Index(fields=["state", "kind"], name="steward_exp_state_eec4f0_idx"),
                    models.Index(fields=["evidence_source", "subject"], name="steward_exp_evidenc_7cd569_idx"),
                ],
            },
        ),
    ]
