# Generated by Django 6.0.7 on 2026-07-30 06:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("steward", "0002_relock_after_steward"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fingerprint", models.CharField(max_length=128, unique=True)),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
                ("sent_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "steward_alert_states",
            },
        ),
        migrations.CreateModel(
            name="DigestRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "delivery",
                    models.CharField(
                        choices=[
                            ("delivered", "Delivered"),
                            ("timeout", "Timeout"),
                            ("transient", "Transient"),
                            ("undeliverable", "Undeliverable"),
                        ],
                        max_length=16,
                    ),
                ),
                ("body", models.TextField()),
                ("stats", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "steward_digest_records",
                "ordering": ["-sent_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TrackedItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "product",
                    models.CharField(
                        choices=[
                            ("nbhd_ios", "NBHD iOS"),
                            ("nbhd_united", "NBHD United"),
                            ("sautai", "Sautai"),
                            ("academy_watch", "Academy Watch"),
                            ("yardtalk", "YardTalk"),
                            ("portfolio", "Portfolio"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("work", "Work"),
                            ("release", "Release"),
                            ("blocked_on_mj", "Blocked on MJ"),
                            ("recurring", "Recurring"),
                            ("infra_watch", "Infrastructure watch"),
                        ],
                        max_length=24,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("context", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("active", "Active"),
                            ("blocked", "Blocked"),
                            ("parked", "Parked"),
                            ("done", "Done"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="proposed",
                        max_length=16,
                    ),
                ),
                ("blocked_reason", models.CharField(blank=True, max_length=200)),
                ("refs", models.JSONField(blank=True, default=list)),
                (
                    "provenance",
                    models.CharField(
                        choices=[("mj", "MJ"), ("collector", "Collector"), ("agent_proposed", "Agent proposed")],
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status_changed_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "steward_tracked_items",
                "ordering": ["product", "title", "id"],
            },
        ),
        migrations.AlterField(
            model_name="evidenceevent",
            name="source",
            field=models.CharField(
                choices=[
                    ("gateway_heartbeat", "Gateway heartbeat"),
                    ("ci_run", "CI run"),
                    ("asc_version_state", "App Store Connect version state"),
                    ("mj_ack", "MJ acknowledgement"),
                    ("eval_run", "Eval run"),
                    ("eval_slo", "Eval SLO"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="expectation",
            name="evidence_source",
            field=models.CharField(
                choices=[
                    ("gateway_heartbeat", "Gateway heartbeat"),
                    ("ci_run", "CI run"),
                    ("asc_version_state", "App Store Connect version state"),
                    ("mj_ack", "MJ acknowledgement"),
                    ("eval_run", "Eval run"),
                    ("eval_slo", "Eval SLO"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="Decision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("decided_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("decision", models.TextField()),
                ("rationale", models.TextField()),
                ("alternatives_rejected", models.TextField(blank=True)),
                ("refs", models.JSONField(blank=True, default=list)),
                (
                    "provenance",
                    models.CharField(
                        choices=[("mj", "MJ"), ("collector", "Collector"), ("agent_proposed", "Agent proposed")],
                        max_length=24,
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="steward.decision",
                    ),
                ),
            ],
            options={
                "db_table": "steward_decisions",
                "ordering": ["-decided_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="expectation",
            name="subject_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expectations",
                to="steward.trackeditem",
            ),
        ),
        migrations.CreateModel(
            name="DependencyEdge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("blocks", "Blocks"),
                            ("release_order", "Release order"),
                            ("shared_contract", "Shared contract"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "from_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_dependencies",
                        to="steward.trackeditem",
                    ),
                ),
                (
                    "to_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_dependencies",
                        to="steward.trackeditem",
                    ),
                ),
            ],
            options={
                "db_table": "steward_dependency_edges",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("from_item", "to_item", "kind"), name="steward_dependency_edge_unique"
                    )
                ],
            },
        ),
    ]
