# Generated by Django 6.0.7 on 2026-07-30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("steward", "0004_relock_after_steward_phase2"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertstate",
            name="suppressed_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="digestrecord",
            name="period_date",
            field=models.DateField(
                blank=True,
                help_text="UTC delivery date claimed by the scheduled daily digest.",
                null=True,
                unique=True,
            ),
        ),
    ]
