# Generated by Django 6.0.7 on 2026-07-31 05:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("steward", "0007_fingerprint_namespace_and_alert_reservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evidenceevent",
            name="source",
            field=models.CharField(
                choices=[
                    ("gateway_heartbeat", "Gateway heartbeat"),
                    ("ci_run", "CI run"),
                    ("github_state", "GitHub state"),
                    ("asc_version_state", "App Store Connect version state"),
                    ("mj_ack", "MJ acknowledgement"),
                    ("eval_run", "Eval run"),
                    ("eval_slo", "Eval SLO"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="expectation",
            name="evidence_source",
            field=models.CharField(
                choices=[
                    ("gateway_heartbeat", "Gateway heartbeat"),
                    ("ci_run", "CI run"),
                    ("github_state", "GitHub state"),
                    ("asc_version_state", "App Store Connect version state"),
                    ("mj_ack", "MJ acknowledgement"),
                    ("eval_run", "Eval run"),
                    ("eval_slo", "Eval SLO"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="RepoPullRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("repo", models.CharField(max_length=60)),
                ("number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=140)),
                ("author", models.CharField(max_length=60)),
                ("draft", models.BooleanField(default=False)),
                (
                    "state",
                    models.CharField(
                        choices=[("open", "Open"), ("merged", "Merged"), ("closed", "Closed")], max_length=12
                    ),
                ),
                ("opened_at", models.DateTimeField()),
                ("last_activity_at", models.DateTimeField()),
                ("is_dependabot", models.BooleanField(default=False)),
                ("head_ref", models.CharField(max_length=120)),
                ("synced_at", models.DateTimeField()),
            ],
            options={
                "db_table": "steward_repo_pull_requests",
                "ordering": ["repo", "number"],
                "indexes": [
                    models.Index(fields=["repo", "state", "last_activity_at"], name="steward_rep_repo_9e4144_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("repo", "number"), name="steward_repo_pull_request_repo_number_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReleaseTrain",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "product",
                    models.CharField(
                        choices=[
                            ("nbhd_ios", "NBHD iOS"),
                            ("nbhd_united", "NBHD United"),
                            ("sautai", "Sautai"),
                            ("academy_watch", "Academy Watch"),
                            ("yardtalk", "YardTalk"),
                            ("portfolio", "Portfolio"),
                        ],
                        max_length=24,
                    ),
                ),
                ("version_string", models.CharField(max_length=32)),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("integrating", "Integrating"),
                            ("verified_local", "Verified locally"),
                            ("pushed", "Pushed"),
                            ("ci_green", "CI green"),
                            ("tagged", "Tagged"),
                            ("submitted", "Submitted"),
                            ("in_review", "In review"),
                            ("released", "Released"),
                            ("rolled_back", "Rolled back"),
                        ],
                        default="planned",
                        max_length=24,
                    ),
                ),
                ("phase_changed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("refs", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tracked_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="release_trains",
                        to="steward.trackeditem",
                    ),
                ),
            ],
            options={
                "db_table": "steward_release_trains",
                "ordering": ["product", "version_string", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "version_string"), name="steward_release_train_product_version_unique"
                    )
                ],
            },
        ),
    ]
