# Generated by Django 6.0.7 on 2026-07-31

import django.utils.timezone
from django.db import migrations, models


def normalize_train_expectations(apps, schema_editor):
    Expectation = apps.get_model("steward", "Expectation")
    Expectation.objects.filter(owner="release_train").exclude(state="retired").update(evidence_source="mj_ack")
    Expectation.objects.filter(
        owner="release_train",
        state="satisfied",
    ).update(state="armed")


class Migration(migrations.Migration):
    dependencies = [
        ("steward", "0009_relock_after_steward_phase2b"),
    ]

    operations = [
        migrations.AddField(
            model_name="releasetrain",
            name="head_ref",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="releasetrain",
            name="head_sha",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.CreateModel(
            name="AscVersionSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_id", models.CharField(max_length=120, unique=True)),
                ("version_string", models.CharField(max_length=32)),
                ("app_state", models.CharField(max_length=60)),
                ("build_number", models.CharField(blank=True, max_length=32)),
                (
                    "build_processing_state",
                    models.CharField(blank=True, max_length=60),
                ),
                ("phased_state", models.CharField(blank=True, max_length=60)),
                (
                    "phased_day",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "steward_asc_version_snapshots",
                "ordering": ["version_string", "version_id"],
            },
        ),
        migrations.CreateModel(
            name="CollectorStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "collector",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("asc", "App Store Connect"),
                        ],
                        max_length=16,
                        unique=True,
                    ),
                ),
                (
                    "last_success_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_attempt_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_error_class",
                    models.CharField(blank=True, max_length=60),
                ),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                ("detail", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "db_table": "steward_collector_statuses",
                "ordering": ["collector"],
            },
        ),
        migrations.RunPython(normalize_train_expectations, migrations.RunPython.noop),
    ]
