# Generated by Django 6.0.7 on 2026-07-31 07:30

from django.db import migrations, models


def migrate_github_watermarks(apps, schema_editor):
    AlertState = apps.get_model("steward", "AlertState")
    GithubRepoCursor = apps.get_model("steward", "GithubRepoCursor")
    prefix = "github-pr-watermark:"
    for state in AlertState.objects.filter(
        fingerprint__startswith=prefix,
        last_sent_at__isnull=False,
    ):
        repo = state.fingerprint.removeprefix(prefix)
        GithubRepoCursor.objects.update_or_create(
            repo=repo,
            defaults={
                "complete_through": state.last_sent_at,
                "newest_seen": state.last_sent_at,
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("steward", "0011_relock_after_steward_phase2b_hardening"),
    ]

    operations = [
        migrations.CreateModel(
            name="GithubRepoCursor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("repo", models.CharField(max_length=60, unique=True)),
                ("complete_through", models.DateTimeField(blank=True, null=True)),
                ("newest_seen", models.DateTimeField(blank=True, null=True)),
                ("consecutive_truncations", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "steward_github_repo_cursors",
                "ordering": ["repo"],
            },
        ),
        migrations.RunPython(migrate_github_watermarks, migrations.RunPython.noop),
        migrations.AddField(
            model_name="ascversionsnapshot",
            name="revision",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="collectorstatus",
            name="consecutive_truncations",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="releasetrain",
            name="ci_workflow",
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.CreateModel(
            name="GithubTagSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("repo", models.CharField(max_length=60)),
                ("tag_name", models.TextField()),
                ("sha", models.CharField(max_length=64)),
                ("revision", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "steward_github_tag_snapshots",
                "ordering": ["repo", "tag_name"],
                "constraints": [
                    models.UniqueConstraint(fields=("repo", "tag_name"), name="steward_github_tag_repo_name_unique")
                ],
            },
        ),
    ]
