# Generated by Django 6.0.7 on 2026-07-31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("steward", "0013_relock_after_steward_phase2b_round2"),
    ]

    operations = [
        migrations.AddField(
            model_name="ascversionsnapshot",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="collectorstatus",
            name="held_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="releasetrain",
            name="ci_binding_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="GithubRepoCursor",
        ),
    ]
