# Generated by Django 6.0.7 on 2026-08-04

from __future__ import annotations

from django.db import migrations, models

EVIDENCE_SOURCE_CHOICES = [
    ("gateway_heartbeat", "Gateway heartbeat"),
    ("ci_run", "CI run"),
    ("github_state", "GitHub state"),
    ("asc_version_state", "App Store Connect version state"),
    ("mj_ack", "MJ acknowledgement"),
    ("eval_run", "Eval run"),
    ("eval_slo", "Eval SLO"),
    ("openrouter_model_health", "OpenRouter model health"),
]


class Migration(migrations.Migration):
    dependencies = [
        ("steward", "0014_phase2b_round3_simplification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectorstatus",
            name="collector",
            field=models.CharField(
                choices=[
                    ("github", "GitHub"),
                    ("asc", "App Store Connect"),
                    ("openrouter", "OpenRouter"),
                ],
                max_length=16,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="evidenceevent",
            name="source",
            field=models.CharField(choices=EVIDENCE_SOURCE_CHOICES, max_length=32),
        ),
        migrations.AlterField(
            model_name="expectation",
            name="evidence_source",
            field=models.CharField(choices=EVIDENCE_SOURCE_CHOICES, max_length=32),
        ),
        migrations.CreateModel(
            name="OpenRouterModelDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("account", "Account"),
                            ("canary", "Canary"),
                            ("provider", "Provider"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="OpenRouter model slug, or provider name when scope=provider.",
                        max_length=200,
                    ),
                ),
                ("finish_reason", models.CharField(max_length=64)),
                ("request_count", models.PositiveBigIntegerField()),
                ("avg_latency_ms", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "steward_openrouter_model_daily",
                "ordering": ["-date", "scope", "model", "finish_reason"],
                "indexes": [
                    models.Index(
                        fields=["scope", "model", "date"],
                        name="steward_or_scope_model_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "scope", "model", "finish_reason"),
                        name="steward_openrouter_daily_dimension_unique",
                    )
                ],
            },
        ),
    ]
