# Generated by Django 6.0.7 on 2026-09-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("steward", "0016_relock_after_openrouter_model_daily"),
    ]

    operations = [
        migrations.AlterField(
            model_name="digestrecord",
            name="delivery",
            field=models.CharField(
                choices=[
                    ("delivered", "Delivered"),
                    ("recorded", "Recorded"),
                    ("timeout", "Timeout"),
                    ("transient", "Transient"),
                    ("undeliverable", "Undeliverable"),
                ],
                max_length=16,
            ),
        ),
    ]
