# Generated by Django 5.1.15 on 2026-02-08 06:14

import django.db.models.deletion
from django.db import migrations, models


def backfill_tenant_user(apps, schema_editor):
    Tenant = apps.get_model("tenants", "Tenant")
    User = apps.get_model("tenants", "User")

    for tenant in Tenant.objects.filter(user__isnull=True).iterator():
        user = User.objects.filter(tenant_id=tenant.id).order_by("date_joined", "id").first()
        if user is None:
            user = User.objects.create(
                username=f"migrated_{str(tenant.id).replace('-', '')[:24]}",
                display_name=getattr(tenant, "name", "") or "Friend",
            )
        tenant.user_id = user.id
        tenant.save(update_fields=["user"])


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_username",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="tenant",
            name="container_fqdn",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Internal FQDN of the container",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="container_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Azure Container App name (e.g. oc-usr-abc123)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="estimated_cost_this_month",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="tenant",
            name="key_vault_prefix",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Key Vault secret prefix (e.g. tenants-<uuid>)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="last_message_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="managed_identity_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Azure User-Assigned Managed Identity resource ID",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="messages_this_month",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tenant",
            name="messages_today",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tenant",
            name="model_tier",
            field=models.CharField(
                choices=[("basic", "Basic (Sonnet)"), ("plus", "Plus (Opus available)")],
                default="basic",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="monthly_token_budget",
            field=models.IntegerField(
                default=500000, help_text="Per-user monthly token budget"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="provisioned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("provisioning", "Provisioning"),
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("deprovisioning", "Deprovisioning"),
                    ("deleted", "Deleted"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="tenant",
            name="tokens_this_month",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tenant",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenant",
                to="tenants.user",
            ),
        ),
        migrations.RunPython(backfill_tenant_user, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="tenant",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenant",
                to="tenants.user",
            ),
        ),
        migrations.RemoveField(
            model_name="user",
            name="tenant",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="name",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="plan_tier",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="slug",
        ),
        migrations.DeleteModel(
            name="AgentConfig",
        ),
    ]
