# Generated by Django 5.1.15 on 2026-02-08 13:08

import json

from django.db import migrations


def create_beat_schedules(apps, schema_editor):
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    # Daily at midnight UTC
    daily_midnight, _ = CrontabSchedule.objects.get_or_create(
        minute="0", hour="0", day_of_week="*",
        day_of_month="*", month_of_year="*",
        defaults={"timezone": "UTC"},
    )

    # 1st of month at midnight UTC
    monthly_first, _ = CrontabSchedule.objects.get_or_create(
        minute="0", hour="0", day_of_week="*",
        day_of_month="1", month_of_year="*",
        defaults={"timezone": "UTC"},
    )

    # Every hour
    hourly, _ = CrontabSchedule.objects.get_or_create(
        minute="0", hour="*", day_of_week="*",
        day_of_month="*", month_of_year="*",
        defaults={"timezone": "UTC"},
    )

    PeriodicTask.objects.get_or_create(
        name="Reset daily message counters",
        defaults={
            "task": "apps.tenants.tasks.reset_daily_counters_task",
            "crontab": daily_midnight,
            "kwargs": json.dumps({}),
            "enabled": True,
        },
    )

    PeriodicTask.objects.get_or_create(
        name="Reset monthly counters",
        defaults={
            "task": "apps.tenants.tasks.reset_monthly_counters_task",
            "crontab": monthly_first,
            "kwargs": json.dumps({}),
            "enabled": True,
        },
    )

    PeriodicTask.objects.get_or_create(
        name="Cleanup expired Telegram link tokens",
        defaults={
            "task": "apps.tenants.tasks.cleanup_expired_telegram_tokens",
            "crontab": hourly,
            "kwargs": json.dumps({}),
            "enabled": True,
        },
    )


def remove_beat_schedules(apps, schema_editor):
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    PeriodicTask.objects.filter(
        name__in=[
            "Reset daily message counters",
            "Reset monthly counters",
            "Cleanup expired Telegram link tokens",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_telegramlinktoken"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.RunPython(create_beat_schedules, remove_beat_schedules),
    ]
