# Generated by Django 5.1.15 on 2026-02-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_remove_celery_beat_schedules'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='internal_api_key_hash',
            field=models.CharField(blank=True, default='', help_text="SHA-256 hex digest of this tenant's internal API key", max_length=64),
        ),
        migrations.AddField(
            model_name='tenant',
            name='internal_api_key_set_at',
            field=models.DateTimeField(blank=True, help_text='When the per-tenant internal API key was last generated', null=True),
        ),
    ]
