# Generated by Django 5.1.15 on 2026-02-16 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_user_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='model_tier',
            field=models.CharField(choices=[('starter', 'Starter (Kimi K2.5)'), ('premium', 'Premium (Sonnet/Opus)'), ('byok', 'Bring Your Own Key')], default='starter', max_length=20),
        ),
        migrations.CreateModel(
            name='UserLLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('groq', 'Groq'), ('google', 'Google Gemini'), ('openrouter', 'OpenRouter'), ('xai', 'xAI (Grok)')], default='anthropic', max_length=30)),
                ('encrypted_api_key', models.TextField(blank=True, default='', help_text='Fernet-encrypted API key')),
                ('model_id', models.CharField(blank=True, default='', help_text="Full model ID e.g. 'anthropic/claude-sonnet-4-20250514'", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llm_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_llm_configs',
            },
        ),
    ]
