# Generated by Django 5.1.15 on 2026-02-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_migrate_tier_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='config_refreshed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
