# Generated by Django 5.1.15 on 2026-02-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_tenant_is_trial_tenant_trial_ends_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='container_image_tag',
            field=models.CharField(blank=True, default='', help_text='Current OpenClaw container image tag (git SHA)', max_length=255),
        ),
    ]
