# Generated by Django 5.1.15 on 2026-02-19
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_tenant_container_image_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='encryption_key_ref',
            field=models.CharField(blank=True, default='', help_text='Key Vault secret name for tenant journal encryption', max_length=255),
        ),
    ]
