# Generated by Django 5.1.15 on 2026-03-04 01:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0016_add_pending_deletion_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='line_display_name',
            field=models.CharField(blank=True, default='', help_text='Display name from LINE profile', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='line_user_id',
            field=models.CharField(blank=True, help_text='LINE user ID (per-bot, not global)', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('line', 'LINE')], default='telegram', help_text='Primary channel for proactive messages (cron, alerts).', max_length=16),
        ),
        migrations.CreateModel(
            name='LineLinkToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_link_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'line_link_tokens',
                'indexes': [models.Index(fields=['expires_at'], name='line_link_t_expires_4e6d52_idx')],
            },
        ),
    ]
