# Generated by Django 5.1.15 on 2026-03-04 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0017_heartbeat_window'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='internal_api_key_hash',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='internal_api_key_set_at',
        ),
    ]
