# Generated by Django 5.1.15 on 2026-03-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0020_backfill_key_vault_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='gate_acknowledged_risk',
            field=models.BooleanField(default=False, help_text='User has explicitly acknowledged the risk of disabling gates'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='gate_all_actions',
            field=models.BooleanField(default=True, help_text='Master switch: require confirmation for all irreversible actions'),
        ),
    ]
