# Generated by Django 5.1.15 on 2026-04-21 03:31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0039_openclaw_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalAccessToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Human label, e.g. 'YardTalk on MacBook Pro'", max_length=255)),
                ('token_prefix', models.CharField(help_text='First 8 chars of the secret (for identification in UI)', max_length=8)),
                ('token_hash', models.CharField(help_text='SHA-256 hex digest of the full pat_... token', max_length=64, unique=True)),
                ('scopes', models.JSONField(blank=True, default=list, help_text='Allowed scopes, e.g. ["sessions:write", "sessions:read"]')),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Null = never expires', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_access_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'personal_access_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token_hash'], name='personal_ac_token_h_84bac7_idx'), models.Index(fields=['user', '-created_at'], name='personal_ac_user_id_413c36_idx')],
            },
        ),
    ]
