# Generated by Django 5.1.15 on 2026-04-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0042_cron_wake_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_budget_exempt',
            field=models.BooleanField(default=False, help_text='Exempt from personal and global budget enforcement. Usage still tracked.'),
        ),
    ]
