# Generated by Django 5.1.15 on 2026-04-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0046_openclaw_version_4_25"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="postgres_cron_canonical",
            field=models.BooleanField(
                default=False,
                help_text="Cutover flag for the Postgres-canonical cron model. When True, the CronJob table is the source of truth and OpenClaw's SQLite is a derived view kept in sync by the regenerate_tenant_crons reconciler.",
            ),
        ),
    ]
