# Generated by Django 5.1.15 on 2026-04-30 15:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0047_backfill_pat_scopes"),
        ("tenants", "0047_tenant_postgres_cron_canonical"),
    ]

    operations = []
