# Generated by Django 5.1.15 on 2026-04-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0048_merge_20260430_1526"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="byo_models_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable bring-your-own Anthropic/OpenAI subscription mode for this tenant"
            ),
        ),
    ]
