# Generated by Django 5.1.15 on 2026-05-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0051_byo_models_enabled_default_true"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="welcomes_sent",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-feature welcome-delivery timestamps (e.g. {'fuel': '2026-05-07T...', 'finance': ...})",
            ),
        ),
    ]
