# Generated by Django 5.1.15 on 2026-05-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0060_tenant_experimental_built_in_heartbeat"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="experimental_memory_core_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Experimental: enable OpenClaw memory-core with the SQLite index on container-local ephemeral storage (markdown stays on the share). Canary-gated rollout.",
            ),
        ),
    ]
