# Generated by Django 5.1.15 on 2026-05-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0061_tenant_experimental_memory_core"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="experimental_active_memory_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Experimental: enable the OpenClaw active-memory plugin (blocking pre-reply recall). Requires experimental_memory_core_enabled. Canary-gated rollout.",
            ),
        ),
    ]
