# Generated by Django 5.1.15 on 2026-05-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0062_tenant_experimental_active_memory"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="experimental_dreaming_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Experimental: enable OpenClaw memory-core dreaming for background consolidation. Requires experimental_memory_core_enabled. Canary-gated rollout.",
            ),
        ),
    ]
