# Generated by Django 5.1.15 on 2026-05-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0064_alter_tenant_applied_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="experimental_typed_journal_lifecycle",
            field=models.BooleanField(
                default=False,
                help_text="Experimental: route goal/task lifecycle through typed Goal/Task tables and corresponding nbhd_goal_*/nbhd_task_* tools instead of free-form Document markdown. Canary-gated rollout.",
            ),
        ),
    ]
