# Generated by Django 5.1.15 on 2026-05-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0067_postgres_cron_canonical_default_true"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="pii_denylist",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Canonical-keyed denylist of false-positive PII spans. Shape: {"goal": {}, "calendar": {"reason": "manual"}}.',
            ),
        ),
    ]
