# Generated by Django 5.1.15 on 2026-05-23 12:19

from django.db import migrations

KIMI_MODEL = "openrouter/moonshotai/kimi-k2.6"
DEEPSEEK_MODEL = "openrouter/deepseek/deepseek-v4-pro"


def kimi_to_deepseek(apps, schema_editor):
    """Rewrite Kimi K2.6 references on tenants to DeepSeek V4 Pro.

    Kimi was removed from `TIER_MODEL_CONFIGS["starter"]` in the same PR.
    Any tenant whose `preferred_model` or `task_model_preferences` still
    point at Kimi would fail the allowlist guard at config-generation
    time and silently inherit the chat primary instead. DeepSeek is the
    closest equivalent (reasoning + long context), so rewriting these
    rows in place preserves user intent.

    Pending config is bumped so the next reconciliation picks up the new
    primary; the same Kimi→DeepSeek substitution also lands in the
    rendered cron payloads on that pass.
    """
    Tenant = apps.get_model("tenants", "Tenant")
    rewritten = 0
    for tenant in Tenant.objects.all():
        changed = False
        if tenant.preferred_model == KIMI_MODEL:
            tenant.preferred_model = DEEPSEEK_MODEL
            changed = True
        prefs = tenant.task_model_preferences or {}
        if isinstance(prefs, dict):
            new_prefs = {k: (DEEPSEEK_MODEL if v == KIMI_MODEL else v) for k, v in prefs.items()}
            if new_prefs != prefs:
                tenant.task_model_preferences = new_prefs
                changed = True
        if changed:
            tenant.pending_config_version = (tenant.pending_config_version or 0) + 1
            tenant.save(
                update_fields=[
                    "preferred_model",
                    "task_model_preferences",
                    "pending_config_version",
                ]
            )
            rewritten += 1
    print(f"  Rewrote Kimi → DeepSeek on {rewritten} tenant(s)")


def deepseek_to_kimi(apps, schema_editor):
    """Reverse op — restore Kimi for tenants that were rewritten.

    Best-effort: this can't distinguish tenants who were originally on
    Kimi from tenants who chose DeepSeek directly after the forward
    migration ran. The reverse is intended for local rollback before
    DeepSeek goes wide; running it after fleet rollout would clobber
    legitimate DeepSeek selections. Use with care.
    """
    Tenant = apps.get_model("tenants", "Tenant")
    for tenant in Tenant.objects.all():
        changed = False
        if tenant.preferred_model == DEEPSEEK_MODEL:
            tenant.preferred_model = KIMI_MODEL
            changed = True
        prefs = tenant.task_model_preferences or {}
        if isinstance(prefs, dict):
            new_prefs = {k: (KIMI_MODEL if v == DEEPSEEK_MODEL else v) for k, v in prefs.items()}
            if new_prefs != prefs:
                tenant.task_model_preferences = new_prefs
                changed = True
        if changed:
            tenant.pending_config_version = (tenant.pending_config_version or 0) + 1
            tenant.save(
                update_fields=[
                    "preferred_model",
                    "task_model_preferences",
                    "pending_config_version",
                ]
            )


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0068_pii_denylist"),
    ]

    operations = [
        migrations.RunPython(kimi_to_deepseek, deepseek_to_kimi),
    ]
