# Generated by Django 5.1.15 on 2026-05-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0069_kimi_to_deepseek"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="last_nightly_extraction_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
