# Generated by Django 5.1.15 on 2026-05-25 15:24

from django.db import migrations, models
from django.utils import timezone


def grandfather_existing_users(apps, schema_editor):
    """
    Mark all existing users as already-verified. They predate this feature
    and most have active Stripe subscriptions + provisioned tenants — forcing
    re-verification would create support load for zero security value.
    Only new signups after this migration go through the verify-email flow.
    """
    User = apps.get_model("tenants", "User")
    now = timezone.now()
    User.objects.filter(email_verified=False).update(
        email_verified=True,
        email_verified_at=now,
    )


def reverse_grandfather(apps, schema_editor):
    # Schema rollback handles field removal; nothing data-side to undo.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0069_kimi_to_deepseek"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(
                default=False,
                help_text="True once the user has clicked the verification link.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When email verification was completed.",
                null=True,
            ),
        ),
        migrations.RunPython(
            grandfather_existing_users,
            reverse_grandfather,
        ),
    ]
