# Generated by Django 5.1.15 on 2026-05-27 05:49

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0070_tenant_last_nightly_extraction_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCampaign",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "code",
                    models.SlugField(
                        help_text="URL-safe campaign identifier (e.g. 'privacy-june-2026').", max_length=64, unique=True
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("trial_extension", "Trial extension")], default="trial_extension", max_length=32
                    ),
                ),
                (
                    "extension_days",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Days to add to trial_ends_at when redeemed (for TRIAL_EXTENSION kind)."
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(help_text="Hard deadline — redemption rejected after this timestamp."),
                ),
                (
                    "audience_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Frozen audit of which user IDs the campaign targeted. Written at send time so we can compare against redemptions later.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "promo_campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="password_last_changed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Stamp updated whenever ``set_password`` is called. Used by the JWT validator to invalidate access + refresh tokens issued before a password rotation, without needing the simplejwt token_blacklist app.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="PromoRedemption",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("redeemed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("extended", "Trial extended"),
                            ("already_subscribed", "User has an active subscription"),
                            ("no_tenant", "User has no associated tenant"),
                        ],
                        default="extended",
                        max_length=32,
                    ),
                ),
                (
                    "new_trial_ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="trial_ends_at value after the extension applied. Null for non-EXTENDED outcomes.",
                        null=True,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="tenants.promocampaign",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_redemptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "promo_redemptions",
                "ordering": ["-redeemed_at"],
                "indexes": [models.Index(fields=["user", "-redeemed_at"], name="promo_red_user_idx")],
                "unique_together": {("campaign", "user")},
            },
        ),
        # Enable RLS on the new public-schema tables to match the
        # public-schema lockdown invariant (tenants/0059 + tenants/0066).
        # The Django backend connects as the table owner and bypasses
        # RLS; the anon role PostgREST exposes has no SELECT/INSERT/UPDATE
        # grant on these tables. Mirrors the lockdown applied to
        # apps/router/migrations/0007_proactive_outbound.py and
        # apps/router/migrations/0008_line_quota_state.py.
        migrations.RunSQL(
            sql="ALTER TABLE promo_campaigns ENABLE ROW LEVEL SECURITY;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE promo_redemptions ENABLE ROW LEVEL SECURITY;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
