# Generated by Django 5.1.15 on 2026-05-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0071_privacy_rotation_2026"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="experimental_typed_crons",
            field=models.BooleanField(
                default=False,
                help_text="Experimental: typed cron patterns (pure_reminder, quote_user_intent, domain_summary, daily_briefing). Loads nbhd-automation-tools + nbhd-cron-enforcement plugins. Canary-gated rollout.",
            ),
        ),
    ]
