# Generated by Django 5.1.15 on 2026-05-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0073_relock_after_typed_crons"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="openrouter_key_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="OpenRouter-side hash identifying this tenant's sub-key (for management DELETE)",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="openrouter_key_secret_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Key Vault secret name holding this tenant's OpenRouter sub-key (PR #1.6)",
                max_length=255,
            ),
        ),
    ]
