# Generated by Django 5.1.15 on 2026-05-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0074_tenant_openrouter_key_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="cost_exhausted_email_sent_at",
            field=models.DateTimeField(
                blank=True, help_text="When the cap-exhausted email was last sent (cleared monthly).", null=True
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="cost_warn_sent_at",
            field=models.DateTimeField(
                blank=True, help_text="When the 90%-of-cap warning email was last sent (cleared monthly).", null=True
            ),
        ),
    ]
