# Generated by Django 5.1.15 on 2026-05-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0075_tenant_cost_exhausted_email_sent_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="first_message_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the tenant's first-ever inbound message across any channel. Set once at the first PendingMessage insert and never bumped again — used to measure onboarding activation.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="welcome_email_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the Day-0 welcome email was delivered to the tenant's User.email. Set after a successful send; checked as the idempotency guard so provisioning retries don't re-send.",
                null=True,
            ),
        ),
    ]
