# Generated by Django 5.1.15 on 2026-06-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0076_welcome_email_and_first_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="openclaw_version",
            field=models.CharField(
                default="2026.5.28", help_text="OpenClaw runtime version pinned to this tenant's config", max_length=20
            ),
        ),
    ]
