# Generated by Django 5.1.15 on 2026-05-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0077_relock_after_fuel_plan_slot"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="fuel_version",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Monotonic counter bumped on every Workout / WorkoutPlan write. Embedded in schedule / calendar responses so the frontend can detect an out-of-band write by the assistant runtime and prompt the user to refresh before saving an open drawer.",
            ),
        ),
    ]
