# Generated by Django 5.1.15 on 2026-06-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0078_relock_constellation_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="core_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable the Core mindfulness pillar (on-demand guided meditations)"
            ),
        ),
    ]
