# Generated by Django 5.1.15 on 2026-06-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0083_relock_after_ios_chat"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="purchased_credit",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Prepaid credit balance in USD. EXTENDS the monthly included allowance once it's spent; persists across months and does not expire. Granted by Stripe top-ups and drawn down for usage beyond the included cap. Source of truth for grants/refunds is apps.billing.models.CreditLedger; this is the denormalized hot-read balance.",
                max_digits=10,
            ),
        ),
    ]
