# Generated by Django 5.1.15 on 2026-06-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0086_migrate_minimax_preferred_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="last_wake_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the container was last woken from hibernation. The message drain treats container-down errors within a grace window of this as 'still booting' (retry soon, don't burn delivery attempts) instead of delivery failures.",
                null=True,
            ),
        ),
    ]
