# Generated by Django 5.1.15 on 2026-06-18 07:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0087_app_user_idle_session_timeout"),
        ("tenants", "0087_tenant_last_wake_at"),
    ]

    operations = []
