# Generated by Django 5.1.15 on 2026-06-19 05:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0088_merge_20260618_0727"),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthAuthorizationCode",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "code_hash",
                    models.CharField(
                        help_text="SHA-256 hex digest of the raw code handed to the SPA.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "code_challenge",
                    models.CharField(
                        help_text="S256 base64url challenge (~43 chars). Re-derived from the verifier at exchange and compared constant-time.",
                        max_length=128,
                    ),
                ),
                ("code_challenge_method", models.CharField(default="S256", max_length=8)),
                ("redirect_uri", models.CharField(max_length=255)),
                ("client", models.CharField(default="ios", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_authorization_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "oauth_authorization_codes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["code_hash"], name="oauth_autho_code_ha_a20500_idx"),
                    models.Index(fields=["expires_at"], name="oauth_autho_expires_0cd250_idx"),
                ],
            },
        ),
    ]
