# Generated by Django 5.1.15 on 2026-07-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0090_relock_after_oauth_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="site_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-tenant website publishing targets for the nbhd-site-publishing plugin. Keys: cosmosEndpoint, cosmosDatabase, cosmosContainer, blobAccount, blobContainer, blobPathPrefix.",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="site_publishing_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable the assistant to publish images to the subscriber's own website"
            ),
        ),
    ]
