# Generated by Django 5.1.15 on 2026-07-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0091_tenant_site_config_tenant_site_publishing_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="identity_growth",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Identity rollback + growth snapshots for SOUL.md/IDENTITY.md (see backfill_identity_growth).",
                null=True,
            ),
        ),
    ]
