# Generated by Django 5.1.15 on 2026-07-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0092_tenant_identity_growth"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_opt_out",
            field=models.BooleanField(
                default=False, help_text="True if the user unsubscribed from marketing/campaign emails."
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_opt_out_at",
            field=models.DateTimeField(
                blank=True, help_text="When the user unsubscribed (null if still subscribed).", null=True
            ),
        ),
    ]
