# Generated by Django 5.1.15 on 2026-07-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0093_user_email_opt_out_user_email_opt_out_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="chat_last_read_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the user last marked the in-app chat read (POST /chat/read/). The APNs unread badge counts assistant replies / proactive pushes after this.",
                null=True,
            ),
        ),
    ]
