# Generated by Django 5.1.15 on 2026-07-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0094_user_chat_last_read_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="dunning_notice_invoice_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Stripe invoice id of the last failed invoice we sent a retry-notice email for.",
                max_length=255,
            ),
        ),
    ]
