# Generated by Django 5.1.15 on 2026-07-05 01:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0095_tenant_dunning_notice_invoice_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="friends_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable the Neighborhood (Friends) layer — waves, shared sparks, wormholes, chat",
            ),
        ),
    ]
