# Generated by Django 5.1.15 on 2026-07-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0103_relock_after_circles"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="friends_agent_propose_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Let the assistant PROPOSE shares/mission-tasks (human still approves every one). Off + friends_enabled = an absorb-only agent: it reads neighbors' sparks but never proposes. Gates the propose plugin tools, the AGENTS.md propose rules, and the runtime propose endpoints.",
            ),
        ),
    ]
