# Generated by Django 5.1.15 on 2026-07-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0107_tenant_cluster_label_cache"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="pii_type_counters",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Per-type monotonic high-water mark for PII placeholder numbering (highest suffix ever minted per type, e.g. {"PERSON": 537}). Never lowered on deletion — prevents freed placeholder numbers from being recycled.',
            ),
        ),
    ]
