# Generated by Django 5.1.15 on 2026-07-10 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0109_seed_pii_type_counters"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantDek",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dek_epoch", models.PositiveSmallIntegerField(default=0)),
                ("wrapped_dek", models.BinaryField()),
                ("kek_version", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="deks", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "unique_together": {("tenant", "dek_epoch")},
            },
        ),
    ]
