# Generated by Django 5.1.15 on 2026-07-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0111_relock_after_tenant_deks"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="constellation_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Gate the Constellation visualization tab in the client apps. Pure client-side feature — involves no assistant plugin, config bump, or container restart.",
            ),
        ),
    ]
