# Generated by Django 5.1.15 on 2026-07-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0112_constellation_enabled_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="document_ingestion_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable document information-keeping: the record/list/forget tools, the AGENTS.md tool-language block, and the same-turn write backstop that blocks a durable write on the turn a document arrived.",
            ),
        ),
    ]
