# Generated by Django 5.1.15 on 2026-07-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0112_constellation_enabled_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="encrypt_chat_writes",
            field=models.BooleanField(
                default=False,
                help_text="Dual-write sealed *_enc envelopes for chat content (encryption-at-rest Phase 2).",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="read_encrypted_chat",
            field=models.BooleanField(
                default=False,
                help_text="Read chat content back through the *_enc column when present (encryption-at-rest Phase 2).",
            ),
        ),
    ]
