# Generated by Django 5.1.15 on 2026-07-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0117_relock_after_eval_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="is_synthetic",
            field=models.BooleanField(
                default=False,
                help_text="Eval-system synthetic tenant (see docs/evals-directive.md). Behaves EXACTLY like a real tenant operationally (provisions, drains, crons, hibernates/wakes) — that is the point — but is EXCLUDED from business-facing aggregates (revenue, donation, campaign audiences, usage/true-cost, growth counts) so it never distorts a number. Never set for a real subscriber.",
            ),
        ),
    ]
