# Generated by Django 5.1.15 on 2026-07-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0119_relock_after_is_synthetic"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="email_provenance_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable email/calendar/Reddit ingestion provenance: the AGENTS.md gate teaching propose-then-stamp for information saved from a read, recorded on the document-keeping ledger with a source_kind + source_ref. Requires document_ingestion_enabled (the record/list/forget tools) and the plugin image roll.",
            ),
        ),
    ]
