# Generated by Django 5.1.15 on 2026-07-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0120_tenant_email_provenance_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="sautai_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable sautai meal-plan generation tools (nutrition sibling of Fuel)"
            ),
        ),
    ]
