# Generated by Django 6.0.7 on 2026-07-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0122_relock_after_sautai_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="encrypt_fuel_writes",
            field=models.BooleanField(
                default=False,
                help_text="Dual-write sealed *_enc envelopes for fuel content (encryption-at-rest Phase 3).",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="encrypt_journal_writes",
            field=models.BooleanField(
                default=False,
                help_text="Dual-write sealed *_enc envelopes for journal/lessons/insights/core content (encryption-at-rest Phase 3).",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="read_encrypted_fuel",
            field=models.BooleanField(
                default=False,
                help_text="Read fuel content back through the *_enc column when present (encryption-at-rest Phase 3).",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="read_encrypted_journal",
            field=models.BooleanField(
                default=False,
                help_text="Read journal/lessons/insights/core content back through the *_enc column when present (encryption-at-rest Phase 3).",
            ),
        ),
    ]
