# Generated by Django 5.1.15 on 2026-07-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0122_relock_after_sautai_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="service_email_opt_out",
            field=models.BooleanField(
                default=False,
                help_text="True if the user unsubscribed from service/operational notice emails (channel sunset, maintenance). Auth-critical emails (password reset) remain exempt.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="service_email_opt_out_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the user unsubscribed from service notices (null if still subscribed).",
                null=True,
            ),
        ),
    ]
