# Generated by Django 5.1.15 on 2026-07-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0124_relock_after_enc_p3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="experimental_typed_crons",
            field=models.BooleanField(
                default=True,
                help_text="Typed cron patterns (pure_reminder, quote_user_intent, domain_summary, daily_briefing). Loads nbhd-automation-tools + nbhd-cron-enforcement plugins. Fleet-wide since 2026-07-13; default True so a new tenant gets the cron-create tools the base AGENTS.md capability list advertises — a flag-off tenant would read that it can set reminders and have no tool to do it.",
            ),
        ),
    ]
