# Generated by Django 6.0.7 on 2026-07-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0125_relock_after_sautai_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="experimental_reply_artifacts_to_journal",
            field=models.BooleanField(
                default=False,
                help_text="Experimental: move oversized GFM tables from persisted assistant history into Journal documents. Canary-gated rollout.",
            ),
        ),
    ]
