# Generated by Django 6.0.7 on 2026-07-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0130_relock_after_is_eval_sink"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="tour_guide_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable server-side tour-guide instructions for this tenant"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="tour_guide_mode",
            field=models.CharField(
                choices=[("cards", "Cards"), ("links", "Links")],
                default="links",
                help_text="Cards: the dev/TestFlight client renders nbhd-guide itinerary cards. Links: the standard App Store client receives plain maps links only.",
                max_length=8,
            ),
        ),
    ]
