# Generated by Django 6.0.7 on 2026-07-19 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0132_tenant_journal_shaping_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="situational_context_enabled",
            field=models.BooleanField(
                default=False, help_text="Capture and render structured current-situation signals for this tenant"
            ),
        ),
        migrations.CreateModel(
            name="UserSituation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("current_place_label", models.CharField(blank=True, default="", max_length=64)),
                ("current_place_since", models.DateTimeField(null=True)),
                ("current_place_last_observed_at", models.DateTimeField(null=True)),
                ("current_place_source", models.CharField(blank=True, default="", max_length=16)),
                ("device_tz", models.CharField(blank=True, default="", max_length=64)),
                ("device_tz_since", models.DateTimeField(null=True)),
                ("device_tz_last_observed_at", models.DateTimeField(null=True)),
                ("device_tz_source_device", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="situation", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "user_situations",
            },
        ),
    ]
