# Generated by Django 6.0.7 on 2026-07-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0134_relock_after_user_situations"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="tour_guide_manifest_ok",
            field=models.BooleanField(
                default=False,
                help_text="Runtime image's settings-tools manifest declares tourGuide config keys; set per-tenant after image verification, fleet-wide at fleet image rollout. Nothing reconciles this field.",
            ),
        ),
    ]
