# Generated by Django 6.0.7 on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0135_tenant_tour_guide_manifest_ok"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="places_search_manifest_ok",
            field=models.BooleanField(
                default=False,
                help_text="Runtime image's settings-tools manifest declares/registers nbhd_places_search; set per-tenant after image verification, nothing reconciles this.",
            ),
        ),
    ]
