# Generated by Django 6.0.7 on 2026-07-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0135_tenant_tour_guide_manifest_ok"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="digest_thread_attribution_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Label non-main iOS chat content in the shared conversation digest with its source thread",
            ),
        ),
    ]
