# Generated by Django 6.0.7 on 2026-07-30 04:04

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0138_relock_after_yardtalk"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppleAuthTransaction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("state", models.CharField(max_length=64)),
                ("nonce_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("purpose", models.CharField(default="web_auth", max_length=32)),
            ],
            options={
                "db_table": "apple_auth_transactions",
            },
        ),
        migrations.CreateModel(
            name="AppleRevocationOutbox",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("token_ciphertext", models.TextField()),
                ("subject", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, default="", max_length=512)),
            ],
            options={
                "db_table": "apple_revocation_outbox",
            },
        ),
        migrations.CreateModel(
            name="ExternalIdentity",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider", models.CharField(default="apple", editable=False, max_length=32)),
                ("subject", models.CharField(max_length=255)),
                ("issuer", models.CharField(default="https://appleid.apple.com", editable=False, max_length=255)),
                ("audience", models.CharField(max_length=255)),
                ("email_at_auth", models.EmailField(blank=True, default="", max_length=254)),
                ("email_is_relay", models.BooleanField(default=False)),
                ("email_verified_at_auth", models.BooleanField(default=False)),
                ("refresh_token_encrypted", models.TextField()),
                ("refresh_token_updated_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_login_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_identities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "external_identities",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "subject"), name="uq_external_identity_provider_subject"
                    ),
                    models.UniqueConstraint(fields=("user", "provider"), name="uq_external_identity_user_provider"),
                ],
            },
        ),
    ]
