# Generated by Django 6.0.7 on 2026-08-04 14:35

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0142_bump_tier_default_tenants_for_flash"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCampaignSend",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sends", to="tenants.promocampaign"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_campaign_sends",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "promo_campaign_sends",
                "ordering": ["-sent_at"],
                "constraints": [
                    models.UniqueConstraint(fields=("campaign", "user"), name="promo_send_campaign_user_uniq")
                ],
            },
        ),
        migrations.RunSQL(
            sql="ALTER TABLE promo_campaign_sends ENABLE ROW LEVEL SECURITY;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
