# Generated by Django 6.0.7 on 2026-08-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0143_promo_campaign_send"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="recall_capture_birthday",
            field=models.DateTimeField(
                blank=True,
                help_text="Memory has a birthday: recall includes only content captured from this moment forward.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="recall_capture_enabled",
            field=models.BooleanField(
                default=False, help_text="Capture transcript memory from its birthday forward; disabled by default."
            ),
        ),
    ]
