# Generated by Django 6.0.7 on 2026-08-07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0144_tenant_recall_capture_birthday_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="layer1_placeholder_writes",
            field=models.BooleanField(
                default=False,
                help_text="Store Layer-1 authored text in PII placeholder space; disabled by default.",
            ),
        ),
    ]
