# Generated by Django 6.0.7 on 2026-08-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0146_bump_tier_default_tenants_for_pro"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaceholderMigrationCursor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "store_label",
                    models.CharField(max_length=128),
                ),
                (
                    "mode",
                    models.CharField(choices=[("dry-run", "Dry run"), ("commit", "Commit")], max_length=8),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("skipped", "Repair queue not drained"),
                            ("complete", "Complete"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("last_pk", models.CharField(blank=True, default="", max_length=64)),
                ("report_counts", models.JSONField(blank=True, default=dict)),
                ("lease_token", models.UUIDField(blank=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placeholder_migration_cursors",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "pii_placeholder_migration_cursors",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "store_label", "mode"),
                        name="pii_migration_cursor_tenant_store_mode_uniq",
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            sql="ALTER TABLE pii_placeholder_migration_cursors ENABLE ROW LEVEL SECURITY;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
