# Generated by Django 6.0.7 on 2026-08-09 08:00

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("tenants", "0147_placeholdermigrationcursor"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppleGrant",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("client_id", models.CharField(db_index=True, max_length=255)),
                ("refresh_token_encrypted", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("rotated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "apple_grants",
            },
        ),
        migrations.AddField(
            model_name="applerevocationoutbox",
            name="backfill_source",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="applerevocationoutbox",
            name="claimed_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="applerevocationoutbox",
            name="client_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="applerevocationoutbox",
            name="consecutive_invalid_client",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="applerevocationoutbox",
            name="next_attempt_at",
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="applerevocationoutbox",
            name="subject_verified",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="terms_accepted_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="terms_version",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="applerevocationoutbox",
            name="subject",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                condition=models.Q(("email", ""), _negated=True),
                name="uq_users_email_lower_nonblank",
            ),
        ),
        migrations.AddField(
            model_name="applegrant",
            name="identity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="grants", to="tenants.externalidentity"
            ),
        ),
        migrations.AddConstraint(
            model_name="applegrant",
            constraint=models.UniqueConstraint(fields=("identity", "client_id"), name="uq_apple_grant_identity_client"),
        ),
    ]
