# Generated by Django 6.0.7 on 2026-08-11 00:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0151_catch_up_apple_grants_and_outbox"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="datebook_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable the server-side Calendar & Reminders capability for this tenant."
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="datebook_events_consent_at",
            field=models.DateTimeField(
                blank=True, help_text="Server timestamp of the tenant's Calendar third-party-AI consent.", null=True
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="datebook_manifest_ok",
            field=models.BooleanField(
                default=False,
                help_text="Runtime image carries the verified datebook plugin manifest. Set only after image verification; nothing reconciles this field.",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="datebook_reminders_consent_at",
            field=models.DateTimeField(
                blank=True, help_text="Server timestamp of the tenant's Reminders third-party-AI consent.", null=True
            ),
        ),
    ]
