# Generated by Django 6.0.7 on 2026-08-26 05:51

from django.db import migrations, models


def disable_byo_for_fleet(apps, schema_editor):
    Tenant = apps.get_model("tenants", "Tenant")
    Tenant.objects.exclude(status="deleted").update(byo_models_enabled=False)


def restore_byo_for_fleet(apps, schema_editor):
    Tenant = apps.get_model("tenants", "Tenant")
    Tenant.objects.exclude(status="deleted").update(byo_models_enabled=True)


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0158_relock_after_calendar_context"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="byo_models_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable bring-your-own Anthropic/OpenAI subscription mode for this tenant"
            ),
        ),
        migrations.RunPython(disable_byo_for_fleet, restore_byo_for_fleet),
    ]
