# Generated by Django 6.0.7 on 2026-08-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0159_relock_after_appchatmessage_redaction_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="provision_lease_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Heartbeat stamped by the run that atomically claimed provisioning for this tenant. A PROVISIONING row is only reclaimable once this goes stale (see orchestrator.services._PROVISION_LEASE_STALE) — without it, concurrent runs (QStash redelivery, Stripe retry racing checkout) both mint an internal API key and the DB/KV values diverge, bricking every authenticated container call.",
                null=True,
            ),
        ),
    ]
