# Generated by Django 6.0.7 on 2026-08-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0160_tenant_provision_lease_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="site_editor_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-tenant nbhd-site-editor config. Keys: owner, repo, branch, allowPaths, denyPaths, maxTextBytes, maxImageBytes, maxFiles, maxTotalBytes, deployMinutes, authorEmail.",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="site_editor_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable guarded GitHub source editing for the subscriber's own website"
            ),
        ),
    ]
