# Generated by Django 6.0.7 on 2026-09-07 21:09

from django.db import migrations

RELOCK_SQL = r"""
DO $$
DECLARE
  r RECORD;
BEGIN
  FOR r IN
    SELECT schemaname, tablename
    FROM pg_tables
    WHERE schemaname = 'public'
      AND tableowner = current_user
      AND rowsecurity = false
  LOOP
    EXECUTE format('ALTER TABLE %I.%I ENABLE ROW LEVEL SECURITY',
                   r.schemaname, r.tablename);
  END LOOP;
END
$$;
"""

REVERSE_SQL = "-- Reversing would leave public tables unlocked at migration time. Do not auto-reverse."


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0161_tenant_site_editor"),
        ("core", "0006_completion_truth_lesson"),
        ("fuel", "0020_completion_truth_lesson"),
    ]

    operations = [migrations.RunSQL(RELOCK_SQL, REVERSE_SQL)]
