# Generated by Django 6.0.7 on 2026-09-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0163_relock_after_lesson_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="neighborhood_enabled",
            field=models.BooleanField(
                default=True, help_text="Person can use the Neighborhood — waves, neighbor chat, circles, shared sparks"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="friends_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Assistant participates in the Neighborhood (friends plugin, tools, AGENTS.md section)",
            ),
        ),
    ]
