# Generated by Django 6.0.7 on 2026-09-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0167_relock_after_message_panels"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="openclaw_migration",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Private OpenClaw migration checkpoints, source snapshot and verification evidence.",
            ),
        ),
    ]
