# Generated by Django 6.1 on 2026-09-26 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0170_openclaw_migration_cron_fence"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenClawAutoUpgrade",
            fields=[
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="openclaw_auto_upgrade",
                        serialize=False,
                        to="tenants.tenant",
                    ),
                ),
                ("cooldown_until", models.DateTimeField(blank=True, null=True)),
                ("run_token", models.CharField(blank=True, default="", max_length=32)),
                ("migration_token", models.CharField(blank=True, default="", max_length=32)),
                ("counters", models.JSONField(blank=True, default=dict)),
                ("last_outcome", models.JSONField(blank=True, default=dict)),
                ("history", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "openclaw_auto_upgrades",
            },
        ),
        migrations.CreateModel(
            name="OpenClawAutoUpgradeLock",
            fields=[
                ("id", models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ("run_token", models.CharField(blank=True, default="", max_length=32)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("next_allowed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "openclaw_auto_upgrade_lock",
            },
        ),
        # Public-schema lockdown invariant (tenants/0058 + 0066): the Django
        # owner role bypasses RLS; PostgREST roles get no rows.
        migrations.RunSQL(
            sql=(
                "ALTER TABLE openclaw_auto_upgrade_lock ENABLE ROW LEVEL SECURITY;"
                "ALTER TABLE openclaw_auto_upgrades ENABLE ROW LEVEL SECURITY;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
