# Generated by Django 6.0.7 on 2026-08-11 00:33

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0152_datebook_b1"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatebookGateway",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("installation_id", models.CharField(max_length=64)),
                ("gateway_epoch", models.PositiveBigIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("retired", "Retired")], default="active", max_length=12
                    ),
                ),
                ("current_generation", models.PositiveBigIntegerField(default=0)),
                ("events_full_snapshot_required", models.BooleanField(default=True)),
                ("reminders_full_snapshot_required", models.BooleanField(default=True)),
                (
                    "events_authorization",
                    models.CharField(
                        choices=[
                            ("not_determined", "Not determined"),
                            ("full_access", "Full access"),
                            ("write_only", "Write only"),
                            ("denied", "Denied"),
                            ("restricted", "Restricted"),
                            ("unavailable", "Unavailable"),
                        ],
                        default="not_determined",
                        max_length=20,
                    ),
                ),
                (
                    "reminders_authorization",
                    models.CharField(
                        choices=[
                            ("not_determined", "Not determined"),
                            ("full_access", "Full access"),
                            ("write_only", "Write only"),
                            ("denied", "Denied"),
                            ("restricted", "Restricted"),
                            ("unavailable", "Unavailable"),
                        ],
                        default="not_determined",
                        max_length=20,
                    ),
                ),
                ("events_last_complete_sync_at", models.DateTimeField(blank=True, null=True)),
                ("reminders_last_complete_sync_at", models.DateTimeField(blank=True, null=True)),
                ("events_window_start", models.DateTimeField(blank=True, null=True)),
                ("events_window_end", models.DateTimeField(blank=True, null=True)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datebook_gateways",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "datebook_gateways",
            },
        ),
        migrations.CreateModel(
            name="DeviceCommand",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("request_id", models.CharField(max_length=128)),
                ("request_digest", models.CharField(max_length=64)),
                (
                    "command_type",
                    models.CharField(
                        choices=[("calendar_create", "Calendar create"), ("reminder_create", "Reminder create")],
                        max_length=24,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("leased", "Leased"),
                            ("executing", "Executing"),
                            ("executed", "Executed"),
                            ("failed", "Failed"),
                            ("ambiguous", "Ambiguous"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("item_count", models.PositiveSmallIntegerField(default=1)),
                ("target_installation_id", models.CharField(max_length=64)),
                ("target_gateway_epoch", models.PositiveBigIntegerField()),
                ("destination_fingerprint", models.CharField(blank=True, default="", max_length=64)),
                ("destination_name", models.CharField(blank=True, default="", max_length=256)),
                ("display_text", models.CharField(blank=True, default="", max_length=512)),
                ("payload", models.JSONField(default=dict)),
                ("pii_receipts", models.JSONField(blank=True, default=dict)),
                ("lease_token", models.UUIDField(blank=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("execution_deadline_at", models.DateTimeField(blank=True, null=True)),
                (
                    "execution_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("executing", "Executing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("ambiguous", "Ambiguous"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "mirror_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("synced", "Synced"),
                            ("failed", "Failed"),
                            ("not_requested", "Not requested"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "safe_error",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("needs_authorization", "Needs authorization"),
                            ("list_not_found", "List not found"),
                            ("list_ambiguous", "List ambiguous"),
                            ("list_read_only", "List read only"),
                            ("calendar_not_found", "Calendar not found"),
                            ("calendar_ambiguous", "Calendar ambiguous"),
                            ("calendar_read_only", "Calendar read only"),
                            ("destination_changed", "Destination changed"),
                            ("invalid_payload", "Invalid payload"),
                            ("save_failed", "Save failed"),
                            ("unknown_safe_failure", "Unknown safe failure"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                ("result_id", models.CharField(blank=True, default="", max_length=64)),
                ("result_request_digest", models.CharField(blank=True, default="", max_length=64)),
                ("journaled_at", models.DateTimeField(blank=True, null=True)),
                ("result_identifiers", models.JSONField(blank=True, default=dict)),
                ("result_display", models.CharField(blank=True, default="", max_length=512)),
                ("expires_at", models.DateTimeField()),
                ("target_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datebook_commands",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "datebook_device_commands",
            },
        ),
        migrations.CreateModel(
            name="SyncRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("client_run_id", models.CharField(max_length=64)),
                ("server_now", models.DateTimeField()),
                ("event_window_start", models.DateTimeField()),
                ("event_window_end", models.DateTimeField()),
                ("base_generation", models.PositiveBigIntegerField()),
                ("gateway_epoch", models.PositiveBigIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("staged", "Staged"),
                            ("committed", "Committed"),
                            ("aborted", "Aborted"),
                        ],
                        default="open",
                        max_length=12,
                    ),
                ),
                ("events_in_scope", models.BooleanField(default=False)),
                (
                    "events_authorization",
                    models.CharField(
                        choices=[
                            ("not_determined", "Not determined"),
                            ("full_access", "Full access"),
                            ("write_only", "Write only"),
                            ("denied", "Denied"),
                            ("restricted", "Restricted"),
                            ("unavailable", "Unavailable"),
                        ],
                        default="not_determined",
                        max_length=20,
                    ),
                ),
                ("events_coverage_complete", models.BooleanField(default=False)),
                ("events_committable", models.BooleanField(default=False)),
                ("events_full_snapshot", models.BooleanField(default=False)),
                ("reminders_in_scope", models.BooleanField(default=False)),
                (
                    "reminders_authorization",
                    models.CharField(
                        choices=[
                            ("not_determined", "Not determined"),
                            ("full_access", "Full access"),
                            ("write_only", "Write only"),
                            ("denied", "Denied"),
                            ("restricted", "Restricted"),
                            ("unavailable", "Unavailable"),
                        ],
                        default="not_determined",
                        max_length=20,
                    ),
                ),
                ("reminders_coverage_complete", models.BooleanField(default=False)),
                ("reminders_committable", models.BooleanField(default=False)),
                ("reminders_full_snapshot", models.BooleanField(default=False)),
                ("events_manifest_digest", models.CharField(blank=True, default="", max_length=64)),
                ("events_item_count", models.PositiveIntegerField(blank=True, null=True)),
                ("reminders_manifest_digest", models.CharField(blank=True, default="", max_length=64)),
                ("reminders_item_count", models.PositiveIntegerField(blank=True, null=True)),
                ("events_absent_source_keys", models.JSONField(blank=True, default=list)),
                ("reminders_absent_source_keys", models.JSONField(blank=True, default=list)),
                ("commit_request_digest", models.CharField(blank=True, default="", max_length=64)),
                ("published_generation", models.PositiveBigIntegerField(blank=True, null=True)),
                ("requires_full_snapshot", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("staged_at", models.DateTimeField(blank=True, null=True)),
                ("committed_at", models.DateTimeField(blank=True, null=True)),
                ("aborted_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_runs",
                        to="datebook.datebookgateway",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datebook_sync_runs",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "datebook_sync_runs",
            },
        ),
        migrations.CreateModel(
            name="SyncPage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("page_index", models.PositiveIntegerField()),
                ("request_digest", models.CharField(max_length=64)),
                ("event_count", models.PositiveSmallIntegerField(default=0)),
                ("reminder_count", models.PositiveSmallIntegerField(default=0)),
                ("events_valid", models.BooleanField(default=True)),
                ("reminders_valid", models.BooleanField(default=True)),
                ("error_codes", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datebook_sync_pages",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="pages", to="datebook.syncrun"
                    ),
                ),
            ],
            options={
                "db_table": "datebook_sync_pages",
            },
        ),
        migrations.CreateModel(
            name="MirrorReminder",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source_key", models.CharField(max_length=64)),
                ("external_id", models.CharField(blank=True, default="", max_length=255)),
                ("series_id", models.CharField(blank=True, default="", max_length=255)),
                ("source_fingerprint", models.CharField(blank=True, default="", max_length=64)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("icloud", "iCloud"),
                            ("exchange", "Exchange"),
                            ("caldav", "CalDAV"),
                            ("subscribed", "Subscribed"),
                            ("birthdays", "Birthdays"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                ("source_title", models.CharField(blank=True, default="", max_length=256)),
                ("list_title", models.CharField(blank=True, default="", max_length=256)),
                ("is_read_only", models.BooleanField(default=False)),
                (
                    "authorization_status",
                    models.CharField(
                        choices=[
                            ("not_determined", "Not determined"),
                            ("full_access", "Full access"),
                            ("write_only", "Write only"),
                            ("denied", "Denied"),
                            ("restricted", "Restricted"),
                            ("unavailable", "Unavailable"),
                        ],
                        default="not_determined",
                        max_length=20,
                    ),
                ),
                (
                    "due_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("all_day", "All day"),
                            ("zoned", "Zoned"),
                            ("floating", "Floating"),
                        ],
                        default="",
                        max_length=12,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("zoned_due_at", models.DateTimeField(blank=True, null=True)),
                ("due_tz_id", models.CharField(blank=True, default="", max_length=63)),
                ("floating_due_date", models.DateField(blank=True, null=True)),
                ("floating_due_time", models.TimeField(blank=True, null=True)),
                ("title", models.CharField(blank=True, default="", max_length=256)),
                ("location", models.CharField(blank=True, default="", max_length=512)),
                ("notes", models.TextField(blank=True, default="")),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("priority", models.PositiveSmallIntegerField(default=0)),
                ("content_hash", models.CharField(blank=True, default="", max_length=64)),
                ("active", models.BooleanField(default=False)),
                ("first_seen_generation", models.PositiveBigIntegerField(default=0)),
                ("last_seen_generation", models.PositiveBigIntegerField(default=0)),
                ("inactive_generation", models.PositiveBigIntegerField(blank=True, null=True)),
                ("staged_page_index", models.PositiveIntegerField(blank=True, null=True)),
                ("staged_payload", models.JSONField(blank=True, default=dict)),
                ("pii_receipts", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datebook_reminders",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "staged_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staged_reminders",
                        to="datebook.syncrun",
                    ),
                ),
            ],
            options={
                "db_table": "datebook_mirror_reminders",
            },
        ),
        migrations.CreateModel(
            name="MirrorEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source_key", models.CharField(max_length=64)),
                ("external_id", models.CharField(blank=True, default="", max_length=255)),
                ("series_id", models.CharField(blank=True, default="", max_length=255)),
                ("source_fingerprint", models.CharField(blank=True, default="", max_length=64)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("icloud", "iCloud"),
                            ("exchange", "Exchange"),
                            ("caldav", "CalDAV"),
                            ("subscribed", "Subscribed"),
                            ("birthdays", "Birthdays"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                ("source_title", models.CharField(blank=True, default="", max_length=256)),
                ("calendar_title", models.CharField(blank=True, default="", max_length=256)),
                ("is_read_only", models.BooleanField(default=False)),
                (
                    "authorization_status",
                    models.CharField(
                        choices=[
                            ("not_determined", "Not determined"),
                            ("full_access", "Full access"),
                            ("write_only", "Write only"),
                            ("denied", "Denied"),
                            ("restricted", "Restricted"),
                            ("unavailable", "Unavailable"),
                        ],
                        default="not_determined",
                        max_length=20,
                    ),
                ),
                (
                    "time_kind",
                    models.CharField(
                        blank=True,
                        choices=[("all_day", "All day"), ("zoned", "Zoned"), ("floating", "Floating")],
                        default="",
                        max_length=12,
                    ),
                ),
                ("all_day_start_date", models.DateField(blank=True, null=True)),
                ("all_day_end_date_exclusive", models.DateField(blank=True, null=True)),
                ("zoned_start_at", models.DateTimeField(blank=True, null=True)),
                ("zoned_end_at", models.DateTimeField(blank=True, null=True)),
                ("tz_id", models.CharField(blank=True, default="", max_length=63)),
                ("floating_start_date", models.DateField(blank=True, null=True)),
                ("floating_start_time", models.TimeField(blank=True, null=True)),
                ("floating_end_date", models.DateField(blank=True, null=True)),
                ("floating_end_time", models.TimeField(blank=True, null=True)),
                ("title", models.CharField(blank=True, default="", max_length=256)),
                ("location", models.CharField(blank=True, default="", max_length=512)),
                ("notes", models.TextField(blank=True, default="")),
                ("is_recurring", models.BooleanField(default=False)),
                ("content_hash", models.CharField(blank=True, default="", max_length=64)),
                ("active", models.BooleanField(default=False)),
                ("first_seen_generation", models.PositiveBigIntegerField(default=0)),
                ("last_seen_generation", models.PositiveBigIntegerField(default=0)),
                ("inactive_generation", models.PositiveBigIntegerField(blank=True, null=True)),
                ("staged_page_index", models.PositiveIntegerField(blank=True, null=True)),
                ("staged_payload", models.JSONField(blank=True, default=dict)),
                ("pii_receipts", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="datebook_events", to="tenants.tenant"
                    ),
                ),
                (
                    "staged_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staged_events",
                        to="datebook.syncrun",
                    ),
                ),
            ],
            options={
                "db_table": "datebook_mirror_events",
            },
        ),
        migrations.AddIndex(
            model_name="datebookgateway",
            index=models.Index(fields=["tenant", "status"], name="datebook_gateway_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="datebookgateway",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")), fields=("tenant",), name="datebook_one_active_gateway"
            ),
        ),
        migrations.AddConstraint(
            model_name="datebookgateway",
            constraint=models.UniqueConstraint(
                fields=("tenant", "installation_id"), name="datebook_gateway_installation_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="datebookgateway",
            constraint=models.CheckConstraint(
                condition=models.Q(("gateway_epoch__gte", 1)), name="datebook_gateway_epoch_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="devicecommand",
            index=models.Index(fields=["tenant", "state", "created_at"], name="datebook_command_claim_idx"),
        ),
        migrations.AddIndex(
            model_name="devicecommand",
            index=models.Index(fields=["state", "lease_expires_at"], name="datebook_command_lease_idx"),
        ),
        migrations.AddIndex(
            model_name="devicecommand",
            index=models.Index(fields=["state", "execution_deadline_at"], name="datebook_command_exec_idx"),
        ),
        migrations.AddConstraint(
            model_name="devicecommand",
            constraint=models.UniqueConstraint(fields=("tenant", "request_id"), name="datebook_command_request_unique"),
        ),
        migrations.AddConstraint(
            model_name="devicecommand",
            constraint=models.CheckConstraint(
                condition=models.Q(("item_count__gte", 1), ("item_count__lte", 5)), name="datebook_command_item_cap"
            ),
        ),
        migrations.AddConstraint(
            model_name="devicecommand",
            constraint=models.CheckConstraint(
                condition=models.Q(("target_gateway_epoch__gte", 1)), name="datebook_command_epoch_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="devicecommand",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("execution_deadline_at__isnull", True),
                        ("execution_status", "pending"),
                        ("journaled_at__isnull", True),
                        ("lease_expires_at__isnull", True),
                        ("lease_token__isnull", True),
                        ("mirror_status", "pending"),
                        ("resolved_at__isnull", True),
                        ("result_id", ""),
                        ("safe_error", ""),
                        ("started_at__isnull", True),
                        ("state", "pending"),
                    ),
                    models.Q(
                        ("execution_deadline_at__isnull", True),
                        ("execution_status", "pending"),
                        ("journaled_at__isnull", True),
                        ("lease_expires_at__isnull", False),
                        ("lease_token__isnull", False),
                        ("mirror_status", "pending"),
                        ("resolved_at__isnull", True),
                        ("result_id", ""),
                        ("safe_error", ""),
                        ("started_at__isnull", True),
                        ("state", "leased"),
                    ),
                    models.Q(
                        ("execution_deadline_at__isnull", False),
                        ("execution_status", "executing"),
                        ("journaled_at__isnull", True),
                        ("lease_expires_at__isnull", False),
                        ("lease_token__isnull", False),
                        ("mirror_status", "pending"),
                        ("resolved_at__isnull", True),
                        ("result_id", ""),
                        ("safe_error", ""),
                        ("started_at__isnull", False),
                        ("state", "executing"),
                    ),
                    models.Q(
                        ("execution_status", "succeeded"),
                        ("journaled_at__isnull", False),
                        ("resolved_at__isnull", False),
                        ("safe_error", ""),
                        ("started_at__isnull", False),
                        ("state", "executed"),
                        models.Q(("result_id", ""), _negated=True),
                    ),
                    models.Q(
                        ("execution_status", "failed"),
                        ("journaled_at__isnull", False),
                        ("resolved_at__isnull", False),
                        ("started_at__isnull", False),
                        ("state", "failed"),
                        models.Q(("safe_error", ""), _negated=True),
                        models.Q(("result_id", ""), _negated=True),
                    ),
                    models.Q(
                        ("execution_status", "ambiguous"),
                        ("journaled_at__isnull", True),
                        ("resolved_at__isnull", False),
                        ("result_id", ""),
                        ("safe_error", ""),
                        ("started_at__isnull", False),
                        ("state", "ambiguous"),
                    ),
                    models.Q(
                        ("execution_deadline_at__isnull", True),
                        ("execution_status", "pending"),
                        ("journaled_at__isnull", True),
                        ("lease_expires_at__isnull", True),
                        ("lease_token__isnull", True),
                        ("mirror_status", "pending"),
                        ("resolved_at__isnull", False),
                        ("result_id", ""),
                        ("safe_error", ""),
                        ("started_at__isnull", True),
                        ("state__in", ["expired", "cancelled"]),
                    ),
                    _connector="OR",
                ),
                name="datebook_command_state_fields_legal",
            ),
        ),
        migrations.AddIndex(
            model_name="syncrun",
            index=models.Index(fields=["tenant", "state"], name="datebook_sync_state_idx"),
        ),
        migrations.AddIndex(
            model_name="syncrun",
            index=models.Index(fields=["gateway", "gateway_epoch"], name="datebook_sync_gateway_idx"),
        ),
        migrations.AddConstraint(
            model_name="syncrun",
            constraint=models.UniqueConstraint(
                fields=("tenant", "client_run_id"), name="datebook_sync_client_run_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="syncrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("event_window_end__gt", models.F("event_window_start"))),
                name="datebook_sync_event_window_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="syncrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("gateway_epoch__gte", 1)), name="datebook_sync_epoch_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="syncrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("aborted_at__isnull", True), ("committed_at__isnull", True), ("state__in", ["open", "staged"])
                    ),
                    models.Q(
                        ("committed_at__isnull", False), ("published_generation__isnull", False), ("state", "committed")
                    ),
                    models.Q(("aborted_at__isnull", False), ("committed_at__isnull", True), ("state", "aborted")),
                    _connector="OR",
                ),
                name="datebook_sync_state_fields_legal",
            ),
        ),
        migrations.AddIndex(
            model_name="syncpage",
            index=models.Index(fields=["tenant", "run"], name="datebook_sync_page_run_idx"),
        ),
        migrations.AddConstraint(
            model_name="syncpage",
            constraint=models.UniqueConstraint(fields=("run", "page_index"), name="datebook_sync_page_unique"),
        ),
        migrations.AddConstraint(
            model_name="syncpage",
            constraint=models.CheckConstraint(
                condition=models.Q(("event_count__lte", 50), ("reminder_count__lte", 50)),
                name="datebook_sync_page_caps",
            ),
        ),
        migrations.AddIndex(
            model_name="mirrorreminder",
            index=models.Index(fields=["tenant", "active"], name="datebook_reminder_active_idx"),
        ),
        migrations.AddIndex(
            model_name="mirrorreminder",
            index=models.Index(fields=["tenant", "staged_run"], name="datebook_reminder_stage_idx"),
        ),
        migrations.AddIndex(
            model_name="mirrorreminder",
            index=models.Index(fields=["tenant", "completed"], name="datebook_reminder_done_idx"),
        ),
        migrations.AddConstraint(
            model_name="mirrorreminder",
            constraint=models.UniqueConstraint(fields=("tenant", "source_key"), name="datebook_reminder_source_unique"),
        ),
        migrations.AddConstraint(
            model_name="mirrorreminder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("content_hash", ""),
                    models.Q(
                        ("due_date__isnull", True),
                        ("due_kind", "none"),
                        ("due_tz_id", ""),
                        ("floating_due_date__isnull", True),
                        ("floating_due_time__isnull", True),
                        ("zoned_due_at__isnull", True),
                    ),
                    models.Q(
                        ("due_date__isnull", False),
                        ("due_kind", "all_day"),
                        ("due_tz_id", ""),
                        ("floating_due_date__isnull", True),
                        ("floating_due_time__isnull", True),
                        ("zoned_due_at__isnull", True),
                    ),
                    models.Q(
                        ("due_date__isnull", True),
                        ("due_kind", "zoned"),
                        ("floating_due_date__isnull", True),
                        ("floating_due_time__isnull", True),
                        ("zoned_due_at__isnull", False),
                        models.Q(("due_tz_id", ""), _negated=True),
                    ),
                    models.Q(
                        ("due_date__isnull", True),
                        ("due_kind", "floating"),
                        ("due_tz_id", ""),
                        ("floating_due_date__isnull", False),
                        ("floating_due_time__isnull", False),
                        ("zoned_due_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="datebook_reminder_tagged_due",
            ),
        ),
        migrations.AddConstraint(
            model_name="mirrorreminder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("active", False), ("content_hash", "")),
                    models.Q(("content_hash", ""), _negated=True),
                    _connector="OR",
                ),
                name="datebook_reminder_active_materialized",
            ),
        ),
        migrations.AddConstraint(
            model_name="mirrorreminder",
            constraint=models.CheckConstraint(
                condition=models.Q(("priority__lte", 9)), name="datebook_reminder_priority_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="mirrorreminder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("content_hash", ""),
                    models.Q(("completed", True), ("completed_at__isnull", False)),
                    models.Q(("completed", False), ("completed_at__isnull", True)),
                    _connector="OR",
                ),
                name="datebook_reminder_completion_time",
            ),
        ),
        migrations.AddIndex(
            model_name="mirrorevent",
            index=models.Index(fields=["tenant", "active"], name="datebook_event_active_idx"),
        ),
        migrations.AddIndex(
            model_name="mirrorevent",
            index=models.Index(fields=["tenant", "staged_run"], name="datebook_event_stage_idx"),
        ),
        migrations.AddIndex(
            model_name="mirrorevent",
            index=models.Index(fields=["tenant", "zoned_start_at"], name="datebook_event_zoned_idx"),
        ),
        migrations.AddIndex(
            model_name="mirrorevent",
            index=models.Index(fields=["tenant", "all_day_start_date"], name="datebook_event_day_idx"),
        ),
        migrations.AddConstraint(
            model_name="mirrorevent",
            constraint=models.UniqueConstraint(fields=("tenant", "source_key"), name="datebook_event_source_unique"),
        ),
        migrations.AddConstraint(
            model_name="mirrorevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("content_hash", ""),
                    models.Q(
                        ("all_day_end_date_exclusive__isnull", False),
                        ("all_day_start_date__isnull", False),
                        ("floating_end_date__isnull", True),
                        ("floating_end_time__isnull", True),
                        ("floating_start_date__isnull", True),
                        ("floating_start_time__isnull", True),
                        ("time_kind", "all_day"),
                        ("tz_id", ""),
                        ("zoned_end_at__isnull", True),
                        ("zoned_start_at__isnull", True),
                    ),
                    models.Q(
                        ("all_day_end_date_exclusive__isnull", True),
                        ("all_day_start_date__isnull", True),
                        ("floating_end_date__isnull", True),
                        ("floating_end_time__isnull", True),
                        ("floating_start_date__isnull", True),
                        ("floating_start_time__isnull", True),
                        ("time_kind", "zoned"),
                        ("zoned_end_at__isnull", False),
                        ("zoned_start_at__isnull", False),
                        models.Q(("tz_id", ""), _negated=True),
                    ),
                    models.Q(
                        ("all_day_end_date_exclusive__isnull", True),
                        ("all_day_start_date__isnull", True),
                        ("floating_end_date__isnull", False),
                        ("floating_end_time__isnull", False),
                        ("floating_start_date__isnull", False),
                        ("floating_start_time__isnull", False),
                        ("time_kind", "floating"),
                        ("tz_id", ""),
                        ("zoned_end_at__isnull", True),
                        ("zoned_start_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="datebook_event_tagged_time",
            ),
        ),
        migrations.AddConstraint(
            model_name="mirrorevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("active", False), ("content_hash", "")),
                    models.Q(("content_hash", ""), _negated=True),
                    _connector="OR",
                ),
                name="datebook_event_active_materialized",
            ),
        ),
        migrations.AddConstraint(
            model_name="mirrorevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("content_hash", ""),
                    models.Q(
                        ("all_day_end_date_exclusive__gt", models.F("all_day_start_date")), ("time_kind", "all_day")
                    ),
                    models.Q(("time_kind", "zoned"), ("zoned_end_at__gt", models.F("zoned_start_at"))),
                    models.Q(("floating_end_date__gt", models.F("floating_start_date")), ("time_kind", "floating")),
                    models.Q(
                        ("floating_end_date", models.F("floating_start_date")),
                        ("floating_end_time__gt", models.F("floating_start_time")),
                        ("time_kind", "floating"),
                    ),
                    _connector="OR",
                ),
                name="datebook_event_time_order",
            ),
        ),
    ]
