# Generated by Django 6.0.7 on 2026-08-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datebook", "0001_datebook_b1"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicecommand",
            name="notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
