# Generated by Django 6.0.7 on 2026-08-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datebook", "0002_devicecommand_notified_at"),
        ("tenants", "0154_relock_after_datebook_b2a"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="mirrorevent",
            name="datebook_event_time_order",
        ),
        migrations.AddConstraint(
            model_name="mirrorevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("content_hash", ""),
                    models.Q(
                        ("all_day_end_date_exclusive__gt", models.F("all_day_start_date")), ("time_kind", "all_day")
                    ),
                    models.Q(("time_kind", "zoned"), ("zoned_end_at__gte", models.F("zoned_start_at"))),
                    models.Q(("floating_end_date__gt", models.F("floating_start_date")), ("time_kind", "floating")),
                    models.Q(
                        ("floating_end_date", models.F("floating_start_date")),
                        ("floating_end_time__gte", models.F("floating_start_time")),
                        ("time_kind", "floating"),
                    ),
                    _connector="OR",
                ),
                name="datebook_event_time_order",
            ),
        ),
    ]
