# Generated by Django 6.0.7 on 2026-08-14 11:13

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datebook", "0003_accept_zero_duration_timed_events"),
        ("tenants", "0155_relock_after_datebook_zero_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatebookDestinationDefault",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "entity_type",
                    models.CharField(choices=[("calendar", "Calendar"), ("reminder", "Reminder")], max_length=16),
                ),
                ("name", models.CharField(max_length=256)),
                ("fingerprint", models.CharField(max_length=64)),
                ("target_installation_id", models.CharField(max_length=64)),
                ("gateway_epoch", models.PositiveBigIntegerField()),
                ("pii_receipts", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datebook_destination_defaults",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "datebook_destination_defaults",
                "indexes": [models.Index(fields=["tenant", "entity_type"], name="datebook_dest_default_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("tenant", "entity_type"), name="datebook_dest_default_unique"),
                    models.CheckConstraint(
                        condition=models.Q(("gateway_epoch__gte", 1)), name="datebook_dest_default_epoch"
                    ),
                ],
            },
        ),
    ]
