# Generated by Django 6.0.7 on 2026-08-24 06:44

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datebook", "0004_datebook_approval_ux"),
        ("tenants", "0157_relock_after_tool_telemetry"),
    ]

    operations = [
        migrations.AddField(
            model_name="mirrorevent",
            name="calendar_fingerprint",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="mirrorreminder",
            name="calendar_fingerprint",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.CreateModel(
            name="CalendarContext",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "entity_scope",
                    models.CharField(choices=[("event", "Event"), ("reminder", "Reminder")], max_length=16),
                ),
                ("calendar_fingerprint", models.CharField(max_length=64)),
                ("included", models.BooleanField(default=True)),
                ("container_title", models.CharField(blank=True, default="", max_length=256)),
                ("source_title", models.CharField(blank=True, default="", max_length=256)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("icloud", "iCloud"),
                            ("exchange", "Exchange"),
                            ("caldav", "CalDAV"),
                            ("subscribed", "Subscribed"),
                            ("birthdays", "Birthdays"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                ("context_note", models.CharField(blank=True, default="", max_length=240)),
                ("pii_receipts", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datebook_calendar_contexts",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "datebook_calendar_contexts",
                "indexes": [models.Index(fields=["tenant", "entity_scope"], name="datebook_context_scope_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "entity_scope", "calendar_fingerprint"),
                        name="datebook_calendar_context_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("included", True), models.Q(("container_title", ""), ("source_title", "")), _connector="OR"
                        ),
                        name="datebook_context_excluded_titles_empty",
                    ),
                ],
            },
        ),
    ]
