# Generated by Django 5.1.15 on 2026-02-12 05:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0005_remove_celery_beat_schedules'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('mood', models.CharField(max_length=255)),
                ('energy', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=16)),
                ('wins', models.JSONField(blank=True, default=list)),
                ('challenges', models.JSONField(blank=True, default=list)),
                ('reflection', models.TextField(blank=True, default='')),
                ('raw_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='tenants.tenant')),
            ],
            options={
                'db_table': 'journal_entries',
                'indexes': [models.Index(fields=['tenant', 'date'], name='journal_ent_tenant__505b56_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('mood_summary', models.TextField()),
                ('top_wins', models.JSONField(blank=True, default=list)),
                ('top_challenges', models.JSONField(blank=True, default=list)),
                ('lessons', models.JSONField(blank=True, default=list)),
                ('week_rating', models.CharField(choices=[('thumbs-up', 'Thumbs Up'), ('thumbs-down', 'Thumbs Down'), ('meh', 'Meh')], max_length=16)),
                ('intentions_next_week', models.JSONField(blank=True, default=list)),
                ('raw_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reviews', to='tenants.tenant')),
            ],
            options={
                'db_table': 'weekly_reviews',
                'indexes': [models.Index(fields=['tenant', 'week_start', 'week_end'], name='weekly_revi_tenant__ff5ebd_idx')],
            },
        ),
    ]
