from django.db import migrations, models
import django.db.models.deletion
import uuid


def seed_default_note_templates(apps, schema_editor):
    Tenant = apps.get_model('tenants', 'Tenant')
    NoteTemplate = apps.get_model('journal', 'NoteTemplate')
    DailyNote = apps.get_model('journal', 'DailyNote')

    db_alias = schema_editor.connection.alias

    default_sections = [
        {
            'slug': 'morning-report',
            'title': 'Morning Report',
            'content': '*Running updates generated by your agent.*',
            'source': 'shared',
        },
        {
            'slug': 'log',
            'title': 'Log',
            'content': '*Add quick timestamped notes throughout the day.*',
            'source': 'shared',
        },
        {
            'slug': 'evening-check-in',
            'title': 'Evening Check-in',
            'content': '*User fills this in each evening.*',
            'source': 'shared',
        },
    ]

    for tenant in Tenant.objects.using(db_alias).all():
        template, created = NoteTemplate.objects.using(db_alias).get_or_create(
            tenant_id=tenant.id,
            slug='default',
            defaults={
                'name': 'Default',
                'sections': default_sections,
                'is_default': True,
                'source': 'shared',
            },
        )
        if created:
            continue

        template.sections = default_sections
        template.is_default = True
        template.source = 'shared'
        template.save(update_fields=['sections', 'is_default', 'source'])

    for note in DailyNote.objects.using(db_alias).all():
        template = NoteTemplate.objects.using(db_alias).filter(tenant_id=note.tenant_id, is_default=True).first()
        if template is not None and note.template_id is None:
            note.template_id = template.id
            note.save(update_fields=['template'])


def reverse_default_note_templates(apps, schema_editor):
    NoteTemplate = apps.get_model('journal', 'NoteTemplate')
    db_alias = schema_editor.connection.alias
    NoteTemplate.objects.using(db_alias).filter(slug='default').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_add_daily_notes_and_long_term_memory'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='note_templates',
                        to='tenants.tenant',
                    ),
                ),
                ('slug', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('sections', models.JSONField(default=list)),
                ('is_default', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('agent', 'Agent'), ('human', 'Human'), ('shared', 'Shared')], default='shared', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'note_templates',
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='dailynote',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='journal.notetemplate'),
        ),
        migrations.RunPython(seed_default_note_templates, reverse_default_note_templates),
    ]
