# Generated by Django 5.1.15 on 2026-02-16 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_migrate_to_documents'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='document',
            new_name='journal_doc_tenant__efec3b_idx',
            old_name='journal_doc_tenant_kind_idx',
        ),
    ]
