# Generated by Django 5.1.15 on 2026-02-19
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_rename_journal_doc_tenant_kind_idx_journal_doc_tenant__efec3b_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
