# Generated by Django 5.1.15 on 2026-03-02 10:49

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_pending_extraction'),
        ('lessons', '0001_initial'),  # VectorExtension() creates pgvector extension
        ('tenants', '0016_add_pending_deletion_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField()),
                ('text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('source_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='journal.document')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_chunks', to='tenants.tenant')),
            ],
            options={
                'db_table': 'journal_document_chunks',
                'indexes': [models.Index(fields=['tenant', 'source_date'], name='journal_doc_tenant__550a06_idx')],
                'unique_together': {('document', 'chunk_index')},
            },
        ),
    ]
