# Generated by Django 5.1.15 on 2026-04-07 11:46

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_pendingextraction_undo_fields'),
        ('tenants', '0037_collapse_tiers_remove_byok'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=60)),
                ('description', models.TextField(blank=True, default='', help_text='What topics this workspace covers. Used for routing classification.')),
                ('description_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, help_text='Embedding of description for message classification.', null=True)),
                ('is_default', models.BooleanField(default=False, help_text="The 'General' catch-all workspace. Cannot be deleted.")),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='tenants.tenant')),
            ],
            options={
                'db_table': 'journal_workspaces',
                'unique_together': {('tenant', 'slug')},
            },
        ),
    ]
