# Generated by Django 5.1.15 on 2026-05-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0014_session_project_identity"),
        ("tenants", "0052_welcomes_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="processed_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Set when the assistant has distilled this session into primitives. NULL = pending.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="processed_summary",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Free-form record of what the assistant created during distillation: task ids, journal doc ids, memory updates, skip reason, etc.",
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["tenant", "processed_at"], name="journal_ses_tenant__9c3eda_idx"),
        ),
    ]
