# Generated by Django 5.1.15 on 2026-05-20 02:01

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insights", "0001_initial"),
        ("journal", "0017_cleanup_garbage_journal_documents"),
        ("tenants", "0065_goal_task_typed_lifecycle"),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=256)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "pillar",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("gravity", "Gravity"),
                            ("fuel", "Fuel"),
                            ("core", "Core"),
                            ("lessons", "Lessons"),
                            ("constellation", "Constellation"),
                            ("horizons", "Horizons"),
                            ("journal", "Journal"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                ("target", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("achieved", "Achieved"),
                            ("abandoned", "Abandoned"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("target_date", models.DateField(blank=True, null=True)),
                ("achieved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "migrated_from_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="migrated_goals",
                        to="journal.document",
                    ),
                ),
                (
                    "parent_goal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_goals",
                        to="journal.goal",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="goals", to="tenants.tenant"
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goals",
                        to="insights.topicregistry",
                    ),
                ),
            ],
            options={
                "db_table": "journal_goals",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=256)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "pillar",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("gravity", "Gravity"),
                            ("fuel", "Fuel"),
                            ("core", "Core"),
                            ("lessons", "Lessons"),
                            ("constellation", "Constellation"),
                            ("horizons", "Horizons"),
                            ("journal", "Journal"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("done", "Done"),
                            ("skipped", "Skipped"),
                            ("deferred", "Deferred"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("related_ref", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "migrated_from_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="migrated_tasks",
                        to="journal.document",
                    ),
                ),
                (
                    "parent_goal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="journal.goal",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "journal_tasks",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(fields=["tenant", "status"], name="journal_goa_tenant__678ea7_idx"),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(fields=["tenant", "pillar", "status"], name="journal_goa_tenant__62abd2_idx"),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(fields=["tenant", "target_date"], name="journal_goa_tenant__e6a1be_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["tenant", "status"], name="journal_tas_tenant__49e34c_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["tenant", "pillar", "status"], name="journal_tas_tenant__1fd73d_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["tenant", "due_date"], name="journal_tas_tenant__c70be3_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["tenant", "parent_goal"], name="journal_tas_tenant__fc80d5_idx"),
        ),
    ]
