# Generated by Django 5.1.15 on 2026-05-24 03:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0018_goal_task_typed_lifecycle"),
        ("tenants", "0069_kimi_to_deepseek"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingextraction",
            name="goal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pending_extractions",
                to="journal.goal",
            ),
        ),
        migrations.AddField(
            model_name="pendingextraction",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pending_extractions",
                to="journal.task",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="parent_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtasks",
                to="journal.task",
            ),
        ),
        migrations.CreateModel(
            name="PendingTaskAction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("task_complete", "Task complete"),
                            ("task_progress", "Task progress"),
                            ("task_skip", "Task skip"),
                            ("task_defer", "Task defer"),
                            ("subtask_create", "Subtask create"),
                            ("goal_achieve", "Goal achieve"),
                            ("goal_abandon", "Goal abandon"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("applied", "Applied"), ("undone", "Undone"), ("failed", "Failed")],
                        default="applied",
                        max_length=16,
                    ),
                ),
                ("evidence", models.TextField(blank=True, default="")),
                ("source_date", models.DateField()),
                ("before_state", models.JSONField(blank=True, null=True)),
                ("telegram_message_id", models.CharField(blank=True, default="", max_length=64)),
                ("line_message_token", models.CharField(blank=True, default="", max_length=128)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "goal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_actions",
                        to="journal.goal",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_actions",
                        to="journal.task",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_task_actions",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "journal_pending_task_actions",
                "ordering": ["-applied_at"],
                "indexes": [
                    models.Index(fields=["tenant", "status"], name="journal_pen_tenant__b03f5c_idx"),
                    models.Index(fields=["tenant", "source_date"], name="journal_pen_tenant__c3f734_idx"),
                    models.Index(fields=["tenant", "kind", "status"], name="journal_pen_tenant__62096d_idx"),
                ],
            },
        ),
    ]
