# Generated by Django 5.1.15 on 2026-07-02 14:45

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0020_cleanup_nan_daily_stubs"),
        ("tenants", "0091_tenant_site_config_tenant_site_publishing_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingextraction",
            name="kind",
            field=models.CharField(
                choices=[("lesson", "Lesson"), ("goal", "Goal"), ("task", "Task"), ("purpose", "Purpose hypothesis")],
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="Purpose",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("statement", models.TextField()),
                ("pillars", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("confirmed", "Confirmed"),
                            ("evolving", "Evolving"),
                            ("retired", "Retired"),
                        ],
                        default="proposed",
                        max_length=16,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[("assistant_proposed", "Assistant proposed"), ("user_created", "User created")],
                        default="user_created",
                        max_length=24,
                    ),
                ),
                ("evidence", models.JSONField(blank=True, default=list)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="purposes", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "journal_purposes",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="goal",
            name="purpose",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="goals",
                to="journal.purpose",
            ),
        ),
        migrations.AddIndex(
            model_name="purpose",
            index=models.Index(fields=["tenant", "status"], name="journal_pur_tenant__44d6e3_idx"),
        ),
        # Public-schema lockdown invariant — every owned public table must have
        # RLS enabled (see tenants/0059 + tenants/0066, journal/0019, and the
        # ``test_rls_enabled_on_owned_public_tables`` guard). No policies are
        # defined here: the Django backend connects as the table owner and
        # bypasses RLS by default; the anon role PostgREST exposes has no
        # SELECT/INSERT/UPDATE grant on this table.
        migrations.RunSQL(
            sql="ALTER TABLE journal_purposes ENABLE ROW LEVEL SECURITY;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
