# Generated by Django 5.1.15 on 2026-07-09 13:27

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0021_purpose_north_star"),
        ("router", "0022_buffered_message_minimal_envelope_help_text"),
        ("tenants", "0110_tenant_document_ingestion_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentIngestion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("client_msg_id", models.CharField(blank=True, default="", max_length=64)),
                ("original_filename", models.CharField(max_length=255)),
                ("content_hash", models.CharField(blank=True, default="", max_length=64)),
                ("workspace_path", models.CharField(blank=True, default="", max_length=255)),
                ("uploaded_at", models.DateTimeField()),
                ("file_expires_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("kept", "Kept"),
                            ("partially_removed", "Partially removed"),
                            ("removed", "Removed"),
                            ("expired", "Expired"),
                        ],
                        default="kept",
                        max_length=24,
                    ),
                ),
                ("agreed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="doc_ingestions", to="tenants.tenant"
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doc_ingestions",
                        to="router.chatthread",
                    ),
                ),
            ],
            options={
                "db_table": "journal_document_ingestions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentIngestionArtifact",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("kind", models.CharField(max_length=32)),
                ("object_type", models.CharField(max_length=64)),
                ("object_id", models.CharField(max_length=128)),
                ("destination", models.CharField(blank=True, default="", max_length=255)),
                ("content_excerpt", models.TextField(blank=True, default="")),
                ("removal_strategy", models.CharField(blank=True, default="", max_length=32)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ingestion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="journal.documentingestion",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doc_ingestion_artifacts",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "journal_document_ingestion_artifacts",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="documentingestion",
            index=models.Index(fields=["tenant", "status"], name="journal_doc_tenant__9e2d05_idx"),
        ),
        migrations.AddIndex(
            model_name="documentingestion",
            index=models.Index(fields=["tenant", "created_at"], name="journal_doc_tenant__906db0_idx"),
        ),
        migrations.AddConstraint(
            model_name="documentingestion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "kept"), _negated=True), ("agreed_at__isnull", False), _connector="OR"
                ),
                name="doc_ingestion_kept_requires_agreed_at",
            ),
        ),
        migrations.AddIndex(
            model_name="documentingestionartifact",
            index=models.Index(fields=["tenant", "ingestion"], name="journal_doc_tenant__8b337f_idx"),
        ),
        migrations.AddIndex(
            model_name="documentingestionartifact",
            index=models.Index(fields=["tenant", "object_type"], name="journal_doc_tenant__da22b1_idx"),
        ),
        # Public-schema lockdown invariant — every owned public table must have
        # RLS enabled (see tenants/0059 + tenants/0066 and the
        # ``test_rls_enabled_on_owned_public_tables`` guard). No policies: the
        # Django backend connects as the table owner and bypasses RLS; the anon
        # role PostgREST exposes has no grant on these tables. A fresh tenants
        # relock migration depends on this one so a topo-sort shift can't push a
        # prior relock ahead of these tables.
        migrations.RunSQL(
            sql="ALTER TABLE journal_document_ingestions ENABLE ROW LEVEL SECURITY;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE journal_document_ingestion_artifacts ENABLE ROW LEVEL SECURITY;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
