# Generated by Django 5.1.15 on 2026-07-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0022_document_ingestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentingestion",
            name="source_kind",
            field=models.CharField(
                choices=[("upload", "Upload"), ("email", "Email"), ("calendar", "Calendar"), ("reddit", "Reddit")],
                default="upload",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="documentingestion",
            name="source_ref",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="documentingestion",
            name="file_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
