# Generated by Django 6.0.7 on 2026-07-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0023_documentingestion_source_kind_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailynote",
            name="markdown_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="text_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="documentingestion",
            name="original_filename_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="documentingestionartifact",
            name="content_excerpt_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="description_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="title_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="pendingextraction",
            name="text_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="pendingtaskaction",
            name="evidence_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="purpose",
            name="evidence_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="purpose",
            name="statement_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="accomplishments_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="blockers_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="next_steps_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="summary_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="description_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="title_enc",
            field=models.BinaryField(null=True),
        ),
    ]
