# Generated by Django 6.0.7 on 2026-08-07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0024_dailynote_markdown_enc_documentchunk_text_enc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="pii_receipts",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="task",
            name="pii_receipts",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
