# Generated by Django 6.0.7 on 2026-08-07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0025_goal_task_pii_receipts"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingtaskaction",
            name="pii_receipts",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
