# Generated by Django 6.0.7 on 2026-08-08 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0026_pendingtaskaction_pii_receipts"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="pii_receipts",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="pii_receipts",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="documentingestion",
            name="pii_receipts",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="documentingestionartifact",
            name="pii_receipts",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
