# Generated by Django 6.0.7 on 2026-09-20 06:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0030_sanitize_document_slugs"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="energy_score",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)],
            ),
        ),
    ]
