"""Neighborhood console URLs — mounted at /api/v1/friends/ (config/urls.py)."""

from django.urls import path

from .views import (
    AbsorbedListView,
    AbsorbedPurgeView,
    AdoptShareView,
    BlockedListView,
    CircleDetailView,
    CircleInviteCodeView,
    CircleJoinView,
    CircleLeaveView,
    CircleMembersView,
    CircleRemoveView,
    CirclesView,
    ConsentView,
    FriendGalaxyView,
    GoalActionApproveView,
    GoalActionRejectView,
    GoalActionsView,
    InviteClaimView,
    InviteCreateView,
    InviteDetailView,
    MissionDeclineView,
    MissionDetailView,
    MissionJoinView,
    MissionLeaveView,
    MissionsView,
    MissionTasksView,
    MissionUpdatesView,
    NeighborhoodHomeView,
    NeighborhoodView,
    NetworkCapabilitiesView,
    PendingSharesView,
    ProfileView,
    ReportView,
    ShareApproveView,
    SharePreviewView,
    ShareRejectView,
    SkyRosterView,
    SkyView,
    ThreadMembershipView,
    ThreadMessagesView,
    ThreadReadView,
    ThreadsView,
    UnblockView,
    UnfriendView,
    WaveCreateView,
    WaveRespondView,
    WormholesView,
    WormholeVisitedView,
)

urlpatterns = [
    path("", NeighborhoodView.as_view(), name="friends-neighborhood"),
    path("network/", NetworkCapabilitiesView.as_view(), name="friends-network-capabilities"),
    path("home/", NeighborhoodHomeView.as_view(), name="friends-home"),
    path("blocked/", BlockedListView.as_view(), name="friends-blocked"),
    path("consent/", ConsentView.as_view(), name="friends-consent"),
    path("profile/", ProfileView.as_view(), name="friends-profile"),
    path("waves/", WaveCreateView.as_view(), name="friends-wave-create"),
    path(
        "waves/<uuid:friendship_id>/accept/",
        WaveRespondView.as_view(),
        {"action": "accept"},
        name="friends-wave-accept",
    ),
    path(
        "waves/<uuid:friendship_id>/decline/",
        WaveRespondView.as_view(),
        {"action": "decline"},
        name="friends-wave-decline",
    ),
    path(
        "waves/<uuid:friendship_id>/block/", WaveRespondView.as_view(), {"action": "block"}, name="friends-wave-block"
    ),
    path("shares/preview/", SharePreviewView.as_view(), name="friends-share-preview"),
    path("shares/pending/", PendingSharesView.as_view(), name="friends-shares-pending"),
    path("shares/<uuid:pending_share_id>/approve/", ShareApproveView.as_view(), name="friends-share-approve"),
    path("shares/<uuid:pending_share_id>/reject/", ShareRejectView.as_view(), name="friends-share-reject"),
    path("shares/<uuid:shared_lesson_id>/adopt/", AdoptShareView.as_view(), name="friends-share-adopt"),
    path("absorbed/", AbsorbedListView.as_view(), name="friends-absorbed"),
    path("absorbed/<uuid:absorbed_item_id>/purge/", AbsorbedPurgeView.as_view(), name="friends-absorbed-purge"),
    # Friend chat (1:1)
    path("threads/", ThreadsView.as_view(), name="friends-threads"),
    path("threads/<uuid:thread_id>/messages/", ThreadMessagesView.as_view(), name="friends-thread-messages"),
    path("threads/<uuid:thread_id>/read/", ThreadReadView.as_view(), name="friends-thread-read"),
    path("threads/<uuid:thread_id>/membership/", ThreadMembershipView.as_view(), name="friends-thread-membership"),
    # Missions (shared goals + crew projection)
    path("missions/", MissionsView.as_view(), name="friends-missions"),
    path("missions/<uuid:mission_id>/", MissionDetailView.as_view(), name="friends-mission-detail"),
    path("missions/<uuid:mission_id>/join/", MissionJoinView.as_view(), name="friends-mission-join"),
    path("missions/<uuid:mission_id>/decline/", MissionDeclineView.as_view(), name="friends-mission-decline"),
    path("missions/<uuid:mission_id>/leave/", MissionLeaveView.as_view(), name="friends-mission-leave"),
    path("missions/<uuid:mission_id>/updates/", MissionUpdatesView.as_view(), name="friends-mission-updates"),
    path("missions/<uuid:mission_id>/tasks/", MissionTasksView.as_view(), name="friends-mission-tasks"),
    path("mission-actions/", GoalActionsView.as_view(), name="friends-mission-actions"),
    path(
        "mission-actions/<uuid:action_id>/approve/",
        GoalActionApproveView.as_view(),
        name="friends-mission-action-approve",
    ),
    path(
        "mission-actions/<uuid:action_id>/reject/", GoalActionRejectView.as_view(), name="friends-mission-action-reject"
    ),
    # Circles (groups on edges). `circles/join/` is a literal, so it wins over
    # the `circles/<uuid:circle_id>/` routes below (join is never a UUID anyway).
    path("circles/", CirclesView.as_view(), name="friends-circles"),
    path("circles/join/", CircleJoinView.as_view(), name="friends-circle-join"),
    path("circles/<uuid:circle_id>/", CircleDetailView.as_view(), name="friends-circle-detail"),
    path("circles/<uuid:circle_id>/members/", CircleMembersView.as_view(), name="friends-circle-members"),
    path("circles/<uuid:circle_id>/leave/", CircleLeaveView.as_view(), name="friends-circle-leave"),
    path("circles/<uuid:circle_id>/remove/", CircleRemoveView.as_view(), name="friends-circle-remove"),
    path("circles/<uuid:circle_id>/invite-code/", CircleInviteCodeView.as_view(), name="friends-circle-invite-code"),
    # Moderation (reporter-side hide; design §10)
    path("report/", ReportView.as_view(), name="friends-report"),
    # Wormholes / warp (read-only) + "my sky" curation. The <friendship_id>/galaxy/,
    # /visited/, /sky/ routes sit ABOVE the bare <friendship_id>/ unfriend catch-all
    # so they win; `sky/` (the roster GET) is a literal (not a UUID), also above it.
    path("wormholes/", WormholesView.as_view(), name="friends-wormholes"),
    path("sky/", SkyRosterView.as_view(), name="friends-sky"),
    path("<uuid:friendship_id>/galaxy/", FriendGalaxyView.as_view(), name="friends-galaxy"),
    path("<uuid:friendship_id>/visited/", WormholeVisitedView.as_view(), name="friends-wormhole-visited"),
    path("<uuid:friendship_id>/sky/", SkyView.as_view(), name="friends-sky-edge"),
    path("<uuid:friendship_id>/unblock/", UnblockView.as_view(), name="friends-unblock"),
    path("invites/", InviteCreateView.as_view(), name="friends-invite-create"),
    path("invites/<str:token>/claim/", InviteClaimView.as_view(), name="friends-invite-claim"),
    path("invites/<str:token>/", InviteDetailView.as_view(), name="friends-invite-detail"),
    path("<uuid:friendship_id>/", UnfriendView.as_view(), name="friends-unfriend"),
]
