# Generated by Django 5.1.15 on 2026-02-08 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsession',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='memoryitem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_items', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='message',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agents.agentsession'),
        ),
        migrations.AlterUniqueTogether(
            name='memoryitem',
            unique_together={('tenant', 'key')},
        ),
    ]
