# Generated by Django 6.0.7 on 2026-08-06 07:47

import uuid

import django.db.models.deletion
from django.db import migrations, models

TABLES = (
    "transcripts_transcriptevent",
    "transcripts_transcriptcapturequarantine",
    "transcripts_transcriptindexoutbox",
)

_GUC_TENANT = "nullif(current_setting('app.tenant_id', true), '')::uuid"
_GUC_SERVICE = "coalesce(current_setting('app.service_role', true), '') = 'true'"

APPLY_SQL = """
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_user') THEN
    CREATE ROLE app_user NOLOGIN;
  END IF;
END
$$;
""" + "\n".join(
    f"""
ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;
ALTER TABLE {table} FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS transcripts_{table}_tenant ON {table};
CREATE POLICY transcripts_{table}_tenant ON {table} TO app_user
USING (
    {_GUC_SERVICE}
    OR tenant_id = {_GUC_TENANT}
)
WITH CHECK (
    {_GUC_SERVICE}
    OR tenant_id = {_GUC_TENANT}
);
"""
    for table in TABLES
)

REVERSE_SQL = "\n".join(
    f"""
DROP POLICY IF EXISTS transcripts_{table}_tenant ON {table};
ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY;
"""
    for table in TABLES
)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0144_tenant_recall_capture_birthday_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranscriptCaptureQuarantine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("ios_queued", "iOS queued"),
                            ("ios_ondevice", "iOS on-device"),
                            ("telegram_poller", "Telegram poller"),
                            ("telegram_webhook", "Telegram webhook"),
                            ("line", "LINE"),
                            ("buffered", "Buffered"),
                            ("assistant_reply", "Assistant reply"),
                            ("proactive", "Proactive"),
                        ],
                        max_length=24,
                    ),
                ),
                ("source_event_id", models.CharField(max_length=255)),
                ("turn_id", models.UUIDField(blank=True, null=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("ios", "iOS"), ("telegram", "Telegram"), ("line", "LINE")], max_length=16
                    ),
                ),
                ("thread_key", models.CharField(blank=True, default="", max_length=255)),
                ("occurred_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.CharField(max_length=64)),
                ("repair_ref", models.CharField(blank=True, default="", max_length=255)),
                ("permanent_loss", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcript_capture_quarantines",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "source_type", "source_event_id"), name="uq_tx_quarantine_source"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TranscriptEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("turn_id", models.UUIDField(db_index=True)),
                ("role", models.CharField(choices=[("user", "User"), ("assistant", "Assistant")], max_length=16)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("ios_queued", "iOS queued"),
                            ("ios_ondevice", "iOS on-device"),
                            ("telegram_poller", "Telegram poller"),
                            ("telegram_webhook", "Telegram webhook"),
                            ("line", "LINE"),
                            ("buffered", "Buffered"),
                            ("assistant_reply", "Assistant reply"),
                            ("proactive", "Proactive"),
                        ],
                        max_length=24,
                    ),
                ),
                ("source_event_id", models.CharField(max_length=255)),
                ("revision", models.PositiveSmallIntegerField(default=0)),
                (
                    "channel",
                    models.CharField(
                        choices=[("ios", "iOS"), ("telegram", "Telegram"), ("line", "LINE")], max_length=16
                    ),
                ),
                ("thread_key", models.CharField(blank=True, default="", max_length=255)),
                ("occurred_at", models.DateTimeField()),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                ("text_enc", models.BinaryField()),
                ("content_hash", models.CharField(max_length=64)),
                ("model_response_ref", models.CharField(blank=True, default="", max_length=255)),
                (
                    "delivery_state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Not applicable"),
                            ("sent", "Sent"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                            ("ambiguous", "Ambiguous"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("delivered_chunks", models.PositiveSmallIntegerField(default=0)),
                ("total_chunks", models.PositiveSmallIntegerField(default=0)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcript_events",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["tenant", "thread_key", "occurred_at"], name="tx_event_thread_time_idx"),
                    models.Index(fields=["tenant", "occurred_at"], name="tx_event_tenant_time_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "source_type", "source_event_id", "revision"),
                        name="uq_tx_event_source_revision",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TranscriptIndexOutbox",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("turn_id", models.UUIDField()),
                ("thread_key", models.CharField(blank=True, default="", max_length=255)),
                (
                    "channel",
                    models.CharField(
                        choices=[("ios", "iOS"), ("telegram", "Telegram"), ("line", "LINE")], max_length=16
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.CharField(blank=True, default="", max_length=512)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcript_index_outbox_rows",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("tenant", "turn_id"), name="uq_tx_outbox_turn")],
            },
        ),
        migrations.RunSQL(APPLY_SQL, REVERSE_SQL),
    ]
