# Generated by Django 5.1.15 on 2026-02-20 07:57

import django.contrib.postgres.fields
import django.db.models.deletion
import pgvector.django.vector
from pgvector.django import VectorExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0013_tenant_container_image_tag'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The lesson/insight in 1-3 sentences')),
                ('context', models.TextField(blank=True, help_text='Where this came from — conversation, article, experience')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536, help_text='OpenAI text-embedding-3-small', null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, help_text='Auto-generated + user-editable', size=None)),
                ('cluster_id', models.IntegerField(help_text='Assigned by clustering algorithm', null=True)),
                ('cluster_label', models.CharField(blank=True, help_text='Human-readable cluster name', max_length=200)),
                ('source_type', models.CharField(choices=[('conversation', 'Conversation'), ('journal', 'Journal Entry'), ('reflection', 'Reflection'), ('article', 'Article/Reading'), ('experience', 'Life Experience')], max_length=30)),
                ('source_ref', models.CharField(blank=True, help_text='Reference to source (daily note date, URL, etc.)', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('suggested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('shared', models.BooleanField(default=False)),
                ('shared_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='tenants.tenant')),
            ],
            options={
                'db_table': 'lessons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField(help_text='Cosine similarity score (0-1)')),
                ('connection_type', models.CharField(choices=[('similar', 'Similar Topic'), ('builds_on', 'Builds On'), ('contradicts', 'Contradicts'), ('user_linked', 'User Linked')], default='similar', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_out', to='lessons.lesson')),
                ('to_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_in', to='lessons.lesson')),
            ],
            options={
                'db_table': 'lesson_connections',
            },
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['tenant', 'status'], name='lessons_tenant__89fd4c_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['tenant', 'cluster_id'], name='lessons_tenant__f331a3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonconnection',
            unique_together={('from_lesson', 'to_lesson')},
        ),
    ]
