# Generated by Django 5.1.15 on 2026-06-02 05:34

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0002_lesson_position_xy"),
        ("tenants", "0077_alter_tenant_openclaw_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="StarJournalEntry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("text", models.TextField()),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("tutoring", "Written after a tutoring session"),
                            ("revisit", "Written when revisiting the star"),
                            ("free", "Free reflection on this topic"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100), default=list, size=None
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "star_journal_entries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TutoringSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("messages", models.JSONField(default=list)),
                (
                    "phases_completed",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        default=list,
                        help_text="Phases completed in order: restate, deepen, stress_test, connect, apply",
                        size=None,
                    ),
                ),
                ("mastery_achieved", models.BooleanField(default=False)),
                ("new_star_stage", models.CharField(blank=True, max_length=20, null=True)),
                ("skipped", models.BooleanField(default=False)),
                ("player_restated_accurately", models.BooleanField(null=True)),
                ("player_found_edge_cases", models.BooleanField(null=True)),
                ("connections_made", models.JSONField(default=list)),
                ("topic_shifted", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "tutoring_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="galaxy_note",
            field=models.TextField(blank=True, help_text="Player's pinned note visible from the galaxy view"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="last_tutored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="last_visited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="star_stage",
            field=models.CharField(
                choices=[
                    ("proto", "Proto-star"),
                    ("ignited", "Ignited"),
                    ("radiant", "Radiant"),
                    ("supernova", "Supernova"),
                ],
                default="proto",
                help_text="Visual/cognitive stage in the constellation game",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="tutoring_sessions_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(fields=["tenant", "star_stage"], name="lessons_tenant__82a63b_idx"),
        ),
        migrations.AddField(
            model_name="starjournalentry",
            name="star",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="journal_entries", to="lessons.lesson"
            ),
        ),
        migrations.AddField(
            model_name="starjournalentry",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="star_journal_entries", to="tenants.tenant"
            ),
        ),
        migrations.AddField(
            model_name="tutoringsession",
            name="star",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="tutoring_sessions", to="lessons.lesson"
            ),
        ),
        migrations.AddIndex(
            model_name="starjournalentry",
            index=models.Index(fields=["star", "created_at"], name="star_journa_star_id_d7da6e_idx"),
        ),
        migrations.AddIndex(
            model_name="starjournalentry",
            index=models.Index(fields=["tenant", "created_at"], name="star_journa_tenant__45aec6_idx"),
        ),
        migrations.AddIndex(
            model_name="tutoringsession",
            index=models.Index(fields=["star", "created_at"], name="tutoring_se_star_id_f14335_idx"),
        ),
    ]
