# Generated by Django 5.1.15 on 2026-07-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0003_add_star_lifecycle_and_tutoring"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("conversation", "Conversation"),
                    ("journal", "Journal Entry"),
                    ("reflection", "Reflection"),
                    ("article", "Article/Reading"),
                    ("experience", "Life Experience"),
                    ("shared", "Adopted from a neighbor"),
                ],
                max_length=30,
            ),
        ),
    ]
