# Generated by Django 5.1.15 on 2026-07-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0004_alter_lesson_source_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="pillar",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gravity", "Gravity"),
                    ("fuel", "Fuel"),
                    ("core", "Core"),
                    ("lessons", "Lessons"),
                    ("constellation", "Constellation"),
                    ("horizons", "Horizons"),
                    ("journal", "Journal"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
