# Generated by Django 6.0.7 on 2026-07-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0006_backfill_lesson_pillar"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="context_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="galaxy_note_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="text_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="starjournalentry",
            name="text_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="tutoringsession",
            name="connections_made_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="tutoringsession",
            name="messages_enc",
            field=models.BinaryField(null=True),
        ),
    ]
