# Generated by Django 6.0.7 on 2026-08-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0007_lesson_context_enc_lesson_galaxy_note_enc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="pii_receipts",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="starjournalentry",
            name="pii_receipts",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
