# Generated by Django 5.1.15 on 2026-07-05 01:25

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0096_tenant_friends_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FriendInvite",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("token", models.CharField(max_length=64, unique=True)),
                ("prefill_email", models.EmailField(blank=True, max_length=254)),
                ("max_uses", models.PositiveIntegerField(default=1)),
                ("uses", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inviter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="friend_invites", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "friend_invites",
            },
        ),
        migrations.CreateModel(
            name="Friendship",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("pair_key", models.CharField(editable=False, max_length=73, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("revoked", "Revoked"),
                            ("blocked", "Blocked"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("requested_via", models.CharField(default="handle", max_length=16)),
                ("invite_note", models.CharField(blank=True, max_length=280)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "addressee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="waves_received", to="tenants.tenant"
                    ),
                ),
                (
                    "blocked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "invite",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="friends.friendinvite"
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="waves_sent", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "friendships",
            },
        ),
        migrations.CreateModel(
            name="NeighborProfile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("handle", models.CharField(max_length=30, unique=True)),
                ("display_name", models.CharField(max_length=80)),
                ("bio", models.CharField(blank=True, max_length=280)),
                ("avatar_hue", models.IntegerField(default=210)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="neighbor_profile",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "neighbor_profiles",
            },
        ),
        migrations.AddIndex(
            model_name="friendinvite",
            index=models.Index(fields=["token"], name="friend_invi_token_5666ba_idx"),
        ),
        migrations.AddIndex(
            model_name="friendship",
            index=models.Index(fields=["addressee", "status"], name="friendships_address_4da91f_idx"),
        ),
        migrations.AddIndex(
            model_name="friendship",
            index=models.Index(fields=["requester", "status"], name="friendships_request_74cfa7_idx"),
        ),
        migrations.AddConstraint(
            model_name="friendship",
            constraint=models.UniqueConstraint(fields=("pair_key",), name="uq_friendship_pair"),
        ),
        migrations.AddConstraint(
            model_name="friendship",
            constraint=models.CheckConstraint(
                condition=models.Q(("requester", models.F("addressee")), _negated=True), name="friendship_no_self"
            ),
        ),
        migrations.AddIndex(
            model_name="neighborprofile",
            index=models.Index(fields=["handle"], name="neighbor_pr_handle_eb2f70_idx"),
        ),
    ]
