# Generated by Django 5.1.15 on 2026-07-05 02:31

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friends", "0001_initial"),
        ("lessons", "0004_alter_lesson_source_type"),
        ("tenants", "0097_relock_after_friends_edge"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedLesson",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("redacted_text", models.TextField(blank=True)),
                ("redacted_context", models.TextField(blank=True)),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100), default=list, size=None
                    ),
                ),
                ("cluster_label", models.CharField(blank=True, max_length=200)),
                ("position_x", models.FloatField(blank=True, null=True)),
                ("position_y", models.FloatField(blank=True, null=True)),
                ("star_stage", models.CharField(default="proto", max_length=20)),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                (
                    "scrub_status",
                    models.CharField(
                        choices=[
                            ("pending", "Scrub pending"),
                            ("ready", "Scrubbed & publishable"),
                            ("failed", "Blocked (fail-closed)"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("scrub_model_version", models.CharField(blank=True, max_length=40)),
                ("scrub_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("scrubbed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner_tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="shared_lessons", to="tenants.tenant"
                    ),
                ),
                (
                    "source_lesson",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="shared_snapshot", to="lessons.lesson"
                    ),
                ),
            ],
            options={
                "db_table": "shared_lessons",
            },
        ),
        migrations.CreateModel(
            name="LessonShareGrant",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("revoked", "Revoked")], default="active", max_length=8
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "friendship",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_grants",
                        to="friends.friendship",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="grants", to="friends.sharedlesson"
                    ),
                ),
            ],
            options={
                "db_table": "lesson_share_grants",
            },
        ),
        migrations.CreateModel(
            name="PendingShare",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("proposed_by", models.CharField(default="agent", max_length=8)),
                ("source_context", models.TextField(blank=True)),
                ("preview_text", models.TextField(blank=True)),
                ("final_text", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("edited", "Edited & approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("blocked", "Blocked (scrub failed)"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("telegram_message_id", models.BigIntegerField(blank=True, null=True)),
                ("line_message_token", models.CharField(blank=True, max_length=120)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "source_lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="pending_shares", to="lessons.lesson"
                    ),
                ),
                (
                    "target_friendship",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="friends.friendship"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="pending_shares", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "pending_shares",
                "indexes": [
                    models.Index(fields=["tenant", "status"], name="pending_sha_tenant__a9eb44_idx"),
                    models.Index(fields=["target_friendship", "status"], name="pending_sha_target__0e5578_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="sharedlesson",
            index=models.Index(fields=["owner_tenant", "scrub_status"], name="shared_less_owner_t_cf66f9_idx"),
        ),
        migrations.AddIndex(
            model_name="lessonsharegrant",
            index=models.Index(fields=["friendship", "status"], name="lesson_shar_friends_245762_idx"),
        ),
        migrations.AddConstraint(
            model_name="lessonsharegrant",
            constraint=models.CheckConstraint(
                condition=models.Q(("friendship__isnull", False)), name="grant_exactly_one_audience"
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonsharegrant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("friendship__isnull", False)),
                fields=("shared_lesson", "friendship"),
                name="uq_grant_friendship",
            ),
        ),
    ]
