# Generated by Django 5.1.15 on 2026-07-05 03:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friends", "0002_sharedlesson_lessonsharegrant_pendingshare_and_more"),
        ("tenants", "0098_relock_after_shared_lessons"),
    ]

    operations = [
        migrations.CreateModel(
            name="WormholeVisit",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("last_visited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "friendship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="friends.friendship"
                    ),
                ),
                (
                    "viewer_tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="wormhole_visits", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "friend_wormhole_visits",
                "constraints": [
                    models.UniqueConstraint(fields=("viewer_tenant", "friendship"), name="uq_wormhole_visit")
                ],
            },
        ),
    ]
