# Generated by Django 5.1.15 on 2026-07-05 04:02

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friends", "0003_wormholevisit"),
        ("tenants", "0099_relock_after_wormhole_visits"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbsorbedItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "source_kind",
                    models.CharField(
                        choices=[("shared_lesson", "Shared spark"), ("friend_message", "Chat")], max_length=16
                    ),
                ),
                ("source_id", models.UUIDField()),
                ("label", models.CharField(blank=True, max_length=200)),
                ("absorbed_at", models.DateTimeField(auto_now_add=True)),
                ("purged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "from_tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="absorbed_items", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "friend_absorbed_items",
                "indexes": [
                    models.Index(fields=["tenant", "purged_at"], name="friend_abso_tenant__e2b86e_idx"),
                    models.Index(fields=["tenant", "from_tenant"], name="friend_abso_tenant__8dd04f_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("tenant", "source_kind", "source_id"), name="uq_absorbed_item")
                ],
            },
        ),
    ]
