# Generated by Django 5.1.15 on 2026-07-05 04:36

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friends", "0004_absorbeditem"),
        ("tenants", "0100_relock_after_absorbed_items"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FriendThread",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(choices=[("direct", "1:1"), ("circle", "Circle")], default="direct", max_length=8),
                ),
                ("title", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_message_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="threads_started", to="tenants.tenant"
                    ),
                ),
                (
                    "friendship",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thread",
                        to="friends.friendship",
                    ),
                ),
            ],
            options={
                "db_table": "friend_threads",
            },
        ),
        migrations.CreateModel(
            name="FriendMessage",
            fields=[
                ("seq", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("client_msg_id", models.CharField(max_length=64)),
                ("text", models.TextField()),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sender_tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
                (
                    "sender_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="friends.friendthread"
                    ),
                ),
            ],
            options={
                "db_table": "friend_messages",
            },
        ),
        migrations.CreateModel(
            name="FriendThreadMembership",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("role", models.CharField(default="member", max_length=8)),
                ("muted", models.BooleanField(default=False)),
                ("agent_absorb_enabled", models.BooleanField(default=True)),
                ("last_read_seq", models.BigIntegerField(default=0)),
                ("last_absorbed_seq", models.BigIntegerField(default=0)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thread_memberships",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="friends.friendthread",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "friend_thread_memberships",
            },
        ),
        migrations.AddConstraint(
            model_name="friendthread",
            constraint=models.UniqueConstraint(
                condition=models.Q(("friendship__isnull", False)), fields=("friendship",), name="uq_direct_thread"
            ),
        ),
        migrations.AddIndex(
            model_name="friendmessage",
            index=models.Index(fields=["thread", "created_at", "seq"], name="friend_mess_thread__06e996_idx"),
        ),
        migrations.AddConstraint(
            model_name="friendmessage",
            constraint=models.UniqueConstraint(fields=("sender_tenant", "client_msg_id"), name="uq_friend_msg_idem"),
        ),
        migrations.AddIndex(
            model_name="friendthreadmembership",
            index=models.Index(fields=["tenant", "left_at"], name="friend_thre_tenant__9167c5_idx"),
        ),
        migrations.AddConstraint(
            model_name="friendthreadmembership",
            constraint=models.UniqueConstraint(fields=("thread", "tenant"), name="uq_thread_member"),
        ),
    ]
