# Generated by Django 5.1.15 on 2026-07-05 05:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friends", "0005_friendthread_friendmessage_friendthreadmembership_and_more"),
        ("journal", "0021_purpose_north_star"),
        ("tenants", "0101_relock_after_friend_chat"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedGoal",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("pillar", models.CharField(blank=True, max_length=20)),
                ("target", models.JSONField(default=dict)),
                ("target_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("achieved", "Achieved"),
                            ("abandoned", "Abandoned"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=0)),
                ("edit_lock_until", models.DateTimeField(blank=True, null=True)),
                ("edit_lock_owner", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("achieved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missions_created",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "friendship",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="friends.friendship"
                    ),
                ),
            ],
            options={
                "db_table": "shared_goals",
            },
        ),
        migrations.CreateModel(
            name="SharedGoalUpdate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("joined", "Joined"),
                            ("task_added", "Task added"),
                            ("task_completed", "Task completed"),
                            ("milestone", "Milestone"),
                            ("note", "Note"),
                            ("progress", "Progress"),
                        ],
                        max_length=16,
                    ),
                ),
                ("text", models.TextField(blank=True)),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "shared_goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="updates", to="friends.sharedgoal"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "shared_goal_updates",
            },
        ),
        migrations.CreateModel(
            name="PendingGoalAction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("kind", models.CharField(default="add_task", max_length=16)),
                ("suggested", models.JSONField(default=dict)),
                ("status", models.CharField(default="pending", max_length=10)),
                ("telegram_message_id", models.BigIntegerField(blank=True, null=True)),
                ("line_message_token", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "task",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="journal.task"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_goal_actions",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "shared_goal",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="friends.sharedgoal"),
                ),
            ],
            options={
                "db_table": "pending_goal_actions",
                "indexes": [models.Index(fields=["tenant", "status"], name="pending_goa_tenant__ef282e_idx")],
            },
        ),
        migrations.CreateModel(
            name="SharedGoalMembership",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("role", models.CharField(default="member", max_length=8)),
                ("status", models.CharField(default="active", max_length=8)),
                ("commitment", models.CharField(blank=True, max_length=200)),
                ("last_digest_window", models.CharField(blank=True, max_length=24)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                (
                    "shared_goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="friends.sharedgoal"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mission_memberships",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "shared_goal_memberships",
                "indexes": [models.Index(fields=["tenant", "left_at"], name="shared_goal_tenant__24ee58_idx")],
                "constraints": [models.UniqueConstraint(fields=("shared_goal", "tenant"), name="uq_mission_member")],
            },
        ),
    ]
