# Generated by Django 5.1.15 on 2026-07-05 05:52

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friends", "0006_sharedgoal_sharedgoalupdate_pendinggoalaction_and_more"),
        ("tenants", "0102_relock_after_missions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Circle",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("hue", models.PositiveSmallIntegerField(default=210)),
                ("invite_code", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "friend_circles",
            },
        ),
        migrations.CreateModel(
            name="CircleMembership",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("role", models.CharField(default="member", max_length=8)),
                ("share_preferences", models.JSONField(default=dict)),
                ("agent_absorb_enabled", models.BooleanField(default=True)),
                ("muted", models.BooleanField(default=False)),
                ("status", models.CharField(default="active", max_length=8)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "friend_circle_memberships",
            },
        ),
        migrations.CreateModel(
            name="ContentReport",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "target_kind",
                    models.CharField(
                        choices=[("shared_lesson", "Shared spark"), ("friend_message", "Chat")], max_length=16
                    ),
                ),
                ("reason", models.CharField(max_length=280)),
                ("status", models.CharField(default="open", max_length=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "content_reports",
            },
        ),
        migrations.RemoveConstraint(
            model_name="lessonsharegrant",
            name="grant_exactly_one_audience",
        ),
        migrations.AddField(
            model_name="circle",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="circles_created", to="tenants.tenant"
            ),
        ),
        migrations.AddField(
            model_name="absorbeditem",
            name="circle",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="friends.circle"
            ),
        ),
        migrations.AddField(
            model_name="friendinvite",
            name="circle",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="friends.circle"
            ),
        ),
        migrations.AddField(
            model_name="friendthread",
            name="circle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threads",
                to="friends.circle",
            ),
        ),
        migrations.AddField(
            model_name="lessonsharegrant",
            name="circle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_grants",
                to="friends.circle",
            ),
        ),
        migrations.AddField(
            model_name="pendingshare",
            name="target_circle",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="friends.circle"
            ),
        ),
        migrations.AddField(
            model_name="sharedgoal",
            name="circle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="missions",
                to="friends.circle",
            ),
        ),
        migrations.AddIndex(
            model_name="lessonsharegrant",
            index=models.Index(fields=["circle", "status"], name="lesson_shar_circle__e806cd_idx"),
        ),
        migrations.AddConstraint(
            model_name="lessonsharegrant",
            constraint=models.CheckConstraint(
                condition=models.Q(("friendship__isnull", False), ("circle__isnull", False), _connector="XOR"),
                name="grant_exactly_one_audience",
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonsharegrant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("circle__isnull", False)),
                fields=("shared_lesson", "circle"),
                name="uq_grant_circle",
            ),
        ),
        migrations.AddField(
            model_name="circlemembership",
            name="circle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="friends.circle"
            ),
        ),
        migrations.AddField(
            model_name="circlemembership",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="circle_memberships", to="tenants.tenant"
            ),
        ),
        migrations.AddField(
            model_name="circlemembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="contentreport",
            name="friend_message",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="friends.friendmessage"
            ),
        ),
        migrations.AddField(
            model_name="contentreport",
            name="reporter_tenant",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"),
        ),
        migrations.AddField(
            model_name="contentreport",
            name="reporter_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="contentreport",
            name="shared_lesson",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="friends.sharedlesson"
            ),
        ),
        migrations.AddIndex(
            model_name="circlemembership",
            index=models.Index(fields=["tenant", "status"], name="friend_circ_tenant__b5c1ca_idx"),
        ),
        migrations.AddConstraint(
            model_name="circlemembership",
            constraint=models.UniqueConstraint(fields=("circle", "tenant"), name="uq_circle_tenant"),
        ),
        migrations.AddIndex(
            model_name="contentreport",
            index=models.Index(fields=["reporter_tenant", "status"], name="content_rep_reporte_acccc2_idx"),
        ),
    ]
