# Generated by Django 5.1.15 on 2026-07-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friends", "0008_friends_rls_backstop"),
    ]

    operations = [
        migrations.AddField(
            model_name="neighborprofile",
            name="accepted_terms_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="neighborprofile",
            name="accepted_terms_version",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="contentreport",
            name="target_kind",
            field=models.CharField(
                choices=[
                    ("shared_lesson", "Shared spark"),
                    ("friend_message", "Chat"),
                    ("general", "General / support"),
                ],
                max_length=16,
            ),
        ),
    ]
