# Generated by Django 5.1.15 on 2026-07-07 06:22

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friends", "0009_neighborprofile_accepted_terms_at_and_more"),
        ("tenants", "0105_enable_friends_propose_flagged_tenants"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkyMembership",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "friendship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="friends.friendship"
                    ),
                ),
                (
                    "viewer_tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sky_memberships", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "friend_sky_memberships",
                "indexes": [models.Index(fields=["viewer_tenant"], name="friend_sky__viewer__9ef981_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("viewer_tenant", "friendship"), name="uq_sky_membership")
                ],
            },
        ),
    ]
