# Generated by Django 6.0.7 on 2026-07-29 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friends", "0012_dedupe_pending_shares"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendship",
            name="acceptance_cutoff_seq",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
