# Generated by Django 6.0.7 on 2026-07-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friends", "0013_friendship_acceptance_cutoff_seq"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendship",
            name="acceptance_incarnation",
            field=models.BigIntegerField(default=0),
        ),
    ]
