# Generated by Django 5.1.15 on 2026-05-13 08:18

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0057_tenant_internal_api_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicRegistry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "pillar",
                    models.CharField(
                        choices=[
                            ("gravity", "Gravity"),
                            ("fuel", "Fuel"),
                            ("core", "Core"),
                            ("lessons", "Lessons"),
                            ("constellation", "Constellation"),
                            ("horizons", "Horizons"),
                            ("journal", "Journal"),
                        ],
                        max_length=32,
                    ),
                ),
                ("slug", models.SlugField(max_length=64)),
                ("display_name", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[("canonical", "Canonical"), ("proposed", "Proposed"), ("deprecated", "Deprecated")],
                        default="canonical",
                        max_length=16,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("seed", "Seed"),
                            ("proposed_by_model", "Proposed by model"),
                            ("promoted", "Promoted from proposal"),
                        ],
                        default="seed",
                        max_length=24,
                    ),
                ),
                ("proposed_by_model_version", models.CharField(blank=True, default="", max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("promoted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "parent_topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="insights.topicregistry",
                    ),
                ),
            ],
            options={
                "db_table": "insights_topic_registry",
                "ordering": ["pillar", "slug"],
            },
        ),
        migrations.CreateModel(
            name="TopicAlias",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("alias", models.CharField(max_length=128)),
                (
                    "source",
                    models.CharField(choices=[("seed", "Seed"), ("model", "Model")], default="seed", max_length=16),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="aliases", to="insights.topicregistry"
                    ),
                ),
            ],
            options={
                "db_table": "insights_topic_alias",
            },
        ),
        migrations.CreateModel(
            name="AssistantInsight",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "pillar",
                    models.CharField(
                        choices=[
                            ("gravity", "Gravity"),
                            ("fuel", "Fuel"),
                            ("core", "Core"),
                            ("lessons", "Lessons"),
                            ("constellation", "Constellation"),
                            ("horizons", "Horizons"),
                            ("journal", "Journal"),
                        ],
                        max_length=32,
                    ),
                ),
                ("statement", models.TextField()),
                ("evidence_refs", models.JSONField(blank=True, default=dict)),
                ("confidence", models.FloatField(default=0.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("confirmed", "Confirmed"),
                            ("refuted", "Refuted"),
                            ("expired", "Expired"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("last_refuted_at", models.DateTimeField(blank=True, null=True)),
                ("user_responses", models.JSONField(blank=True, default=list)),
                ("author_model_version", models.CharField(blank=True, default="", max_length=128)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assistant_insights",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="insights",
                        to="insights.topicregistry",
                    ),
                ),
            ],
            options={
                "db_table": "insights_assistant_insight",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserVoicePref",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "pillar",
                    models.CharField(
                        choices=[
                            ("gravity", "Gravity"),
                            ("fuel", "Fuel"),
                            ("core", "Core"),
                            ("lessons", "Lessons"),
                            ("constellation", "Constellation"),
                            ("horizons", "Horizons"),
                            ("journal", "Journal"),
                        ],
                        max_length=32,
                    ),
                ),
                ("register_offset", models.IntegerField(default=0)),
                (
                    "tone",
                    models.CharField(
                        choices=[("gentle", "Gentle"), ("direct", "Direct")], default="gentle", max_length=16
                    ),
                ),
                (
                    "volume",
                    models.CharField(
                        choices=[("silent", "Silent"), ("weekly", "Weekly"), ("live", "Live")],
                        default="weekly",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="voice_prefs", to="tenants.tenant"
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_prefs",
                        to="insights.topicregistry",
                    ),
                ),
            ],
            options={
                "db_table": "insights_user_voice_pref",
            },
        ),
        migrations.CreateModel(
            name="PillarSnapshot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "pillar",
                    models.CharField(
                        choices=[
                            ("gravity", "Gravity"),
                            ("fuel", "Fuel"),
                            ("core", "Core"),
                            ("lessons", "Lessons"),
                            ("constellation", "Constellation"),
                            ("horizons", "Horizons"),
                            ("journal", "Journal"),
                        ],
                        max_length=32,
                    ),
                ),
                ("ts", models.DateTimeField()),
                (
                    "granularity",
                    models.CharField(
                        choices=[("daily", "Daily"), ("weekly", "Weekly"), ("monthly", "Monthly")], max_length=16
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pillar_snapshots",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "insights_pillar_snapshot",
                "ordering": ["-ts"],
                "indexes": [models.Index(fields=["tenant", "pillar", "-ts"], name="insights_pi_tenant__465d0d_idx")],
            },
        ),
        migrations.AddIndex(
            model_name="topicregistry",
            index=models.Index(fields=["pillar", "status"], name="insights_to_pillar_d9f8cf_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="topicregistry",
            unique_together={("pillar", "slug")},
        ),
        migrations.AddIndex(
            model_name="topicalias",
            index=models.Index(fields=["alias"], name="insights_to_alias_67e331_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="topicalias",
            unique_together={("topic", "alias")},
        ),
        migrations.AddIndex(
            model_name="assistantinsight",
            index=models.Index(fields=["tenant", "pillar", "status"], name="insights_as_tenant__17b1b0_idx"),
        ),
        migrations.AddIndex(
            model_name="assistantinsight",
            index=models.Index(fields=["tenant", "topic"], name="insights_as_tenant__1f4e06_idx"),
        ),
        migrations.AddIndex(
            model_name="assistantinsight",
            index=models.Index(fields=["tenant", "-created_at"], name="insights_as_tenant__fc4eb7_idx"),
        ),
        migrations.AddIndex(
            model_name="uservoicepref",
            index=models.Index(fields=["tenant", "pillar"], name="insights_us_tenant__ffc81b_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="uservoicepref",
            unique_together={("tenant", "pillar", "topic")},
        ),
    ]
