# Generated by Django 6.0.7 on 2026-07-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insights", "0002_seed_canonical_topics"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistantinsight",
            name="statement_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="assistantinsight",
            name="user_responses_enc",
            field=models.BinaryField(null=True),
        ),
    ]
