"""Re-render and push ``workspace/AGENTS.md`` to every tenant's file share.

The per-tenant AGENTS.md is a flat file generated by
``apps.orchestrator.personas.render_workspace_files`` from a global
template (``templates/openclaw/AGENTS.md`` or the
``AZURE_KV_SECRET_AGENTS_MD`` Key Vault secret) with the per-tenant
persona personality + ``prompt_extras`` spliced in. It is *written* to
each tenant's Azure File Share at ``workspace/AGENTS.md`` and read by
the running OpenClaw container at session boot.

When the global template ships new instructions (e.g. PR #432's chat-
marker branching), tenants whose file shares predate the change keep
serving the old text until ``update_tenant_config`` runs for them —
which only fires when ``pending_config_version > config_version``.
``apply_pending_configs`` (the cron path) gets there eventually, but
fleet-wide rollouts that need the new instructions to be live *now*
need a non-lazy push.

This command:

  * Re-renders AGENTS.md per the latest template + persona + tenant
    prompt extras.
  * Compares the rendered content to the in-memory render that the
    last config push would have produced (cheap, no Azure read needed)
    and skips when ``prompt_extras`` are absent and the global template
    is unchanged for this run — but in practice we always push, since
    the file share has no read-cheap "compare current" API and the
    write itself is idempotent (last-write-wins of identical bytes).
  * Pushes the rendered file via ``upload_workspace_file`` per tenant.
  * Parallelises with the same ``ThreadPoolExecutor(max_workers=5)``
    pattern as ``bump_all_tenant_images`` to stay within Azure Storage
    rate limits.

Customizations: AGENTS.md is template-+-variables, not a flat blob the
user edits directly. The two pieces of per-tenant variation are the
agent persona (``user.preferences['agent_persona']``) and the prompt
extras (``user.preferences['prompt_extras']['agents_md']``). Both are
read fresh on every render, so refresh preserves them automatically —
the only thing this command clobbers is older versions of the global
boilerplate that the new template supersedes.

Usage:

    python manage.py refresh_persona_agents_md                # all active
    python manage.py refresh_persona_agents_md --include-hibernated
    python manage.py refresh_persona_agents_md --dry-run
    python manage.py refresh_persona_agents_md --tenant <uuid>   # single
"""

from __future__ import annotations

import concurrent.futures
import logging

from django.core.management.base import BaseCommand, CommandError

from apps.orchestrator.azure_client import upload_workspace_file
from apps.orchestrator.personas import render_workspace_files
from apps.tenants.models import Tenant

logger = logging.getLogger(__name__)

_DEFAULT_MAX_WORKERS = 5
_AGENTS_MD_PATH = "workspace/AGENTS.md"


class Command(BaseCommand):
    help = "Re-render workspace/AGENTS.md and push it to every tenant's file share."

    def add_arguments(self, parser):
        parser.add_argument(
            "--tenant",
            default=None,
            help="Single tenant UUID (default: every active tenant)",
        )
        parser.add_argument(
            "--include-hibernated",
            action="store_true",
            help="Also refresh hibernated tenants (default: skip — they pick up on next wake)",
        )
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Show what would happen without uploading anything",
        )
        parser.add_argument(
            "--max-workers",
            type=int,
            default=_DEFAULT_MAX_WORKERS,
            help=f"Max concurrent storage uploads (default: {_DEFAULT_MAX_WORKERS})",
        )

    def handle(self, *args, **options):
        include_hibernated = options["include_hibernated"]
        dry_run = options["dry_run"]
        max_workers = max(1, options["max_workers"])

        if options["tenant"]:
            qs = Tenant.objects.filter(id=options["tenant"])
        else:
            qs = Tenant.objects.filter(
                status=Tenant.Status.ACTIVE,
                container_id__gt="",
            )
            if not include_hibernated:
                qs = qs.filter(hibernated_at__isnull=True)

        tenants = list(qs.select_related("user"))
        if not tenants:
            raise CommandError("No matching tenants found")

        prefix = "[DRY RUN] " if dry_run else ""
        self.stdout.write(f"{prefix}Refreshing AGENTS.md for {len(tenants)} tenant(s) (concurrency: {max_workers})")

        if dry_run:
            for tenant in tenants:
                persona_key = (tenant.user.preferences or {}).get("agent_persona", "neighbor")
                self.stdout.write(
                    f"  [dry-run] {tenant.container_id or '(no container)'} "
                    f"({str(tenant.id)[:8]}): persona={persona_key}"
                )
            return

        succeeded = 0
        failed = 0
        with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as pool:
            futures = {pool.submit(self._refresh_one, tenant): tenant for tenant in tenants}
            for future in concurrent.futures.as_completed(futures):
                tenant = futures[future]
                tid = str(tenant.id)[:8]
                try:
                    future.result()
                    succeeded += 1
                    self.stdout.write(
                        self.style.SUCCESS(f"  {tenant.container_id or '(no container)'} ({tid}): refreshed")
                    )
                except Exception as exc:
                    failed += 1
                    self.stderr.write(
                        self.style.ERROR(f"  {tenant.container_id or '(no container)'} ({tid}): FAILED — {exc}")
                    )

        self.stdout.write(f"Done: {succeeded} refreshed, {failed} failed")
        if failed:
            raise CommandError(f"{failed} tenant(s) failed to refresh — see errors above")

    def _refresh_one(self, tenant: Tenant) -> None:
        """Render AGENTS.md for one tenant and push to their file share.

        Runs inside the thread pool. Each call:

          1. Reads the persona key from ``user.preferences``.
          2. Calls ``render_workspace_files`` (which itself loads the
             global template, splices in persona personality, and appends
             tenant prompt extras).
          3. Uploads the rendered string to ``workspace/AGENTS.md`` on
             the tenant's Azure File Share — overwriting the prior file.

        The upload is idempotent at the SMB level (writing identical
        bytes is a no-op on the running container's view), so calling
        this command repeatedly is safe.
        """
        persona_key = (tenant.user.preferences or {}).get("agent_persona", "neighbor")
        rendered = render_workspace_files(persona_key, tenant=tenant)
        content = rendered.get("NBHD_AGENTS_MD", "")
        if not content:
            # Highly unusual — render_workspace_files always returns this
            # key. Surface as an error so we don't silently no-op.
            raise RuntimeError("render_workspace_files returned empty NBHD_AGENTS_MD")

        upload_workspace_file(str(tenant.id), _AGENTS_MD_PATH, content)
